# Include
include:
  - local: 'lint/.lint-gitlab-ci-template-master.yml'
  - local: 'code-quality/.code-climate.yml'

code-quality:
  extends: .code-quality
  stage: lint
  only:
    refs:
      - merge_requests
      - master
      - tags
      - /^release\/\d+\.\d+.*$/

flake8:
  extends: .flake8

hocon-lint:
  extends: .hocon-lint

json-lint:
  extends: .json-lint

legacy-script-check:
  extends: .legacy-script-check

python-version-check:
  extends: .python-version-check

plansdk-deprecated-check:
  extends: .plansdk-deprecated-check
