circuit_devices_single_cpe = [
    {
        "CIRC_PATH_INST_ID": "2421975",
        "PATH_NAME": "95.L1XX.004421..CHTR",
        "PATH_REV": "1",
        "PATH_CATEGORY": "ETHERNET",
        "PATH_A_SITE": "SNAQTXKY-TWC/COLO-LEVEL3-SYNERGY SAN ANTONIO (SNAQTXL3) (NBB)",
        "PATH_Z_SITE": "LARETXNR-CARRIER ENTERPRISE LLC//4102 AIRPARK DR",
        "A_CLLI": "SNAQTXKY",
        "Z_CLLI": "LARETXNR",
        "PATH_A_SITE_TYPE": "COLO-NETWORK",
        "PATH_Z_SITE_TYPE": "LOCAL",
        "TOPOLOGY": "Point-to-point",
        "PATH_STATUS": "Live",
        "CLASS_OF_SERVICE": "BRONZE REGIONAL",
        "SLM_ELIGIBILITY": "ELIGIBLE DESIGN",
        "EVC_ID": "426369",
        "SERVICE_TYPE": "CAR-E-ACCESS FIBER/FIBER EPL",
        "BANDWIDTH": "20 Mbps",
        "BW_SIZE": "20000000",
        "CUSTOMER_ID": "ACCT-21122235",
        "CUSTOMER_NAME": "LEVEL 3 NEW TWCC",
        "IPV4_GLUE_SUBNET": None,
        "IPV4_ASSIGNED_SUBNETS": None,
        "IPV4_ASSIGNED_GATEWAY": None,
        "IPV4_SERVICE_TYPE": None,
        "IPV6_GLUE_SUBNET": None,
        "IPV6_ASSIGNED_SUBNETS": None,
        "IPV6_SERVICE_TYPE": None,
        "CUSTOMER_TYPE": "CARRIER",
        "ORDER_REFERENCE": "1.",
        "PARENT_SEQUENCE": None,
        "PARENT_MEMBER_NBR": None,
        "SEQUENCE": "1",
        "MEMBER_NBR": None,
        "LEG_NAME": "1",
        "LEG_INST_ID": "2783107",
        "A_SITE_NAME": "SNAQTXKY-TWC/COLO-LEVEL3-SYNERGY SAN ANTONIO (SNAQTXL3) (NBB)",
        "Z_SITE_NAME": None,
        "ELEMENT_TYPE": "PORT",
        "ELEMENT_NAME": "SNAQTXKY2AW/C001.0102.001.005.16/NIU",
        "ELEMENT_REFERENCE": "857566",
        "ELEMENT_CATEGORY": "NIU",
        "ELEMENT_STATUS": "Live",
        "ELEMENT_BANDWIDTH": "20 Mbps",
        "NEXT_PATH_INST_ID": None,
        "PREV_PATH_INST_ID": None,
        "CHAN_NAME": None,
        "CHAN_INST_ID": None,
        "SLOT": "3/1",
        "PORT_NAME": "1-105",
        "PORT_INST_ID": "114706101",
        "PORT_ACCESS_ID": "3/1",
        "CONNECTOR_TYPE": "LC",
        "FQDN": "SNAQTXKY2AW.CHTRSE.COM",
        "MODEL": "ETX-220A",
        "VENDOR": "RAD",
        "TID": "SNAQTXKY2AW",
        "LEGACY_EQUIP_SOURCE": "L-TWC",
        "PURCHASING_GROUP": "ENTERPRISE",
        "IPV4_ADDRESS": "10.4.216.2/24",
        "IPV6_ADDRESS": None,
        "C_VLAN": None,
        "CUST_S_VLAN": "2522",
        "S_VLAN": "2522",
        "VLAN_OPERATION": None,
        "PORT_ROLE": "ENNI",
        "INITIAL_PATH_NAME": "95.L1XX.004421..CHTR",
        "INITIAL_CIRCUIT_ID": "2421975",
        "LVL": "1",
    },
    {
        "CIRC_PATH_INST_ID": "2421975",
        "PATH_NAME": "95.L1XX.004421..CHTR",
        "PATH_REV": "1",
        "PATH_CATEGORY": "ETHERNET",
        "PATH_A_SITE": "SNAQTXKY-TWC/COLO-LEVEL3-SYNERGY SAN ANTONIO (SNAQTXL3) (NBB)",
        "PATH_Z_SITE": "LARETXNR-CARRIER ENTERPRISE LLC//4102 AIRPARK DR",
        "A_CLLI": "SNAQTXKY",
        "Z_CLLI": "LARETXNR",
        "PATH_A_SITE_TYPE": "COLO-NETWORK",
        "PATH_Z_SITE_TYPE": "LOCAL",
        "TOPOLOGY": "Point-to-point",
        "PATH_STATUS": "Live",
        "CLASS_OF_SERVICE": "BRONZE REGIONAL",
        "SLM_ELIGIBILITY": "ELIGIBLE DESIGN",
        "EVC_ID": "426369",
        "SERVICE_TYPE": "CAR-E-ACCESS FIBER/FIBER EPL",
        "BANDWIDTH": "20 Mbps",
        "BW_SIZE": "20000000",
        "CUSTOMER_ID": "ACCT-21122235",
        "CUSTOMER_NAME": "LEVEL 3 NEW TWCC",
        "IPV4_GLUE_SUBNET": None,
        "IPV4_ASSIGNED_SUBNETS": None,
        "IPV4_ASSIGNED_GATEWAY": None,
        "IPV4_SERVICE_TYPE": None,
        "IPV6_GLUE_SUBNET": None,
        "IPV6_ASSIGNED_SUBNETS": None,
        "IPV6_SERVICE_TYPE": None,
        "CUSTOMER_TYPE": "CARRIER",
        "ORDER_REFERENCE": "6.",
        "PARENT_SEQUENCE": None,
        "PARENT_MEMBER_NBR": None,
        "SEQUENCE": "6",
        "MEMBER_NBR": None,
        "LEG_NAME": "1",
        "LEG_INST_ID": "2783107",
        "A_SITE_NAME": "LARETXNR-CARRIER ENTERPRISE LLC//4102 AIRPARK DR",
        "Z_SITE_NAME": None,
        "ELEMENT_TYPE": "PORT",
        "ELEMENT_NAME": "LARETXNR1ZW/999.9999.999.99/SWT",
        "ELEMENT_REFERENCE": "1732692",
        "ELEMENT_CATEGORY": "SWITCH",
        "ELEMENT_STATUS": "Live",
        "ELEMENT_BANDWIDTH": "10/100/1000 BASET",
        "NEXT_PATH_INST_ID": None,
        "PREV_PATH_INST_ID": None,
        "CHAN_NAME": None,
        "CHAN_INST_ID": None,
        "SLOT": "CHASSIS PORTS",
        "PORT_NAME": "03",
        "PORT_INST_ID": "114706095",
        "PORT_ACCESS_ID": "ACCESS-1-1-1-3",
        "CONNECTOR_TYPE": "RJ-45",
        "FQDN": "LARETXNR1ZW.CML.CHTRSE.COM",
        "MODEL": "FSP 150-GE114PRO-C",
        "VENDOR": "ADVA",
        "TID": "LARETXNR1ZW",
        "LEGACY_EQUIP_SOURCE": None,
        "PURCHASING_GROUP": "ENTERPRISE",
        "IPV4_ADDRESS": "DHCP",
        "IPV6_ADDRESS": None,
        "C_VLAN": None,
        "CUST_S_VLAN": None,
        "S_VLAN": "2522",
        "VLAN_OPERATION": "PUSH",
        "PORT_ROLE": "UNI-EP",
        "INITIAL_PATH_NAME": "95.L1XX.004421..CHTR",
        "INITIAL_CIRCUIT_ID": "2421975",
        "LVL": "1",
    },
]

granite_cpe_data_single_cpe = [
    {
        "CIRC_PATH_INST_ID": "2421975",
        "PATH_NAME": "95.L1XX.004421..CHTR",
        "PATH_REV": "1",
        "PATH_CATEGORY": "ETHERNET",
        "PATH_A_SITE": "SNAQTXKY-TWC/COLO-LEVEL3-SYNERGY SAN ANTONIO (SNAQTXL3) (NBB)",
        "PATH_Z_SITE": "LARETXNR-CARRIER ENTERPRISE LLC//4102 AIRPARK DR",
        "A_CLLI": "SNAQTXKY",
        "Z_CLLI": "LARETXNR",
        "PATH_A_SITE_TYPE": "COLO-NETWORK",
        "PATH_Z_SITE_TYPE": "LOCAL",
        "TOPOLOGY": "Point-to-point",
        "PATH_STATUS": "Live",
        "CLASS_OF_SERVICE": "BRONZE REGIONAL",
        "SLM_ELIGIBILITY": "ELIGIBLE DESIGN",
        "EVC_ID": "426369",
        "SERVICE_TYPE": "CAR-E-ACCESS FIBER/FIBER EPL",
        "BANDWIDTH": "20 Mbps",
        "BW_SIZE": "20000000",
        "CUSTOMER_ID": "ACCT-21122235",
        "CUSTOMER_NAME": "LEVEL 3 NEW TWCC",
        "IPV4_GLUE_SUBNET": None,
        "IPV4_ASSIGNED_SUBNETS": None,
        "IPV4_ASSIGNED_GATEWAY": None,
        "IPV4_SERVICE_TYPE": None,
        "IPV6_GLUE_SUBNET": None,
        "IPV6_ASSIGNED_SUBNETS": None,
        "IPV6_SERVICE_TYPE": None,
        "CUSTOMER_TYPE": "CARRIER",
        "ORDER_REFERENCE": "6.",
        "PARENT_SEQUENCE": None,
        "PARENT_MEMBER_NBR": None,
        "SEQUENCE": "6",
        "MEMBER_NBR": None,
        "LEG_NAME": "1",
        "LEG_INST_ID": "2783107",
        "A_SITE_NAME": "LARETXNR-CARRIER ENTERPRISE LLC//4102 AIRPARK DR",
        "Z_SITE_NAME": None,
        "ELEMENT_TYPE": "PORT",
        "ELEMENT_NAME": "LARETXNR1ZW/999.9999.999.99/SWT",
        "ELEMENT_REFERENCE": "1732692",
        "ELEMENT_CATEGORY": "SWITCH",
        "ELEMENT_STATUS": "Live",
        "ELEMENT_BANDWIDTH": "10/100/1000 BASET",
        "NEXT_PATH_INST_ID": None,
        "PREV_PATH_INST_ID": None,
        "CHAN_NAME": None,
        "CHAN_INST_ID": None,
        "SLOT": "CHASSIS PORTS",
        "PORT_NAME": "03",
        "PORT_INST_ID": "114706095",
        "PORT_ACCESS_ID": "ACCESS-1-1-1-3",
        "CONNECTOR_TYPE": "RJ-45",
        "FQDN": "LARETXNR1ZW.CML.CHTRSE.COM",
        "MODEL": "FSP 150-GE114PRO-C",
        "VENDOR": "ADVA",
        "TID": "LARETXNR1ZW",
        "LEGACY_EQUIP_SOURCE": None,
        "PURCHASING_GROUP": "ENTERPRISE",
        "IPV4_ADDRESS": "DHCP",
        "IPV6_ADDRESS": None,
        "C_VLAN": None,
        "CUST_S_VLAN": None,
        "S_VLAN": "2522",
        "VLAN_OPERATION": "PUSH",
        "PORT_ROLE": "UNI-EP",
        "INITIAL_PATH_NAME": "95.L1XX.004421..CHTR",
        "INITIAL_CIRCUIT_ID": "2421975",
        "LVL": "1",
    }
]

circuit_devices_double_cpe = [
    {
        "CIRC_PATH_INST_ID": "2421975",
        "PATH_NAME": "95.L1XX.004421..CHTR",
        "PATH_REV": "1",
        "PATH_CATEGORY": "ETHERNET",
        "PATH_A_SITE": "SNAQTXKY-TWC/COLO-LEVEL3-SYNERGY SAN ANTONIO (SNAQTXL3) (NBB)",
        "PATH_Z_SITE": "LARETXNR-CARRIER ENTERPRISE LLC//4102 AIRPARK DR",
        "A_CLLI": "SNAQTXKY",
        "Z_CLLI": "LARETXNR",
        "PATH_A_SITE_TYPE": "COLO-NETWORK",
        "PATH_Z_SITE_TYPE": "LOCAL",
        "TOPOLOGY": "Point-to-point",
        "PATH_STATUS": "Live",
        "CLASS_OF_SERVICE": "BRONZE REGIONAL",
        "SLM_ELIGIBILITY": "ELIGIBLE DESIGN",
        "EVC_ID": "426369",
        "SERVICE_TYPE": "CAR-E-ACCESS FIBER/FIBER EPL",
        "BANDWIDTH": "20 Mbps",
        "BW_SIZE": "20000000",
        "CUSTOMER_ID": "ACCT-21122235",
        "CUSTOMER_NAME": "LEVEL 3 NEW TWCC",
        "IPV4_GLUE_SUBNET": None,
        "IPV4_ASSIGNED_SUBNETS": None,
        "IPV4_ASSIGNED_GATEWAY": None,
        "IPV4_SERVICE_TYPE": None,
        "IPV6_GLUE_SUBNET": None,
        "IPV6_ASSIGNED_SUBNETS": None,
        "IPV6_SERVICE_TYPE": None,
        "CUSTOMER_TYPE": "CARRIER",
        "ORDER_REFERENCE": "1.",
        "PARENT_SEQUENCE": None,
        "PARENT_MEMBER_NBR": None,
        "SEQUENCE": "1",
        "MEMBER_NBR": None,
        "LEG_NAME": "1",
        "LEG_INST_ID": "2783107",
        "A_SITE_NAME": "SNAQTXKY-TWC/COLO-LEVEL3-SYNERGY SAN ANTONIO (SNAQTXL3) (NBB)",
        "Z_SITE_NAME": None,
        "ELEMENT_TYPE": "PORT",
        "ELEMENT_NAME": "SNAQTXKY2AW/C001.0102.001.005.16/NIU",
        "ELEMENT_REFERENCE": "857566",
        "ELEMENT_CATEGORY": "NIU",
        "ELEMENT_STATUS": "Live",
        "ELEMENT_BANDWIDTH": "20 Mbps",
        "NEXT_PATH_INST_ID": None,
        "PREV_PATH_INST_ID": None,
        "CHAN_NAME": None,
        "CHAN_INST_ID": None,
        "SLOT": "3/1",
        "PORT_NAME": "1-105",
        "PORT_INST_ID": "114706101",
        "PORT_ACCESS_ID": "3/1",
        "CONNECTOR_TYPE": "LC",
        "FQDN": "SNAQTXKY2AW.CHTRSE.COM",
        "MODEL": "ETX-220A",
        "VENDOR": "RAD",
        "TID": "SNAQTXKY2AW",
        "LEGACY_EQUIP_SOURCE": "L-TWC",
        "PURCHASING_GROUP": "ENTERPRISE",
        "IPV4_ADDRESS": "10.4.216.2/24",
        "IPV6_ADDRESS": None,
        "C_VLAN": None,
        "CUST_S_VLAN": "2522",
        "S_VLAN": "2522",
        "VLAN_OPERATION": None,
        "PORT_ROLE": "ENNI",
        "INITIAL_PATH_NAME": "95.L1XX.004421..CHTR",
        "INITIAL_CIRCUIT_ID": "2421975",
        "LVL": "1",
    },
    {
        "CIRC_PATH_INST_ID": "2421975",
        "PATH_NAME": "95.L1XX.004421..CHTR",
        "PATH_REV": "1",
        "PATH_CATEGORY": "ETHERNET",
        "PATH_A_SITE": "SNAQTXKY-TWC/COLO-LEVEL3-SYNERGY SAN ANTONIO (SNAQTXL3) (NBB)",
        "PATH_Z_SITE": "LARETXNR-CARRIER ENTERPRISE LLC//4102 AIRPARK DR",
        "A_CLLI": "SNAQTXKY",
        "Z_CLLI": "LARETXNR",
        "PATH_A_SITE_TYPE": "COLO-NETWORK",
        "PATH_Z_SITE_TYPE": "LOCAL",
        "TOPOLOGY": "Point-to-point",
        "PATH_STATUS": "Live",
        "CLASS_OF_SERVICE": "BRONZE REGIONAL",
        "SLM_ELIGIBILITY": "ELIGIBLE DESIGN",
        "EVC_ID": "426369",
        "SERVICE_TYPE": "CAR-E-ACCESS FIBER/FIBER EPL",
        "BANDWIDTH": "20 Mbps",
        "BW_SIZE": "20000000",
        "CUSTOMER_ID": "ACCT-21122235",
        "CUSTOMER_NAME": "LEVEL 3 NEW TWCC",
        "IPV4_GLUE_SUBNET": None,
        "IPV4_ASSIGNED_SUBNETS": None,
        "IPV4_ASSIGNED_GATEWAY": None,
        "IPV4_SERVICE_TYPE": None,
        "IPV6_GLUE_SUBNET": None,
        "IPV6_ASSIGNED_SUBNETS": None,
        "IPV6_SERVICE_TYPE": None,
        "CUSTOMER_TYPE": "CARRIER",
        "ORDER_REFERENCE": "6.",
        "PARENT_SEQUENCE": None,
        "PARENT_MEMBER_NBR": None,
        "SEQUENCE": "6",
        "MEMBER_NBR": None,
        "LEG_NAME": "1",
        "LEG_INST_ID": "2783107",
        "A_SITE_NAME": "LARETXNR-CARRIER ENTERPRISE LLC//4102 AIRPARK DR",
        "Z_SITE_NAME": None,
        "ELEMENT_TYPE": "PORT",
        "ELEMENT_NAME": "LARETXNR1ZW/999.9999.999.99/SWT",
        "ELEMENT_REFERENCE": "1732692",
        "ELEMENT_CATEGORY": "SWITCH",
        "ELEMENT_STATUS": "Live",
        "ELEMENT_BANDWIDTH": "10/100/1000 BASET",
        "NEXT_PATH_INST_ID": None,
        "PREV_PATH_INST_ID": None,
        "CHAN_NAME": None,
        "CHAN_INST_ID": None,
        "SLOT": "CHASSIS PORTS",
        "PORT_NAME": "03",
        "PORT_INST_ID": "114706095",
        "PORT_ACCESS_ID": "ACCESS-1-1-1-3",
        "CONNECTOR_TYPE": "RJ-45",
        "FQDN": "LARETXNR1ZW.CML.CHTRSE.COM",
        "MODEL": "FSP 150-GE114PRO-C",
        "VENDOR": "ADVA",
        "TID": "LARETXNR1ZW",
        "LEGACY_EQUIP_SOURCE": None,
        "PURCHASING_GROUP": "ENTERPRISE",
        "IPV4_ADDRESS": "DHCP",
        "IPV6_ADDRESS": None,
        "C_VLAN": None,
        "CUST_S_VLAN": None,
        "S_VLAN": "2522",
        "VLAN_OPERATION": "PUSH",
        "PORT_ROLE": "UNI-EP",
        "INITIAL_PATH_NAME": "95.L1XX.004421..CHTR",
        "INITIAL_CIRCUIT_ID": "2421975",
        "LVL": "1",
    },
    {
        "CIRC_PATH_INST_ID": "2421975",
        "PATH_NAME": "95.L1XX.004421..CHTR",
        "PATH_REV": "1",
        "PATH_CATEGORY": "ETHERNET",
        "PATH_A_SITE": "ABCDTXKY-TWC/COLO-LEVEL3-SYNERGY SAN ANTONIO (ABCDTXL3) (NBB)",
        "PATH_Z_SITE": "EFGHTXNR-CARRIER ENTERPRISE LLC//1000 UNICORNS WAY",
        "A_CLLI": "ABCDTXKY",
        "Z_CLLI": "EFGHTXNR",
        "PATH_A_SITE_TYPE": "COLO-NETWORK",
        "PATH_Z_SITE_TYPE": "LOCAL",
        "TOPOLOGY": "Point-to-point",
        "PATH_STATUS": "Live",
        "CLASS_OF_SERVICE": "BRONZE REGIONAL",
        "SLM_ELIGIBILITY": "ELIGIBLE DESIGN",
        "EVC_ID": "426369",
        "SERVICE_TYPE": "CAR-E-ACCESS FIBER/FIBER EPL",
        "BANDWIDTH": "20 Mbps",
        "BW_SIZE": "20000000",
        "CUSTOMER_ID": "ACCT-21122235",
        "CUSTOMER_NAME": "LEVEL 3 NEW TWCC",
        "IPV4_GLUE_SUBNET": None,
        "IPV4_ASSIGNED_SUBNETS": None,
        "IPV4_ASSIGNED_GATEWAY": None,
        "IPV4_SERVICE_TYPE": None,
        "IPV6_GLUE_SUBNET": None,
        "IPV6_ASSIGNED_SUBNETS": None,
        "IPV6_SERVICE_TYPE": None,
        "CUSTOMER_TYPE": "CARRIER",
        "ORDER_REFERENCE": "1.",
        "PARENT_SEQUENCE": None,
        "PARENT_MEMBER_NBR": None,
        "SEQUENCE": "1",
        "MEMBER_NBR": None,
        "LEG_NAME": "1",
        "LEG_INST_ID": "2783107",
        "A_SITE_NAME": "ABCDXKY-TWC/COLO-LEVEL3-SYNERGY SAN ANTONIO (ABCDTXL3) (NBB)",
        "Z_SITE_NAME": None,
        "ELEMENT_TYPE": "PORT",
        "ELEMENT_NAME": "ABCDTXKY2AW/C001.0102.001.005.16/NIU",
        "ELEMENT_REFERENCE": "857566",
        "ELEMENT_CATEGORY": "NIU",
        "ELEMENT_STATUS": "Live",
        "ELEMENT_BANDWIDTH": "20 Mbps",
        "NEXT_PATH_INST_ID": None,
        "PREV_PATH_INST_ID": None,
        "CHAN_NAME": None,
        "CHAN_INST_ID": None,
        "SLOT": "3/1",
        "PORT_NAME": "1-105",
        "PORT_INST_ID": "114706101",
        "PORT_ACCESS_ID": "3/1",
        "CONNECTOR_TYPE": "LC",
        "FQDN": "ABCDTXKY2AW.CHTRSE.COM",
        "MODEL": "ETX-220A",
        "VENDOR": "RAD",
        "TID": "ABCDXKY2AW",
        "LEGACY_EQUIP_SOURCE": "L-TWC",
        "PURCHASING_GROUP": "ENTERPRISE",
        "IPV4_ADDRESS": "10.4.216.2/24",
        "IPV6_ADDRESS": None,
        "C_VLAN": None,
        "CUST_S_VLAN": "2522",
        "S_VLAN": "2522",
        "VLAN_OPERATION": None,
        "PORT_ROLE": "ENNI",
        "INITIAL_PATH_NAME": "95.L1XX.004421..CHTR",
        "INITIAL_CIRCUIT_ID": "2421975",
        "LVL": "1",
    },
    {
        "CIRC_PATH_INST_ID": "2421975",
        "PATH_NAME": "95.L1XX.004421..CHTR",
        "PATH_REV": "1",
        "PATH_CATEGORY": "ETHERNET",
        "PATH_A_SITE": "ABCDTXKY-TWC/COLO-LEVEL3-SYNERGY SAN ANTONIO (ABCDTXL3) (NBB)",
        "PATH_Z_SITE": "LARETXNR-CARRIER ENTERPRISE LLC//4102 AIRPARK DR",
        "A_CLLI": "ABCDTXKY",
        "Z_CLLI": "EFGHTXNR",
        "PATH_A_SITE_TYPE": "COLO-NETWORK",
        "PATH_Z_SITE_TYPE": "LOCAL",
        "TOPOLOGY": "Point-to-point",
        "PATH_STATUS": "Live",
        "CLASS_OF_SERVICE": "BRONZE REGIONAL",
        "SLM_ELIGIBILITY": "ELIGIBLE DESIGN",
        "EVC_ID": "426369",
        "SERVICE_TYPE": "CAR-E-ACCESS FIBER/FIBER EPL",
        "BANDWIDTH": "20 Mbps",
        "BW_SIZE": "20000000",
        "CUSTOMER_ID": "ACCT-21122235",
        "CUSTOMER_NAME": "LEVEL 3 NEW TWCC",
        "IPV4_GLUE_SUBNET": None,
        "IPV4_ASSIGNED_SUBNETS": None,
        "IPV4_ASSIGNED_GATEWAY": None,
        "IPV4_SERVICE_TYPE": None,
        "IPV6_GLUE_SUBNET": None,
        "IPV6_ASSIGNED_SUBNETS": None,
        "IPV6_SERVICE_TYPE": None,
        "CUSTOMER_TYPE": "CARRIER",
        "ORDER_REFERENCE": "6.",
        "PARENT_SEQUENCE": None,
        "PARENT_MEMBER_NBR": None,
        "SEQUENCE": "6",
        "MEMBER_NBR": None,
        "LEG_NAME": "1",
        "LEG_INST_ID": "2783107",
        "A_SITE_NAME": "EGFHTXNR-CARRIER ENTERPRISE LLC//1000 UNICORNS WAY",
        "Z_SITE_NAME": None,
        "ELEMENT_TYPE": "PORT",
        "ELEMENT_NAME": "EFGHTXNR1ZW/999.9999.999.99/SWT",
        "ELEMENT_REFERENCE": "1732692",
        "ELEMENT_CATEGORY": "SWITCH",
        "ELEMENT_STATUS": "Live",
        "ELEMENT_BANDWIDTH": "10/100/1000 BASET",
        "NEXT_PATH_INST_ID": None,
        "PREV_PATH_INST_ID": None,
        "CHAN_NAME": None,
        "CHAN_INST_ID": None,
        "SLOT": "CHASSIS PORTS",
        "PORT_NAME": "03",
        "PORT_INST_ID": "114706095",
        "PORT_ACCESS_ID": "ACCESS-1-1-1-3",
        "CONNECTOR_TYPE": "RJ-45",
        "FQDN": "EGFHTXNR1ZW.CML.CHTRSE.COM",
        "MODEL": "FSP 150-GE114PRO-C",
        "VENDOR": "ADVA",
        "TID": "EGFHTXNR1ZW",
        "LEGACY_EQUIP_SOURCE": None,
        "PURCHASING_GROUP": "ENTERPRISE",
        "IPV4_ADDRESS": "DHCP",
        "IPV6_ADDRESS": None,
        "C_VLAN": None,
        "CUST_S_VLAN": None,
        "S_VLAN": "2522",
        "VLAN_OPERATION": "PUSH",
        "PORT_ROLE": "UNI-EP",
        "INITIAL_PATH_NAME": "95.L1XX.004421..CHTR",
        "INITIAL_CIRCUIT_ID": "2421975",
        "LVL": "1",
    },
]

granite_cpe_data_double_cpe = [
    {
        "CIRC_PATH_INST_ID": "2421975",
        "PATH_NAME": "95.L1XX.004421..CHTR",
        "PATH_REV": "1",
        "PATH_CATEGORY": "ETHERNET",
        "PATH_A_SITE": "SNAQTXKY-TWC/COLO-LEVEL3-SYNERGY SAN ANTONIO (SNAQTXL3) (NBB)",
        "PATH_Z_SITE": "LARETXNR-CARRIER ENTERPRISE LLC//4102 AIRPARK DR",
        "A_CLLI": "SNAQTXKY",
        "Z_CLLI": "LARETXNR",
        "PATH_A_SITE_TYPE": "COLO-NETWORK",
        "PATH_Z_SITE_TYPE": "LOCAL",
        "TOPOLOGY": "Point-to-point",
        "PATH_STATUS": "Live",
        "CLASS_OF_SERVICE": "BRONZE REGIONAL",
        "SLM_ELIGIBILITY": "ELIGIBLE DESIGN",
        "EVC_ID": "426369",
        "SERVICE_TYPE": "CAR-E-ACCESS FIBER/FIBER EPL",
        "BANDWIDTH": "20 Mbps",
        "BW_SIZE": "20000000",
        "CUSTOMER_ID": "ACCT-21122235",
        "CUSTOMER_NAME": "LEVEL 3 NEW TWCC",
        "IPV4_GLUE_SUBNET": None,
        "IPV4_ASSIGNED_SUBNETS": None,
        "IPV4_ASSIGNED_GATEWAY": None,
        "IPV4_SERVICE_TYPE": None,
        "IPV6_GLUE_SUBNET": None,
        "IPV6_ASSIGNED_SUBNETS": None,
        "IPV6_SERVICE_TYPE": None,
        "CUSTOMER_TYPE": "CARRIER",
        "ORDER_REFERENCE": "6.",
        "PARENT_SEQUENCE": None,
        "PARENT_MEMBER_NBR": None,
        "SEQUENCE": "6",
        "MEMBER_NBR": None,
        "LEG_NAME": "1",
        "LEG_INST_ID": "2783107",
        "A_SITE_NAME": "LARETXNR-CARRIER ENTERPRISE LLC//4102 AIRPARK DR",
        "Z_SITE_NAME": None,
        "ELEMENT_TYPE": "PORT",
        "ELEMENT_NAME": "LARETXNR1ZW/999.9999.999.99/SWT",
        "ELEMENT_REFERENCE": "1732692",
        "ELEMENT_CATEGORY": "SWITCH",
        "ELEMENT_STATUS": "Live",
        "ELEMENT_BANDWIDTH": "10/100/1000 BASET",
        "NEXT_PATH_INST_ID": None,
        "PREV_PATH_INST_ID": None,
        "CHAN_NAME": None,
        "CHAN_INST_ID": None,
        "SLOT": "CHASSIS PORTS",
        "PORT_NAME": "03",
        "PORT_INST_ID": "114706095",
        "PORT_ACCESS_ID": "ACCESS-1-1-1-3",
        "CONNECTOR_TYPE": "RJ-45",
        "FQDN": "LARETXNR1ZW.CML.CHTRSE.COM",
        "MODEL": "FSP 150-GE114PRO-C",
        "VENDOR": "ADVA",
        "TID": "LARETXNR1ZW",
        "LEGACY_EQUIP_SOURCE": None,
        "PURCHASING_GROUP": "ENTERPRISE",
        "IPV4_ADDRESS": "DHCP",
        "IPV6_ADDRESS": None,
        "C_VLAN": None,
        "CUST_S_VLAN": None,
        "S_VLAN": "2522",
        "VLAN_OPERATION": "PUSH",
        "PORT_ROLE": "UNI-EP",
        "INITIAL_PATH_NAME": "95.L1XX.004421..CHTR",
        "INITIAL_CIRCUIT_ID": "2421975",
        "LVL": "1",
    },
    {
        "CIRC_PATH_INST_ID": "2421975",
        "PATH_NAME": "95.L1XX.004421..CHTR",
        "PATH_REV": "1",
        "PATH_CATEGORY": "ETHERNET",
        "PATH_A_SITE": "ABCDTXKY-TWC/COLO-LEVEL3-SYNERGY SAN ANTONIO (ABCDTXL3) (NBB)",
        "PATH_Z_SITE": "LARETXNR-CARRIER ENTERPRISE LLC//4102 AIRPARK DR",
        "A_CLLI": "ABCDTXKY",
        "Z_CLLI": "EFGHTXNR",
        "PATH_A_SITE_TYPE": "COLO-NETWORK",
        "PATH_Z_SITE_TYPE": "LOCAL",
        "TOPOLOGY": "Point-to-point",
        "PATH_STATUS": "Live",
        "CLASS_OF_SERVICE": "BRONZE REGIONAL",
        "SLM_ELIGIBILITY": "ELIGIBLE DESIGN",
        "EVC_ID": "426369",
        "SERVICE_TYPE": "CAR-E-ACCESS FIBER/FIBER EPL",
        "BANDWIDTH": "20 Mbps",
        "BW_SIZE": "20000000",
        "CUSTOMER_ID": "ACCT-21122235",
        "CUSTOMER_NAME": "LEVEL 3 NEW TWCC",
        "IPV4_GLUE_SUBNET": None,
        "IPV4_ASSIGNED_SUBNETS": None,
        "IPV4_ASSIGNED_GATEWAY": None,
        "IPV4_SERVICE_TYPE": None,
        "IPV6_GLUE_SUBNET": None,
        "IPV6_ASSIGNED_SUBNETS": None,
        "IPV6_SERVICE_TYPE": None,
        "CUSTOMER_TYPE": "CARRIER",
        "ORDER_REFERENCE": "6.",
        "PARENT_SEQUENCE": None,
        "PARENT_MEMBER_NBR": None,
        "SEQUENCE": "6",
        "MEMBER_NBR": None,
        "LEG_NAME": "1",
        "LEG_INST_ID": "2783107",
        "A_SITE_NAME": "EGFHTXNR-CARRIER ENTERPRISE LLC//1000 UNICORNS WAY",
        "Z_SITE_NAME": None,
        "ELEMENT_TYPE": "PORT",
        "ELEMENT_NAME": "EFGHTXNR1ZW/999.9999.999.99/SWT",
        "ELEMENT_REFERENCE": "1732692",
        "ELEMENT_CATEGORY": "SWITCH",
        "ELEMENT_STATUS": "Live",
        "ELEMENT_BANDWIDTH": "10/100/1000 BASET",
        "NEXT_PATH_INST_ID": None,
        "PREV_PATH_INST_ID": None,
        "CHAN_NAME": None,
        "CHAN_INST_ID": None,
        "SLOT": "CHASSIS PORTS",
        "PORT_NAME": "03",
        "PORT_INST_ID": "114706095",
        "PORT_ACCESS_ID": "ACCESS-1-1-1-3",
        "CONNECTOR_TYPE": "RJ-45",
        "FQDN": "EGFHTXNR1ZW.CML.CHTRSE.COM",
        "MODEL": "FSP 150-GE114PRO-C",
        "VENDOR": "ADVA",
        "TID": "EGFHTXNR1ZW",
        "LEGACY_EQUIP_SOURCE": None,
        "PURCHASING_GROUP": "ENTERPRISE",
        "IPV4_ADDRESS": "DHCP",
        "IPV6_ADDRESS": None,
        "C_VLAN": None,
        "CUST_S_VLAN": None,
        "S_VLAN": "2522",
        "VLAN_OPERATION": "PUSH",
        "PORT_ROLE": "UNI-EP",
        "INITIAL_PATH_NAME": "95.L1XX.004421..CHTR",
        "INITIAL_CIRCUIT_ID": "2421975",
        "LVL": "1",
    },
]

device_ips_single_cpe = {"LARETXNR1ZW": "10.4.146.247"}

device_ips_double_cpe = {"LARETXNR1ZW": "10.4.146.247", "EGFHTXNR1ZW": "10.4.146.99"}

granite_info_fia_single_cpe = [
    {
        "CIRC_PATH_INST_ID": "2421975",
        "PATH_NAME": "95.L1XX.004421..CHTR",
        "PATH_REV": "1",
        "PATH_CATEGORY": "ETHERNET",
        "PATH_A_SITE": "SNAQTXKY-TWC/COLO-LEVEL3-SYNERGY SAN ANTONIO (SNAQTXL3) (NBB)",
        "PATH_Z_SITE": "LARETXNR-CARRIER ENTERPRISE LLC//4102 AIRPARK DR",
        "A_CLLI": "SNAQTXKY",
        "Z_CLLI": "LARETXNR",
        "PATH_A_SITE_TYPE": "COLO-NETWORK",
        "PATH_Z_SITE_TYPE": "LOCAL",
        "TOPOLOGY": "Point-to-point",
        "PATH_STATUS": "Live",
        "CLASS_OF_SERVICE": "BRONZE REGIONAL",
        "SLM_ELIGIBILITY": None,
        "EVC_ID": "426369",
        "SERVICE_TYPE": "FIA",
        "BANDWIDTH": "20 Mbps",
        "BW_SIZE": "20000000",
        "CUSTOMER_ID": "ACCT-21122235",
        "CUSTOMER_NAME": "LEVEL 3 NEW TWCC",
        "IPV4_GLUE_SUBNET": None,
        "IPV4_ASSIGNED_SUBNETS": None,
        "IPV4_ASSIGNED_GATEWAY": None,
        "IPV4_SERVICE_TYPE": None,
        "IPV6_GLUE_SUBNET": None,
        "IPV6_ASSIGNED_SUBNETS": None,
        "IPV6_SERVICE_TYPE": None,
        "CUSTOMER_TYPE": "CARRIER",
        "ORDER_REFERENCE": "6.",
        "PARENT_SEQUENCE": None,
        "PARENT_MEMBER_NBR": None,
        "SEQUENCE": "6",
        "MEMBER_NBR": None,
        "LEG_NAME": "1",
        "LEG_INST_ID": "2783107",
        "A_SITE_NAME": "LARETXNR-CARRIER ENTERPRISE LLC//4102 AIRPARK DR",
        "Z_SITE_NAME": None,
        "ELEMENT_TYPE": "PORT",
        "ELEMENT_NAME": "LARETXNR1ZW/999.9999.999.99/SWT",
        "ELEMENT_REFERENCE": "1732692",
        "ELEMENT_CATEGORY": "SWITCH",
        "ELEMENT_STATUS": "Live",
        "ELEMENT_BANDWIDTH": "10/100/1000 BASET",
        "NEXT_PATH_INST_ID": None,
        "PREV_PATH_INST_ID": None,
        "CHAN_NAME": None,
        "CHAN_INST_ID": None,
        "SLOT": "CHASSIS PORTS",
        "PORT_NAME": "03",
        "PORT_INST_ID": "114706095",
        "PORT_ACCESS_ID": "ACCESS-1-1-1-3",
        "CONNECTOR_TYPE": "RJ-45",
        "FQDN": "LARETXNR1ZW.CML.CHTRSE.COM",
        "MODEL": "FSP 150-GE114PRO-C",
        "VENDOR": "ADVA",
        "TID": "LARETXNR1ZW",
        "LEGACY_EQUIP_SOURCE": None,
        "PURCHASING_GROUP": "ENTERPRISE",
        "IPV4_ADDRESS": "DHCP",
        "IPV6_ADDRESS": None,
        "C_VLAN": None,
        "CUST_S_VLAN": None,
        "S_VLAN": "2522",
        "VLAN_OPERATION": "PUSH",
        "PORT_ROLE": "UNI-EP",
        "INITIAL_PATH_NAME": "95.L1XX.004421..CHTR",
        "INITIAL_CIRCUIT_ID": "2421975",
        "LVL": "1",
    }
]

granite_info_eline_single_cpe = [
    {
        "CIRC_PATH_INST_ID": "2421975",
        "PATH_NAME": "95.L1XX.004421..CHTR",
        "PATH_REV": "1",
        "PATH_CATEGORY": "ETHERNET",
        "PATH_A_SITE": "SNAQTXKY-TWC/COLO-LEVEL3-SYNERGY SAN ANTONIO (SNAQTXL3) (NBB)",
        "PATH_Z_SITE": "LARETXNR-CARRIER ENTERPRISE LLC//4102 AIRPARK DR",
        "A_CLLI": "SNAQTXKY",
        "Z_CLLI": "LARETXNR",
        "PATH_A_SITE_TYPE": "COLO-NETWORK",
        "PATH_Z_SITE_TYPE": "LOCAL",
        "TOPOLOGY": "Point-to-point",
        "PATH_STATUS": "Live",
        "CLASS_OF_SERVICE": "BRONZE REGIONAL",
        "SLM_ELIGIBILITY": "ELIGIBLE DESIGN",
        "EVC_ID": "426369",
        "SERVICE_TYPE": "CAR-E-ACCESS FIBER/FIBER EPL",
        "BANDWIDTH": "20 Mbps",
        "BW_SIZE": "20000000",
        "CUSTOMER_ID": "ACCT-21122235",
        "CUSTOMER_NAME": "LEVEL 3 NEW TWCC",
        "IPV4_GLUE_SUBNET": None,
        "IPV4_ASSIGNED_SUBNETS": None,
        "IPV4_ASSIGNED_GATEWAY": None,
        "IPV4_SERVICE_TYPE": None,
        "IPV6_GLUE_SUBNET": None,
        "IPV6_ASSIGNED_SUBNETS": None,
        "IPV6_SERVICE_TYPE": None,
        "CUSTOMER_TYPE": "CARRIER",
        "ORDER_REFERENCE": "6.",
        "PARENT_SEQUENCE": None,
        "PARENT_MEMBER_NBR": None,
        "SEQUENCE": "6",
        "MEMBER_NBR": None,
        "LEG_NAME": "1",
        "LEG_INST_ID": "2783107",
        "A_SITE_NAME": "LARETXNR-CARRIER ENTERPRISE LLC//4102 AIRPARK DR",
        "Z_SITE_NAME": None,
        "ELEMENT_TYPE": "PORT",
        "ELEMENT_NAME": "LARETXNR1ZW/999.9999.999.99/SWT",
        "ELEMENT_REFERENCE": "1732692",
        "ELEMENT_CATEGORY": "SWITCH",
        "ELEMENT_STATUS": "Live",
        "ELEMENT_BANDWIDTH": "10/100/1000 BASET",
        "NEXT_PATH_INST_ID": None,
        "PREV_PATH_INST_ID": None,
        "CHAN_NAME": None,
        "CHAN_INST_ID": None,
        "SLOT": "CHASSIS PORTS",
        "PORT_NAME": "03",
        "PORT_INST_ID": "114706095",
        "PORT_ACCESS_ID": "ACCESS-1-1-1-3",
        "CONNECTOR_TYPE": "RJ-45",
        "FQDN": "LARETXNR1ZW.CML.CHTRSE.COM",
        "MODEL": "FSP 150-GE114PRO-C",
        "VENDOR": "ADVA",
        "TID": "LARETXNR1ZW",
        "LEGACY_EQUIP_SOURCE": None,
        "PURCHASING_GROUP": "ENTERPRISE",
        "IPV4_ADDRESS": "DHCP",
        "IPV6_ADDRESS": None,
        "C_VLAN": None,
        "CUST_S_VLAN": None,
        "S_VLAN": "2522",
        "VLAN_OPERATION": "PUSH",
        "PORT_ROLE": "UNI-EP",
        "INITIAL_PATH_NAME": "95.L1XX.004421..CHTR",
        "INITIAL_CIRCUIT_ID": "2421975",
        "LVL": "1",
    }
]

post_base = {
    "label": "95.L1XX.004421..CHTR",
    "productId": "TEST PRODUCT ID",
    "resourceTypeId": "charter.resourceTypes.ServiceMapper",
    "properties": {"circuit_id": "95.L1XX.004421..CHTR", "remediation_flag": True, "device_properties": {}},
}

post_base_cpe_swap = {
    "label": "95.L1XX.004421..CHTR",
    "productId": "TEST PRODUCT ID",
    "resourceTypeId": "charter.resourceTypes.ServiceMapper",
    "properties": {
        "circuit_id": "95.L1XX.004421..CHTR",
        "remediation_flag": True,
        "device_properties": {},
        "cpe_swap": True,
        "cpe_swap_note": {
            "NYMTNY511ZW": {
                "designed": {"model": "ETX203AX/2SFP/2UTP2SFP", "vendor": "RAD"},
                "installed": {"model": "FSP 150-GE114PRO-C", "vendor": "ADVA"},
            }
        },
    },
}

fia_post_with_cpe_swap = {
    "label": "95.L1XX.004421..CHTR",
    "productId": "TEST PRODUCT ID",
    "resourceTypeId": "charter.resourceTypes.ServiceMapper",
    "properties": {
        "circuit_id": "95.L1XX.004421..CHTR",
        "remediation_flag": True,
        "device_properties": {"LARETXNR1ZW": {"Management IP": "10.4.146.247", "MediaType": "RJ-45"}},
        "cpe_swap": True,
        "cpe_swap_note": {
            "NYMTNY511ZW": {
                "designed": {"model": "ETX203AX/2SFP/2UTP2SFP", "vendor": "RAD"},
                "installed": {"model": "FSP 150-GE114PRO-C", "vendor": "ADVA"},
            }
        },
    },
}

fia_post_with_ip = {
    "label": "95.L1XX.004421..CHTR",
    "productId": "TEST PRODUCT ID",
    "resourceTypeId": "charter.resourceTypes.ServiceMapper",
    "properties": {
        "circuit_id": "95.L1XX.004421..CHTR",
        "remediation_flag": True,
        "device_properties": {"LARETXNR1ZW": {"Management IP": "10.4.146.247", "MediaType": "RJ-45"}},
    },
}

fia_post_no_ip = {
    "label": "95.L1XX.004421..CHTR",
    "productId": "TEST PRODUCT ID",
    "resourceTypeId": "charter.resourceTypes.ServiceMapper",
    "properties": {
        "circuit_id": "95.L1XX.004421..CHTR",
        "remediation_flag": True,
        "device_properties": {"LARETXNR1ZW": {"MediaType": "RJ-45"}},
    },
}

eline_post_single_cpe_with_ip = {
    "label": "95.L1XX.004421..CHTR",
    "productId": "TEST PRODUCT ID",
    "resourceTypeId": "charter.resourceTypes.ServiceMapper",
    "properties": {
        "circuit_id": "95.L1XX.004421..CHTR",
        "remediation_flag": True,
        "device_properties": {"LARETXNR1ZW": {"Management IP": "10.4.146.247", "MediaType": "RJ-45"}},
        "slm_eligible": True,
    },
}

eline_post_single_cpe_no_ip = {
    "label": "95.L1XX.004421..CHTR",
    "productId": "TEST PRODUCT ID",
    "resourceTypeId": "charter.resourceTypes.ServiceMapper",
    "properties": {
        "circuit_id": "95.L1XX.004421..CHTR",
        "remediation_flag": True,
        "device_properties": {"LARETXNR1ZW": {"MediaType": "RJ-45"}},
        "slm_eligible": True,
    },
}

eline_post_double_cpe_double_ip = {
    "label": "95.L1XX.004421..CHTR",
    "productId": "TEST PRODUCT ID",
    "resourceTypeId": "charter.resourceTypes.ServiceMapper",
    "properties": {
        "circuit_id": "95.L1XX.004421..CHTR",
        "remediation_flag": True,
        "device_properties": {
            "LARETXNR1ZW": {"Management IP": "10.4.146.247", "MediaType": "RJ-45"},
            "EGFHTXNR1ZW": {"Management IP": "10.4.146.99", "MediaType": "RJ-45"},
        },
        "slm_eligible": True,
    },
}

eline_post_double_cpe_single_ip = {
    "label": "95.L1XX.004421..CHTR",
    "productId": "TEST PRODUCT ID",
    "resourceTypeId": "charter.resourceTypes.ServiceMapper",
    "properties": {
        "circuit_id": "95.L1XX.004421..CHTR",
        "remediation_flag": True,
        "device_properties": {
            "LARETXNR1ZW": {"Management IP": "10.4.146.247", "MediaType": "RJ-45"},
            "EGFHTXNR1ZW": {"MediaType": "RJ-45"},
        },
        "slm_eligible": True,
    },
}

eline_post_double_cpe_no_ip = {
    "label": "95.L1XX.004421..CHTR",
    "productId": "TEST PRODUCT ID",
    "resourceTypeId": "charter.resourceTypes.ServiceMapper",
    "properties": {
        "circuit_id": "95.L1XX.004421..CHTR",
        "remediation_flag": True,
        "device_properties": {"LARETXNR1ZW": {"MediaType": "RJ-45"}, "EGFHTXNR1ZW": {"MediaType": "RJ-45"}},
        "slm_eligible": True,
    },
}

voice_request_body = {
    "bw": False,
    "ip": False,
    "dsc": False,
    "product_name": "PRI Trunk (Fiber)",
    "cid": "21.IPXN.001628..CHTR",
    "device_mapping": True,
    "order_type": "Change",
    "remediation_flag": True,
    "duplex_setting": "FULL",
}

voice_passing_path = [
    {
        "aSideSiteName": "SNAVTXUU-TWC/HUB 50-LA COLONIA (SNANTX5000)",
        "bandwidth": "10 Mbps",
        "category": "PRI TRUNKS",
        "gia_UDA": "NO",
        "off_NetFacility_UDA": "NO",
        "orderingCustomer": "ACCT-01692364",
        "orderNumber": "ENG-02984010",
        "pathId": "21.IPXN.001628..CHTR",
        "pathInService": "2023-01-12 12:00:00.0",
        "pathRev": "1",
        "product_Service_UDA": "CUS-VOICE-PRI",
        "servicePriority": "NO",
        "status": "Live",
        "topology": "P",
        "tspChildPresent_UDA": "NO",
        "zSideCustomer": "ACCT-01692364",
        "zSideSiteName": "SNAPTXET-SAFELITE 1869//11105 LANDMARK 35 DR",
        "instanceProtocol": "4",
        "managedService": "NO",
        "ofEnnis": "0",
        "pathInstanceId": "2251769",
        "serviceMedia": "FIBER",
        "slmEligibility": "INELIGIBLE SERVICE",
        "startChanNbr": "1",
        "vcClass": "TYPE 1",
        "virtualChans": "D",
    }
]

voice_two_path = [
    {
        "aSideSiteName": "SNAVTXUU-TWC/HUB 50-LA COLONIA (SNANTX5000)",
        "bandwidth": "10 Mbps",
        "category": "PRI TRUNKS",
        "gia_UDA": "NO",
        "off_NetFacility_UDA": "NO",
        "orderingCustomer": "ACCT-01692364",
        "orderNumber": "ENG-02984010",
        "pathId": "21.IPXN.001628..CHTR",
        "pathInService": "2023-01-12 12:00:00.0",
        "pathRev": "1",
        "product_Service_UDA": "CUS-VOICE-PRI",
        "servicePriority": "NO",
        "status": "Live",
        "topology": "P",
        "tspChildPresent_UDA": "NO",
        "zSideCustomer": "ACCT-01692364",
        "zSideSiteName": "SNAPTXET-SAFELITE 1869//11105 LANDMARK 35 DR",
        "instanceProtocol": "4",
        "managedService": "NO",
        "ofEnnis": "0",
        "pathInstanceId": "2251769",
        "serviceMedia": "FIBER",
        "slmEligibility": "INELIGIBLE SERVICE",
        "startChanNbr": "1",
        "vcClass": "TYPE 1",
        "virtualChans": "D",
    },
    {
        "aSideSiteName": "SNAVTXUU-TWC/HUB 50-LA COLONIA (SNANTX5000)",
        "bandwidth": "10 Mbps",
        "category": "PRI TRUNKS",
        "gia_UDA": "NO",
        "off_NetFacility_UDA": "NO",
        "orderingCustomer": "ACCT-01692364",
        "orderNumber": "ENG-02984010",
        "pathId": "21.IPXN.001628..CHTR",
        "pathInService": "2023-01-12 12:00:00.0",
        "pathRev": "1",
        "product_Service_UDA": "CUS-VOICE-PRI",
        "servicePriority": "NO",
        "status": "Designed",
        "topology": "P",
        "tspChildPresent_UDA": "NO",
        "zSideCustomer": "ACCT-01692364",
        "zSideSiteName": "SNAPTXET-SAFELITE 1869//11105 LANDMARK 35 DR",
        "instanceProtocol": "4",
        "managedService": "NO",
        "ofEnnis": "0",
        "pathInstanceId": "2251769",
        "serviceMedia": "FIBER",
        "slmEligibility": "INELIGIBLE SERVICE",
        "startChanNbr": "1",
        "vcClass": "TYPE 1",
        "virtualChans": "D",
    },
]

voice_designed_path = [
    {
        "aSideSiteName": "SNAVTXUU-TWC/HUB 50-LA COLONIA (SNANTX5000)",
        "bandwidth": "10 Mbps",
        "category": "PRI TRUNKS",
        "gia_UDA": "NO",
        "off_NetFacility_UDA": "NO",
        "orderingCustomer": "ACCT-01692364",
        "orderNumber": "ENG-02984010",
        "pathId": "21.IPXN.001628..CHTR",
        "pathInService": "2023-01-12 12:00:00.0",
        "pathRev": "1",
        "product_Service_UDA": "CUS-VOICE-PRI",
        "servicePriority": "NO",
        "status": "Designed",
        "topology": "P",
        "tspChildPresent_UDA": "NO",
        "zSideCustomer": "ACCT-01692364",
        "zSideSiteName": "SNAPTXET-SAFELITE 1869//11105 LANDMARK 35 DR",
        "instanceProtocol": "4",
        "managedService": "NO",
        "ofEnnis": "0",
        "pathInstanceId": "2251769",
        "serviceMedia": "FIBER",
        "slmEligibility": "INELIGIBLE SERVICE",
        "startChanNbr": "1",
        "vcClass": "TYPE 1",
        "virtualChans": "D",
    }
]

empty_request_body = {
    "bw": False,
    "ip": False,
    "dsc": False,
    "product_name": "Fiber Internet Access",
    "cid": "51.L1XX.010026..TWCC",
    "device_mapping": True,
    "order_type": "Change",
    "remediation_flag": True,
    "duplex_setting": "FULL",
}

empty_path_elements = {
    "instId": "0",
    "retCode": 2,
    "httpCode": 200,
    "retString": "No records found with the specified search criteria...",
}
