#!/bin/sh

#don't overwrite image tag if it's been set, if it's set and empty we don't change that
if [ ! -z ${IMAGE_TAG+x} ]; then
  export IMAGE_TAG
elif [[ $CI_COMMIT_REF_NAME == $MAIN_BRANCH ]]; then
  export IMAGE_TAG=$PROJECT_VERSION_TAG
elif  [[ $CI_COMMIT_REF_NAME == release/* ]]; then
  export IMAGE_TAG=${CI_COMMIT_REF_NAME#release/}.$PROJECT_VERSION_TAG
elif [ ! -z ${CI_MERGE_REQUEST_ID+x} ]; then
  export IMAGE_TAG=$PROJECT_VERSION_TAG.MR.$CI_MERGE_REQUEST_IID.$CI_COMMIT_SHORT_SHA
else
  export IMAGE_TAG=${CI_COMMIT_REF_NAME//\//-}.$PROJECT_VERSION_TAG
fi
echo Image tag= $IMAGE_TAG
