class MockResponseJson:
    def __init__(self, response_data, status_code=200):
        self.status_code = status_code
        self.response_data = response_data

    def json(self):
        return self.response_data


def sense_v3_logic_success_response(*args, **kwargs):
    status_code = 201
    return MockResponseJson(v3_sense_success_response_lan_payload, status_code)


def mock_uda_update_good_resp(*args, **kwargs):
    status_code = 200
    return MockResponseJson(uda_update_good, status_code)


v3_sense_success_response_lan_payload = {
    "ipv4_service_type": "LAN",
    "ipv4_glue_subnet": "",
    "ipv4_assigned_subnets": "10.10.10.10/29",
    "ipv4_assigned_gateway": "10.10.10.11/29",
    "ipv6_service_type": "ROUTED",
    "ipv6_glue_subnet": "2600:5C01:3E76:D993:8B02:38CB:3BBE:6C18/127",
    "ipv6_assigned_subnet": "2600:5C01:593::/48",
}


v3_sense_success_response_routed_payload = {
    "ipv4_service_type": "ROUTED",
    "ipv4_glue_subnet": "10.10.10.10/30",
    "ipv4_assigned_subnets": "20.20.20.20/29",
    "ipv4_assigned_gateway": "10.10.10.11/30",
    "ipv6_service_type": "ROUTED",
    "ipv6_glue_subnet": "2600:5C01:3E76:D993:8B02:38CB:3BBE:6C18/127",
    "ipv6_assigned_subnet": "2600:5C01:593::/48",
}


# Mock payload matching baseline MVP support case (net new, TWC, LAN)
v3_intake_payload_valid_mvp = {
    "service": "net_new",
    "legacy_company": "TWC",
    "cid": "51.L1XX.816475..CHTR",
    "ipv4_type": "LAN",
    "block_size": "/29=5",
    "acct": "123456",
    "epr": "ENG-0001234",
}

intake_payload_valid_nn_twc_lan = {
    "service": "'net_new' or 'quick_connect'",
    "legacy_company": "'TWC', 'BHN', or 'CHTR'",
    "cid": "51.L1XX.816475..CHTR",
    "ipv4_type": "'LAN' or 'ROUTED'",
    "block_size": "/29=5",
    "acct": "123456",
    "epr": "ENG-0001234",
}

l1_good = [
    {
        "CIRC_PATH_INST_ID": "1842455",
        "PATH_NAME": "THIS_IS_A_PATH_NAME",
        "PATH_REV": "1",
        "A_CLLI": "AUSDTXIR",
        "Z_CLLI": "AUSXTXZR",
        "CUSTOMER_ID": "SEEFA TESTING",
        "LEG_NAME": "1",
        "LEG_INST_ID": "2088416",
        "PATH_A_SITE": "MATT",
        "PATH_Z_SITE": "JON",
        "ELEMENT_NAME": "CHTRSE.CEN.TEXAS.MPLS",
        "LVL": "1",
    },
    {"ELEMENT_NAME": "51001.GE1.AUSDTXIR8CW.AUSXTXZR5ZW"},
]

l1_bad_first_element = [
    {
        "CIRC_PATH_INST_ID": "1842455",
        "PATH_NAME": "THIS_IS_A_PATH_NAME",
        "CUSTOMER_NAME": "AMAZON RETAIL",
        "PATH_REV": "1",
        "A_CLLI": "AUSDTXIR",
        "Z_CLLI": "AUSXTXZR",
        "CUSTOMER_ID": "SEEFA TESTING",
        "LEG_NAME": "1",
        "LEG_INST_ID": "2088416",
        "A_SITE_NAME": "MATT",
        "Z_SITE_NAME": "JON",
        "ELEMENT_NAME": "BAD_ELEMENT_NAME",
        "LVL": "1",
    },
    {"ELEMENT_NAME": "51001.GE1.AUSDTXIR8CW.AUSXTXZR5ZW"},
]

l1_bad_mx = [
    {
        "CIRC_PATH_INST_ID": "1842455",
        "PATH_NAME": "THIS_IS_A_PATH_NAME",
        "CUSTOMER_NAME": "AMAZON RETAIL",
        "PATH_REV": "1",
        "A_CLLI": "AUSDTXIR",
        "Z_CLLI": "AUSXTXZR",
        "CUSTOMER_ID": "SEEFA TESTING",
        "LEG_NAME": "1",
        "LEG_INST_ID": "2088416",
        "A_SITE_NAME": "MATT",
        "Z_SITE_NAME": "JON",
        "ELEMENT_NAME": "CHTRSE.CEN.TEXAS.MPLS",
        "LVL": "1",
    },
    {"ELEMENT_NAME": "51001.GE1.AUSDTXIR8CAW.AUSXTXZR5ZW", "LVL": "1"},
]

l1_bad_hub_element_name = [
    {
        "ELEMENT_NAME": "CHTRSE.CEN.WEST.MPLS",
        "LEG_NAME": "1",
        "CUSTOMER_ID": "AMAZON RETAIL",
        "CUSTOMER_NAME": "AMAZON RETAIL",
        "LVL": "1",
    },
    {
        "ELEMENT_NAME": None,
        "LEG_NAME": "1",
        "CUSTOMER_ID": "AMAZON RETAIL",
        "CUSTOMER_NAME": "AMAZON RETAIL",
        "LVL": "1",
    },
]

l1_bad_a_site_name = [
    {"ELEMENT_NAME": "CHTRSE.CEN.WEST.MPLS", "LEG_NAME": "1", "CUSTOMER_ID": "AMAZON RETAIL"},
    {"ELEMENT_NAME": "CW", "LEG_NAME": "1", "CUSTOMER_ID": "AMAZON RETAIL", "A_SITE_NAME": None},
]
l1_bad_z_site_name = [
    {"ELEMENT_NAME": "CHTRSE.CEN.WEST.MPLS", "LEG_NAME": "1", "CUSTOMER_ID": "AMAZON RETAIL"},
    {"ELEMENT_NAME": "CW", "LEG_NAME": "1", "CUSTOMER_ID": "AMAZON RETAIL", "A_SITE_NAME": "Name"},
    {"ELEMENT_NAME": "ZW", "A_SITE_NAME": None, "Z_SITE_NAME": None},
]

l1_a_site_values_for_z_site_info = [
    {
        "CIRC_PATH_INST_ID": "1972067",
        "PATH_NAME": "81.L4XX.000347..CHTR",
        "PATH_REV": "1",
        "PATH_CATEGORY": "ETHERNET",
        "PATH_A_SITE": "SHOKCA64-AMAZON.COM WHOLE FOODS MARKET//12905 RIVERSIDE DR",
        "PATH_Z_SITE": "SHOKCA64-AMAZON.COM WHOLE FOODS MARKET//12905 RIVERSIDE DR",
        "CUSTOMER_NAME": "AMAZON RETAIL",
        "CUSTOMER_ID": "AMAZON RETAIL",
        "A_CLLI": "SHOKCA64",
        "Z_CLLI": "SHOKCA64",
        "PATH_A_SITE_TYPE": "LOCAL",
        "PATH_Z_SITE_TYPE": "LOCAL",
        "TOPOLOGY": "Point-to-point",
        "PATH_STATUS": "Planned",
        "CLASS_OF_SERVICE": None,
        "EVC_ID": None,
        "SERVICE_TYPE": "COM-DIA",
        "BANDWIDTH": "500 Mbps",
        "BW_SIZE": "500000000",
        "ASSIGNED_IP_SUBNET_MASK": "/30",
        "ASSIGNED_GLUE_SUBNET": "2600:5C00:3800::1012/127",
        "ASSIGNED_IP_SUBNET": "108.178.140.232",
        "ASSIGNED_IP_RANGE": "108.178.140.234 THRU 108.178.140.235",
        "GATEWAY_IP_ADDRESS": "108.178.140.233",
        "ASSIGNED_IPV6_GLUE_SUBNET": "2600:5C00:3800::1012/127",
        "ASSIGNED_IPV6_SUBNET": "2600:5C00:474B::/48",
        "ASSIGNED_IPV6_RANGE": "2600:5C00:474B:: THRU 2600:5C00:474B:FFFF:FFFF:FFFF:FFFF:FFFF",
        "IPV4_SERVICE_TYPE": "LAN",
        "IPV6_SERVICE_TYPE": "ROUTED",
        "CUSTOMER_TYPE": "ENTERPRISE",
        "SEQUENCE": "1",
        "MEMBER_NBR": None,
        "LEG_NAME": "1",
        "LEG_INST_ID": "2235554",
        "A_SITE_NAME": None,
        "Z_SITE_NAME": None,
        "A_SITE_TYPE": None,
        "Z_SITE_TYPE": None,
        "ELEMENT_TYPE": "NETWORK",
        "ELEMENT_NAME": "CHTRSE.CEN.WEST.MPLS",
        "ELEMENT_REFERENCE": "602608",
        "ELEMENT_CATEGORY": "SE MPLS CORE",
        "ELEMENT_STATUS": "Live",
        "ELEMENT_BANDWIDTH": "MPLS_CORE",
        "LEGACY_EQUIP_SOURCE": "",
        "CHAN_NAME": "7661",
        "CHAN_INST_ID": "9216201",
        "SLOT": None,
        "PORT_NAME": None,
        "PORT_INST_ID": None,
        "PORT_ACCESS_ID": None,
        "CONNECTOR_TYPE": None,
        "FQDN": None,
        "MODEL": None,
        "VENDOR": None,
        "TID": None,
        "MANAGEMENT_IP": None,
        "C_VLAN": None,
        "S_VLAN": None,
        "VLAN_OPERATION": None,
        "INITIAL_PATH_NAME": "81.L4XX.000347..CHTR",
        "INITIAL_CIRCUIT_ID": "1972067",
        "LVL": "1",
    },
    {
        "CIRC_PATH_INST_ID": "1972067",
        "PATH_NAME": "81.L4XX.000347..CHTR",
        "PATH_REV": "1",
        "PATH_CATEGORY": "ETHERNET",
        "PATH_A_SITE": "",
        "PATH_Z_SITE": "SHOKCA64-AMAZON.COM WHOLE FOODS MARKET//12905 RIVERSIDE DR",
        "A_CLLI": "SHOKCA64",
        "Z_CLLI": "SHOKCA64",
        "PATH_A_SITE_TYPE": "LOCAL",
        "PATH_Z_SITE_TYPE": "LOCAL",
        "TOPOLOGY": "Point-to-point",
        "PATH_STATUS": "Planned",
        "CLASS_OF_SERVICE": None,
        "EVC_ID": None,
        "SERVICE_TYPE": "COM-DIA",
        "BANDWIDTH": "500 Mbps",
        "BW_SIZE": "500000000",
        "ASSIGNED_IP_SUBNET_MASK": "/30",
        "ASSIGNED_GLUE_SUBNET": "2600:5C00:3800::1012/127",
        "ASSIGNED_IP_SUBNET": "108.178.140.232",
        "ASSIGNED_IP_RANGE": "108.178.140.234 THRU 108.178.140.235",
        "GATEWAY_IP_ADDRESS": "108.178.140.233",
        "ASSIGNED_IPV6_GLUE_SUBNET": "2600:5C00:3800::1012/127",
        "ASSIGNED_IPV6_SUBNET": "2600:5C00:474B::/48",
        "ASSIGNED_IPV6_RANGE": "2600:5C00:474B:: THRU 2600:5C00:474B:FFFF:FFFF:FFFF:FFFF:FFFF",
        "IPV4_SERVICE_TYPE": "LAN",
        "IPV6_SERVICE_TYPE": "ROUTED",
        "CUSTOMER_TYPE": "ENTERPRISE",
        "SEQUENCE": "2",
        "MEMBER_NBR": None,
        "LEG_NAME": "1",
        "LEG_INST_ID": "2235554",
        "A_SITE_NAME": "it should grab this item for a_site_name",
        "Z_SITE_NAME": "VNNZCA24-TWC/HUB VNNY3-VAN-NUYS-3-VNNY3 (VNNYCA3)",
        "A_SITE_TYPE": "HUB",
        "Z_SITE_TYPE": "HUB",
        "ELEMENT_TYPE": "PATH",
        "ELEMENT_NAME": "81001.GE40L.VNNZCA242CW.VNNZCA241QW",
        "ELEMENT_REFERENCE": "1320916",
        "ELEMENT_CATEGORY": "ETHERNET TRANSPORT",
        "ELEMENT_STATUS": "Live",
        "ELEMENT_BANDWIDTH": "AGGREGATE",
        "CHAN_NAME": "VLAN1400",
        "CHAN_INST_ID": "9216200",
        "LEGACY_EQUIP_SOURCE": "",
        "SLOT": None,
        "PORT_NAME": None,
        "PORT_INST_ID": None,
        "PORT_ACCESS_ID": None,
        "CONNECTOR_TYPE": None,
        "FQDN": None,
        "MODEL": None,
        "VENDOR": None,
        "TID": None,
        "MANAGEMENT_IP": None,
        "C_VLAN": None,
        "S_VLAN": None,
        "VLAN_OPERATION": None,
        "INITIAL_PATH_NAME": "81.L4XX.000347..CHTR",
        "INITIAL_CIRCUIT_ID": "1972067",
        "LVL": "1",
    },
    {
        "CIRC_PATH_INST_ID": "1972067",
        "PATH_NAME": "81.L4XX.000347..CHTR",
        "PATH_REV": "1",
        "PATH_CATEGORY": "ETHERNET",
        "PATH_A_SITE": "it should grab this item for leg_a_site_name",
        "PATH_Z_SITE": "SHOKCA64-AMAZON.COM WHOLE FOODS MARKET//12905 RIVERSIDE DR",
        "A_CLLI": "SHOKCA64",
        "Z_CLLI": "SHOKCA64",
        "PATH_A_SITE_TYPE": "LOCAL",
        "PATH_Z_SITE_TYPE": "LOCAL",
        "TOPOLOGY": "Point-to-point",
        "PATH_STATUS": "Planned",
        "CLASS_OF_SERVICE": None,
        "EVC_ID": None,
        "SERVICE_TYPE": "COM-DIA",
        "BANDWIDTH": "500 Mbps",
        "BW_SIZE": "500000000",
        "CUSTOMER_ID": "AMAZON RETAIL",
        "CUSTOMER_NAME": "AMAZON RETAIL",
        "ASSIGNED_IP_SUBNET_MASK": "/30",
        "ASSIGNED_GLUE_SUBNET": "2600:5C00:3800::1012/127",
        "ASSIGNED_IP_SUBNET": "108.178.140.232",
        "ASSIGNED_IP_RANGE": "108.178.140.234 THRU 108.178.140.235",
        "GATEWAY_IP_ADDRESS": "108.178.140.233",
        "ASSIGNED_IPV6_GLUE_SUBNET": "2600:5C00:3800::1012/127",
        "ASSIGNED_IPV6_SUBNET": "2600:5C00:474B::/48",
        "ASSIGNED_IPV6_RANGE": "2600:5C00:474B:: THRU 2600:5C00:474B:FFFF:FFFF:FFFF:FFFF:FFFF",
        "IPV4_SERVICE_TYPE": "LAN",
        "IPV6_SERVICE_TYPE": "ROUTED",
        "CUSTOMER_TYPE": "ENTERPRISE",
        "SEQUENCE": "2",
        "MEMBER_NBR": None,
        "LEG_NAME": "1",
        "LEG_INST_ID": "2235554",
        "A_SITE_NAME": "it should grab this item for a_site_name",
        "Z_SITE_NAME": "VNNZCA24-TWC/HUB VNNY3-VAN-NUYS-3-VNNY3 (VNNYCA3)",
        "A_SITE_TYPE": "HUB",
        "Z_SITE_TYPE": "HUB",
        "ELEMENT_TYPE": "PATH",
        "ELEMENT_NAME": "81001.GE40L.VNNZCA242CW.VNNZCA241QW",
        "ELEMENT_REFERENCE": "1320916",
        "ELEMENT_CATEGORY": "ETHERNET TRANSPORT",
        "ELEMENT_STATUS": "Live",
        "ELEMENT_BANDWIDTH": "AGGREGATE",
        "LEGACY_EQUIP_SOURCE": "TWC",
        "CHAN_NAME": "VLAN1400",
        "CHAN_INST_ID": "9216200",
        "SLOT": None,
        "PORT_NAME": None,
        "PORT_INST_ID": None,
        "PORT_ACCESS_ID": None,
        "CONNECTOR_TYPE": None,
        "FQDN": None,
        "MODEL": None,
        "VENDOR": None,
        "TID": "VNNZCA242CW",
        "MANAGEMENT_IP": None,
        "C_VLAN": None,
        "S_VLAN": None,
        "VLAN_OPERATION": None,
        "INITIAL_PATH_NAME": "81.L4XX.000347..CHTR",
        "INITIAL_CIRCUIT_ID": "1972067",
        "LVL": "2",
    },
    {
        "CIRC_PATH_INST_ID": "1972067",
        "PATH_NAME": "81.L4XX.000347..CHTR",
        "PATH_REV": "1",
        "PATH_CATEGORY": "ETHERNET",
        "PATH_A_SITE": "SHOKCA64-AMAZON.COM WHOLE FOODS MARKET//12905 RIVERSIDE DR",
        "PATH_Z_SITE": "SHOKCA64-AMAZON.COM WHOLE FOODS MARKET//12905 RIVERSIDE DR",
        "A_CLLI": "SHOKCA64",
        "Z_CLLI": "SHOKCA64",
        "PATH_A_SITE_TYPE": "LOCAL",
        "PATH_Z_SITE_TYPE": "LOCAL",
        "TOPOLOGY": "Point-to-point",
        "PATH_STATUS": "Planned",
        "CLASS_OF_SERVICE": None,
        "EVC_ID": None,
        "SERVICE_TYPE": "COM-DIA",
        "BANDWIDTH": "500 Mbps",
        "BW_SIZE": "500000000",
        "CUSTOMER_ID": "AMAZON RETAIL",
        "ASSIGNED_IP_SUBNET_MASK": "/30",
        "ASSIGNED_GLUE_SUBNET": "2600:5C00:3800::1012/127",
        "ASSIGNED_IP_SUBNET": "108.178.140.232",
        "ASSIGNED_IP_RANGE": "108.178.140.234 THRU 108.178.140.235",
        "GATEWAY_IP_ADDRESS": "108.178.140.233",
        "ASSIGNED_IPV6_GLUE_SUBNET": "2600:5C00:3800::1012/127",
        "ASSIGNED_IPV6_SUBNET": "2600:5C00:474B::/48",
        "ASSIGNED_IPV6_RANGE": "2600:5C00:474B:: THRU 2600:5C00:474B:FFFF:FFFF:FFFF:FFFF:FFFF",
        "IPV4_SERVICE_TYPE": "LAN",
        "IPV6_SERVICE_TYPE": "ROUTED",
        "CUSTOMER_TYPE": "ENTERPRISE",
        "SEQUENCE": "3",
        "MEMBER_NBR": None,
        "LEG_NAME": "1",
        "LEG_INST_ID": "2235554",
        "A_SITE_NAME": "VNNZCA24-TWC/HUB VNNY3-VAN-NUYS-3-VNNY3 (VNNYCA3)",
        "Z_SITE_NAME": "SHOKCA64-AMAZON.COM WHOLE FOODS MARKET//12905 RIVERSIDE DR",
        "A_SITE_TYPE": "HUB",
        "Z_SITE_TYPE": "LOCAL",
        "ELEMENT_TYPE": "PATH",
        "ELEMENT_NAME": "81001.GE10.VNNZCA241QW.SHOKCA642ZW",
        "ELEMENT_REFERENCE": "1974949",
        "ELEMENT_CATEGORY": "ETHERNET TRANSPORT",
        "ELEMENT_STATUS": "Planned",
        "ELEMENT_BANDWIDTH": "10 Gbps",
        "CHAN_NAME": "VLAN1400",
        "LEGACY_EQUIP_SOURCE": "",
        "CHAN_INST_ID": "9216169",
        "SLOT": None,
        "PORT_NAME": None,
        "PORT_INST_ID": None,
        "PORT_ACCESS_ID": None,
        "CONNECTOR_TYPE": None,
        "FQDN": None,
        "MODEL": None,
        "VENDOR": None,
        "TID": None,
        "MANAGEMENT_IP": None,
        "C_VLAN": None,
        "S_VLAN": None,
        "VLAN_OPERATION": None,
        "INITIAL_PATH_NAME": "81.L4XX.000347..CHTR",
        "INITIAL_CIRCUIT_ID": "1972067",
        "LVL": "1",
    },
    {
        "CIRC_PATH_INST_ID": "1972067",
        "PATH_NAME": "81.L4XX.000347..CHTR",
        "PATH_REV": "1",
        "PATH_CATEGORY": "ETHERNET",
        "PATH_A_SITE": "it should grab this item for leg_z_site_name",
        "PATH_Z_SITE": "blah",
        "A_CLLI": "SHOKCA64",
        "Z_CLLI": "SHOKCA64",
        "PATH_A_SITE_TYPE": "LOCAL",
        "PATH_Z_SITE_TYPE": "LOCAL",
        "TOPOLOGY": "Point-to-point",
        "PATH_STATUS": "Planned",
        "CLASS_OF_SERVICE": None,
        "EVC_ID": None,
        "SERVICE_TYPE": "COM-DIA",
        "BANDWIDTH": "500 Mbps",
        "BW_SIZE": "500000000",
        "CUSTOMER_ID": "AMAZON RETAIL",
        "ASSIGNED_IP_SUBNET_MASK": "/30",
        "ASSIGNED_GLUE_SUBNET": "2600:5C00:3800::1012/127",
        "ASSIGNED_IP_SUBNET": "108.178.140.232",
        "ASSIGNED_IP_RANGE": "108.178.140.234 THRU 108.178.140.235",
        "GATEWAY_IP_ADDRESS": "108.178.140.233",
        "ASSIGNED_IPV6_GLUE_SUBNET": "2600:5C00:3800::1012/127",
        "ASSIGNED_IPV6_SUBNET": "2600:5C00:474B::/48",
        "ASSIGNED_IPV6_RANGE": "2600:5C00:474B:: THRU 2600:5C00:474B:FFFF:FFFF:FFFF:FFFF:FFFF",
        "IPV4_SERVICE_TYPE": "LAN",
        "IPV6_SERVICE_TYPE": "ROUTED",
        "CUSTOMER_TYPE": "ENTERPRISE",
        "SEQUENCE": "4",
        "MEMBER_NBR": None,
        "LEG_NAME": "1",
        "LEG_INST_ID": "2235554",
        "A_SITE_NAME": "it should grab this item for z_site_name",
        "Z_SITE_NAME": None,
        "A_SITE_TYPE": "LOCAL",
        "Z_SITE_TYPE": None,
        "ELEMENT_TYPE": "PORT",
        "ELEMENT_NAME": "SHOKCA642ZW/999.9999.999.99/NIU",
        "ELEMENT_REFERENCE": "1438519",
        "ELEMENT_CATEGORY": "NIU",
        "LEGACY_EQUIP_SOURCE": "",
        "ELEMENT_STATUS": "Planned",
        "ELEMENT_BANDWIDTH": "10/100/1000 BASET",
        "CHAN_NAME": None,
        "CHAN_INST_ID": None,
        "SLOT": "CHASSIS",
        "PORT_NAME": "0/11",
        "PORT_INST_ID": "110178310",
        "PORT_ACCESS_ID": "ETH PORT 0/11",
        "CONNECTOR_TYPE": "RJ-45",
        "FQDN": "SHOKCA642ZW.CML.CHTRSE.COM",
        "MODEL": "ETX-2I-10G/4SFPP/4SFP4UTP",
        "VENDOR": "RAD",
        "TID": "SHOKCA642ZW",
        "MANAGEMENT_IP": "DHCP",
        "C_VLAN": None,
        "S_VLAN": None,
        "VLAN_OPERATION": "PUSH",
        "INITIAL_PATH_NAME": "81.L4XX.000347..CHTR",
        "INITIAL_CIRCUIT_ID": "1972067",
        "LVL": "1",
    },
]

l1_z_site_values_for_z_site_info = [
    {
        "CIRC_PATH_INST_ID": "1972067",
        "PATH_NAME": "81.L4XX.000347..CHTR",
        "PATH_REV": "1",
        "PATH_CATEGORY": "ETHERNET",
        "PATH_A_SITE": "SHOKCA64-AMAZON.COM WHOLE FOODS MARKET//12905 RIVERSIDE DR",
        "PATH_Z_SITE": "SHOKCA64-AMAZON.COM WHOLE FOODS MARKET//12905 RIVERSIDE DR",
        "A_CLLI": "SHOKCA64",
        "Z_CLLI": "SHOKCA64",
        "PATH_A_SITE_TYPE": "LOCAL",
        "PATH_Z_SITE_TYPE": "LOCAL",
        "TOPOLOGY": "Point-to-point",
        "PATH_STATUS": "Planned",
        "CLASS_OF_SERVICE": None,
        "EVC_ID": None,
        "SERVICE_TYPE": "COM-DIA",
        "BANDWIDTH": "500 Mbps",
        "BW_SIZE": "500000000",
        "CUSTOMER_ID": "AMAZON RETAIL",
        "CUSTOMER_NAME": "AMAZON RETAIL",
        "ASSIGNED_IP_SUBNET_MASK": "/30",
        "ASSIGNED_GLUE_SUBNET": "2600:5C00:3800::1012/127",
        "ASSIGNED_IP_SUBNET": "108.178.140.232",
        "ASSIGNED_IP_RANGE": "108.178.140.234 THRU 108.178.140.235",
        "GATEWAY_IP_ADDRESS": "108.178.140.233",
        "ASSIGNED_IPV6_GLUE_SUBNET": "2600:5C00:3800::1012/127",
        "ASSIGNED_IPV6_SUBNET": "2600:5C00:474B::/48",
        "ASSIGNED_IPV6_RANGE": "2600:5C00:474B:: THRU 2600:5C00:474B:FFFF:FFFF:FFFF:FFFF:FFFF",
        "IPV4_SERVICE_TYPE": "LAN",
        "IPV6_SERVICE_TYPE": "ROUTED",
        "CUSTOMER_TYPE": "ENTERPRISE",
        "SEQUENCE": "1",
        "MEMBER_NBR": None,
        "LEG_NAME": "1",
        "LEG_INST_ID": "2235554",
        "A_SITE_NAME": None,
        "Z_SITE_NAME": None,
        "A_SITE_TYPE": None,
        "Z_SITE_TYPE": None,
        "ELEMENT_TYPE": "NETWORK",
        "ELEMENT_NAME": "CHTRSE.CEN.WEST.MPLS",
        "ELEMENT_REFERENCE": "602608",
        "ELEMENT_CATEGORY": "SE MPLS CORE",
        "ELEMENT_STATUS": "Live",
        "LEGACY_EQUIP_SOURCE": "",
        "ELEMENT_BANDWIDTH": "MPLS_CORE",
        "CHAN_NAME": "7661",
        "CHAN_INST_ID": "9216201",
        "SLOT": None,
        "PORT_NAME": None,
        "PORT_INST_ID": None,
        "PORT_ACCESS_ID": None,
        "CONNECTOR_TYPE": None,
        "FQDN": None,
        "MODEL": None,
        "VENDOR": None,
        "TID": None,
        "MANAGEMENT_IP": None,
        "C_VLAN": None,
        "S_VLAN": None,
        "VLAN_OPERATION": None,
        "INITIAL_PATH_NAME": "81.L4XX.000347..CHTR",
        "INITIAL_CIRCUIT_ID": "1972067",
        "LVL": "1",
    },
    {
        "CIRC_PATH_INST_ID": "1972067",
        "PATH_NAME": "81.L4XX.000347..CHTR",
        "PATH_REV": "1",
        "PATH_CATEGORY": "ETHERNET",
        "PATH_A_SITE": "it should grab this item for leg_a_site_name",
        "PATH_Z_SITE": "SHOKCA64-AMAZON.COM WHOLE FOODS MARKET//12905 RIVERSIDE DR",
        "A_CLLI": "SHOKCA64",
        "Z_CLLI": "SHOKCA64",
        "PATH_A_SITE_TYPE": "LOCAL",
        "PATH_Z_SITE_TYPE": "LOCAL",
        "TOPOLOGY": "Point-to-point",
        "PATH_STATUS": "Planned",
        "CLASS_OF_SERVICE": None,
        "EVC_ID": None,
        "SERVICE_TYPE": "COM-DIA",
        "BANDWIDTH": "500 Mbps",
        "BW_SIZE": "500000000",
        "CUSTOMER_ID": "AMAZON RETAIL",
        "CUSTOMER_NAME": "AMAZON RETAIL",
        "ASSIGNED_IP_SUBNET_MASK": "/30",
        "ASSIGNED_GLUE_SUBNET": "2600:5C00:3800::1012/127",
        "ASSIGNED_IP_SUBNET": "108.178.140.232",
        "ASSIGNED_IP_RANGE": "108.178.140.234 THRU 108.178.140.235",
        "GATEWAY_IP_ADDRESS": "108.178.140.233",
        "ASSIGNED_IPV6_GLUE_SUBNET": "2600:5C00:3800::1012/127",
        "ASSIGNED_IPV6_SUBNET": "2600:5C00:474B::/48",
        "ASSIGNED_IPV6_RANGE": "2600:5C00:474B:: THRU 2600:5C00:474B:FFFF:FFFF:FFFF:FFFF:FFFF",
        "IPV4_SERVICE_TYPE": "LAN",
        "IPV6_SERVICE_TYPE": "ROUTED",
        "CUSTOMER_TYPE": "ENTERPRISE",
        "SEQUENCE": "2",
        "MEMBER_NBR": None,
        "LEG_NAME": "1",
        "LEG_INST_ID": "2235554",
        "A_SITE_NAME": "it should grab this item for a_site_name",
        "Z_SITE_NAME": "VNNZCA24-TWC/HUB VNNY3-VAN-NUYS-3-VNNY3 (VNNYCA3)",
        "A_SITE_TYPE": "HUB",
        "Z_SITE_TYPE": "HUB",
        "ELEMENT_TYPE": "PATH",
        "ELEMENT_NAME": "81001.GE40L.VNNZCA242CW.VNNZCA241QW",
        "ELEMENT_REFERENCE": "1320916",
        "ELEMENT_CATEGORY": "ETHERNET TRANSPORT",
        "ELEMENT_STATUS": "Live",
        "ELEMENT_BANDWIDTH": "AGGREGATE",
        "LEGACY_EQUIP_SOURCE": "",
        "CHAN_NAME": "VLAN1400",
        "CHAN_INST_ID": "9216200",
        "SLOT": None,
        "PORT_NAME": None,
        "PORT_INST_ID": None,
        "PORT_ACCESS_ID": None,
        "CONNECTOR_TYPE": None,
        "FQDN": None,
        "MODEL": None,
        "VENDOR": None,
        "TID": None,
        "MANAGEMENT_IP": None,
        "C_VLAN": None,
        "S_VLAN": None,
        "VLAN_OPERATION": None,
        "INITIAL_PATH_NAME": "81.L4XX.000347..CHTR",
        "INITIAL_CIRCUIT_ID": "1972067",
        "LVL": "1",
    },
    {
        "CIRC_PATH_INST_ID": "1972067",
        "PATH_NAME": "81.L4XX.000347..CHTR",
        "PATH_REV": "1",
        "PATH_CATEGORY": "ETHERNET",
        "PATH_A_SITE": "it should grab this item for leg_a_site_name",
        "PATH_Z_SITE": "SHOKCA64-AMAZON.COM WHOLE FOODS MARKET//12905 RIVERSIDE DR",
        "A_CLLI": "SHOKCA64",
        "Z_CLLI": "SHOKCA64",
        "PATH_A_SITE_TYPE": "LOCAL",
        "PATH_Z_SITE_TYPE": "LOCAL",
        "TOPOLOGY": "Point-to-point",
        "PATH_STATUS": "Planned",
        "CLASS_OF_SERVICE": None,
        "EVC_ID": None,
        "SERVICE_TYPE": "COM-DIA",
        "BANDWIDTH": "500 Mbps",
        "BW_SIZE": "500000000",
        "CUSTOMER_ID": "AMAZON RETAIL",
        "CUSTOMER_NAME": "AMAZON RETAIL",
        "ASSIGNED_IP_SUBNET_MASK": "/30",
        "ASSIGNED_GLUE_SUBNET": "2600:5C00:3800::1012/127",
        "ASSIGNED_IP_SUBNET": "108.178.140.232",
        "ASSIGNED_IP_RANGE": "108.178.140.234 THRU 108.178.140.235",
        "GATEWAY_IP_ADDRESS": "108.178.140.233",
        "ASSIGNED_IPV6_GLUE_SUBNET": "2600:5C00:3800::1012/127",
        "ASSIGNED_IPV6_SUBNET": "2600:5C00:474B::/48",
        "ASSIGNED_IPV6_RANGE": "2600:5C00:474B:: THRU 2600:5C00:474B:FFFF:FFFF:FFFF:FFFF:FFFF",
        "IPV4_SERVICE_TYPE": "LAN",
        "IPV6_SERVICE_TYPE": "ROUTED",
        "CUSTOMER_TYPE": "ENTERPRISE",
        "SEQUENCE": "2",
        "MEMBER_NBR": None,
        "LEG_NAME": "1",
        "LEG_INST_ID": "2235554",
        "A_SITE_NAME": "it should grab this item for a_site_name",
        "Z_SITE_NAME": "VNNZCA24-TWC/HUB VNNY3-VAN-NUYS-3-VNNY3 (VNNYCA3)",
        "A_SITE_TYPE": "HUB",
        "Z_SITE_TYPE": "HUB",
        "ELEMENT_TYPE": "PATH",
        "ELEMENT_NAME": "81001.GE40L.VNNZCA242CW.VNNZCA241QW",
        "ELEMENT_REFERENCE": "1320916",
        "ELEMENT_CATEGORY": "ETHERNET TRANSPORT",
        "ELEMENT_STATUS": "Live",
        "ELEMENT_BANDWIDTH": "AGGREGATE",
        "LEGACY_EQUIP_SOURCE": "TWC",
        "CHAN_NAME": "VLAN1400",
        "CHAN_INST_ID": "9216200",
        "SLOT": None,
        "PORT_NAME": None,
        "PORT_INST_ID": None,
        "PORT_ACCESS_ID": None,
        "CONNECTOR_TYPE": None,
        "FQDN": None,
        "MODEL": None,
        "VENDOR": None,
        "TID": "VNNZCA242CW",
        "MANAGEMENT_IP": None,
        "C_VLAN": None,
        "S_VLAN": None,
        "VLAN_OPERATION": None,
        "INITIAL_PATH_NAME": "81.L4XX.000347..CHTR",
        "INITIAL_CIRCUIT_ID": "1972067",
        "LVL": "2",
    },
    {
        "CIRC_PATH_INST_ID": "1972067",
        "PATH_NAME": "81.L4XX.000347..CHTR",
        "PATH_REV": "1",
        "PATH_CATEGORY": "ETHERNET",
        "PATH_A_SITE": "SHOKCA64-AMAZON.COM WHOLE FOODS MARKET//12905 RIVERSIDE DR",
        "PATH_Z_SITE": "it should grab this item for leg_z_site_name",
        "A_CLLI": "SHOKCA64",
        "Z_CLLI": "SHOKCA64",
        "PATH_A_SITE_TYPE": "LOCAL",
        "PATH_Z_SITE_TYPE": "LOCAL",
        "TOPOLOGY": "Point-to-point",
        "PATH_STATUS": "Planned",
        "CLASS_OF_SERVICE": None,
        "EVC_ID": None,
        "SERVICE_TYPE": "COM-DIA",
        "BANDWIDTH": "500 Mbps",
        "BW_SIZE": "500000000",
        "CUSTOMER_ID": "AMAZON RETAIL",
        "ASSIGNED_IP_SUBNET_MASK": "/30",
        "ASSIGNED_GLUE_SUBNET": "2600:5C00:3800::1012/127",
        "ASSIGNED_IP_SUBNET": "108.178.140.232",
        "ASSIGNED_IP_RANGE": "108.178.140.234 THRU 108.178.140.235",
        "GATEWAY_IP_ADDRESS": "108.178.140.233",
        "ASSIGNED_IPV6_GLUE_SUBNET": "2600:5C00:3800::1012/127",
        "ASSIGNED_IPV6_SUBNET": "2600:5C00:474B::/48",
        "ASSIGNED_IPV6_RANGE": "2600:5C00:474B:: THRU 2600:5C00:474B:FFFF:FFFF:FFFF:FFFF:FFFF",
        "IPV4_SERVICE_TYPE": "LAN",
        "IPV6_SERVICE_TYPE": "ROUTED",
        "CUSTOMER_TYPE": "ENTERPRISE",
        "SEQUENCE": "3",
        "MEMBER_NBR": None,
        "LEG_NAME": "1",
        "LEG_INST_ID": "2235554",
        "A_SITE_NAME": None,
        "Z_SITE_NAME": "it should grab this item for z_site_name",
        "A_SITE_TYPE": "HUB",
        "Z_SITE_TYPE": "LOCAL",
        "ELEMENT_TYPE": "PATH",
        "ELEMENT_NAME": "81001.GE10.VNNZCA241QW.SHOKCA642ZW",
        "ELEMENT_REFERENCE": "1974949",
        "ELEMENT_CATEGORY": "ETHERNET TRANSPORT",
        "LEGACY_EQUIP_SOURCE": "",
        "ELEMENT_STATUS": "Planned",
        "ELEMENT_BANDWIDTH": "10 Gbps",
        "CHAN_NAME": "VLAN1400",
        "CHAN_INST_ID": "9216169",
        "SLOT": None,
        "PORT_NAME": None,
        "PORT_INST_ID": None,
        "PORT_ACCESS_ID": None,
        "CONNECTOR_TYPE": None,
        "FQDN": None,
        "MODEL": None,
        "VENDOR": None,
        "TID": None,
        "MANAGEMENT_IP": None,
        "C_VLAN": None,
        "S_VLAN": None,
        "VLAN_OPERATION": None,
        "INITIAL_PATH_NAME": "81.L4XX.000347..CHTR",
        "INITIAL_CIRCUIT_ID": "1972067",
        "LVL": "1",
    },
    {
        "CIRC_PATH_INST_ID": "1972067",
        "PATH_NAME": "81.L4XX.000347..CHTR",
        "PATH_REV": "1",
        "PATH_CATEGORY": "ETHERNET",
        "PATH_A_SITE": "it should grab this item for leg_z_site_name",
        "PATH_Z_SITE": "blah",
        "A_CLLI": "SHOKCA64",
        "Z_CLLI": "SHOKCA64",
        "PATH_A_SITE_TYPE": "LOCAL",
        "PATH_Z_SITE_TYPE": "LOCAL",
        "TOPOLOGY": "Point-to-point",
        "PATH_STATUS": "Planned",
        "CLASS_OF_SERVICE": None,
        "EVC_ID": None,
        "SERVICE_TYPE": "COM-DIA",
        "BANDWIDTH": "500 Mbps",
        "BW_SIZE": "500000000",
        "CUSTOMER_ID": "AMAZON RETAIL",
        "ASSIGNED_IP_SUBNET_MASK": "/30",
        "ASSIGNED_GLUE_SUBNET": "2600:5C00:3800::1012/127",
        "ASSIGNED_IP_SUBNET": "108.178.140.232",
        "ASSIGNED_IP_RANGE": "108.178.140.234 THRU 108.178.140.235",
        "GATEWAY_IP_ADDRESS": "108.178.140.233",
        "ASSIGNED_IPV6_GLUE_SUBNET": "2600:5C00:3800::1012/127",
        "ASSIGNED_IPV6_SUBNET": "2600:5C00:474B::/48",
        "ASSIGNED_IPV6_RANGE": "2600:5C00:474B:: THRU 2600:5C00:474B:FFFF:FFFF:FFFF:FFFF:FFFF",
        "IPV4_SERVICE_TYPE": "LAN",
        "IPV6_SERVICE_TYPE": "ROUTED",
        "CUSTOMER_TYPE": "ENTERPRISE",
        "SEQUENCE": "4",
        "MEMBER_NBR": None,
        "LEG_NAME": "1",
        "LEG_INST_ID": "2235554",
        "A_SITE_NAME": None,
        "Z_SITE_NAME": None,
        "A_SITE_TYPE": "LOCAL",
        "Z_SITE_TYPE": None,
        "ELEMENT_TYPE": "PORT",
        "ELEMENT_NAME": "SHOKCA642ZW/999.9999.999.99/NIU",
        "LEGACY_EQUIP_SOURCE": "",
        "ELEMENT_REFERENCE": "1438519",
        "ELEMENT_CATEGORY": "NIU",
        "ELEMENT_STATUS": "Planned",
        "ELEMENT_BANDWIDTH": "10/100/1000 BASET",
        "CHAN_NAME": None,
        "CHAN_INST_ID": None,
        "SLOT": "CHASSIS",
        "PORT_NAME": "0/11",
        "PORT_INST_ID": "110178310",
        "PORT_ACCESS_ID": "ETH PORT 0/11",
        "CONNECTOR_TYPE": "RJ-45",
        "FQDN": "SHOKCA642ZW.CML.CHTRSE.COM",
        "MODEL": "ETX-2I-10G/4SFPP/4SFP4UTP",
        "VENDOR": "RAD",
        "TID": "SHOKCA642ZW",
        "MANAGEMENT_IP": "DHCP",
        "C_VLAN": None,
        "S_VLAN": None,
        "VLAN_OPERATION": "PUSH",
        "INITIAL_PATH_NAME": "81.L4XX.000347..CHTR",
        "INITIAL_CIRCUIT_ID": "1972067",
        "LVL": "1",
    },
]

l1_a_and_z_site_values_for_z_site_info = [
    {
        "CIRC_PATH_INST_ID": "1972067",
        "PATH_NAME": "81.L4XX.000347..CHTR",
        "PATH_REV": "1",
        "PATH_CATEGORY": "ETHERNET",
        "PATH_A_SITE": "SHOKCA64-AMAZON.COM WHOLE FOODS MARKET//12905 RIVERSIDE DR",
        "PATH_Z_SITE": "SHOKCA64-AMAZON.COM WHOLE FOODS MARKET//12905 RIVERSIDE DR",
        "CUSTOMER_NAME": "AMAZON RETAIL",
        "CUSTOMER_ID": "AMAZON RETAIL",
        "A_CLLI": "SHOKCA64",
        "Z_CLLI": "SHOKCA64",
        "PATH_A_SITE_TYPE": "LOCAL",
        "PATH_Z_SITE_TYPE": "LOCAL",
        "TOPOLOGY": "Point-to-point",
        "PATH_STATUS": "Planned",
        "CLASS_OF_SERVICE": None,
        "EVC_ID": None,
        "SERVICE_TYPE": "COM-DIA",
        "BANDWIDTH": "500 Mbps",
        "BW_SIZE": "500000000",
        "ASSIGNED_IP_SUBNET_MASK": "/30",
        "ASSIGNED_GLUE_SUBNET": "2600:5C00:3800::1012/127",
        "ASSIGNED_IP_SUBNET": "108.178.140.232",
        "ASSIGNED_IP_RANGE": "108.178.140.234 THRU 108.178.140.235",
        "GATEWAY_IP_ADDRESS": "108.178.140.233",
        "ASSIGNED_IPV6_GLUE_SUBNET": "2600:5C00:3800::1012/127",
        "ASSIGNED_IPV6_SUBNET": "2600:5C00:474B::/48",
        "ASSIGNED_IPV6_RANGE": "2600:5C00:474B:: THRU 2600:5C00:474B:FFFF:FFFF:FFFF:FFFF:FFFF",
        "IPV4_SERVICE_TYPE": "LAN",
        "IPV6_SERVICE_TYPE": "ROUTED",
        "CUSTOMER_TYPE": "ENTERPRISE",
        "SEQUENCE": "1",
        "MEMBER_NBR": None,
        "LEG_NAME": "1",
        "LEG_INST_ID": "2235554",
        "A_SITE_NAME": None,
        "Z_SITE_NAME": None,
        "A_SITE_TYPE": None,
        "Z_SITE_TYPE": None,
        "ELEMENT_TYPE": "NETWORK",
        "ELEMENT_NAME": "CHTRSE.CEN.WEST.MPLS",
        "ELEMENT_REFERENCE": "602608",
        "ELEMENT_CATEGORY": "SE MPLS CORE",
        "LEGACY_EQUIP_SOURCE": "TWC",
        "ELEMENT_STATUS": "Live",
        "ELEMENT_BANDWIDTH": "MPLS_CORE",
        "CHAN_NAME": "7661",
        "CHAN_INST_ID": "9216201",
        "SLOT": None,
        "PORT_NAME": None,
        "PORT_INST_ID": None,
        "PORT_ACCESS_ID": None,
        "CONNECTOR_TYPE": None,
        "FQDN": None,
        "MODEL": None,
        "VENDOR": None,
        "TID": None,
        "MANAGEMENT_IP": None,
        "C_VLAN": None,
        "S_VLAN": None,
        "VLAN_OPERATION": None,
        "INITIAL_PATH_NAME": "81.L4XX.000347..CHTR",
        "INITIAL_CIRCUIT_ID": "1972067",
        "LVL": "1",
    },
    {
        "CIRC_PATH_INST_ID": "1972067",
        "PATH_NAME": "81.L4XX.000347..CHTR",
        "PATH_REV": "1",
        "PATH_CATEGORY": "ETHERNET",
        "PATH_A_SITE": "it should grab this item for leg_a_site_name",
        "PATH_Z_SITE": "SHOKCA64-AMAZON.COM WHOLE FOODS MARKET//12905 RIVERSIDE DR",
        "A_CLLI": "SHOKCA64",
        "Z_CLLI": "SHOKCA64",
        "PATH_A_SITE_TYPE": "LOCAL",
        "PATH_Z_SITE_TYPE": "LOCAL",
        "TOPOLOGY": "Point-to-point",
        "PATH_STATUS": "Planned",
        "CLASS_OF_SERVICE": None,
        "EVC_ID": None,
        "SERVICE_TYPE": "COM-DIA",
        "BANDWIDTH": "500 Mbps",
        "BW_SIZE": "500000000",
        "CUSTOMER_ID": "AMAZON RETAIL",
        "ASSIGNED_IP_SUBNET_MASK": "/30",
        "ASSIGNED_GLUE_SUBNET": "2600:5C00:3800::1012/127",
        "ASSIGNED_IP_SUBNET": "108.178.140.232",
        "ASSIGNED_IP_RANGE": "108.178.140.234 THRU 108.178.140.235",
        "GATEWAY_IP_ADDRESS": "108.178.140.233",
        "ASSIGNED_IPV6_GLUE_SUBNET": "2600:5C00:3800::1012/127",
        "ASSIGNED_IPV6_SUBNET": "2600:5C00:474B::/48",
        "ASSIGNED_IPV6_RANGE": "2600:5C00:474B:: THRU 2600:5C00:474B:FFFF:FFFF:FFFF:FFFF:FFFF",
        "IPV4_SERVICE_TYPE": "LAN",
        "IPV6_SERVICE_TYPE": "ROUTED",
        "CUSTOMER_TYPE": "ENTERPRISE",
        "SEQUENCE": "2",
        "MEMBER_NBR": None,
        "LEG_NAME": "1",
        "LEG_INST_ID": "2235554",
        "A_SITE_NAME": "it should grab this item for a_site_name",
        "Z_SITE_NAME": "VNNZCA24-TWC/HUB VNNY3-VAN-NUYS-3-VNNY3 (VNNYCA3)",
        "A_SITE_TYPE": "HUB",
        "Z_SITE_TYPE": "HUB",
        "ELEMENT_TYPE": "PATH",
        "ELEMENT_NAME": "81001.GE40L.VNNZCA242CW.VNNZCA241QW",
        "ELEMENT_REFERENCE": "1320916",
        "ELEMENT_CATEGORY": "ETHERNET TRANSPORT",
        "ELEMENT_STATUS": "Live",
        "ELEMENT_BANDWIDTH": "AGGREGATE",
        "LEGACY_EQUIP_SOURCE": "TWC",
        "CHAN_NAME": "VLAN1400",
        "CHAN_INST_ID": "9216200",
        "SLOT": None,
        "PORT_NAME": None,
        "PORT_INST_ID": None,
        "PORT_ACCESS_ID": None,
        "CONNECTOR_TYPE": None,
        "FQDN": None,
        "MODEL": None,
        "VENDOR": None,
        "TID": None,
        "MANAGEMENT_IP": None,
        "C_VLAN": None,
        "S_VLAN": None,
        "VLAN_OPERATION": None,
        "INITIAL_PATH_NAME": "81.L4XX.000347..CHTR",
        "INITIAL_CIRCUIT_ID": "1972067",
        "LVL": "1",
    },
    {
        "CIRC_PATH_INST_ID": "1972067",
        "PATH_NAME": "81.L4XX.000347..CHTR",
        "PATH_REV": "1",
        "PATH_CATEGORY": "ETHERNET",
        "PATH_A_SITE": "it should grab this item for leg_a_site_name",
        "PATH_Z_SITE": "SHOKCA64-AMAZON.COM WHOLE FOODS MARKET//12905 RIVERSIDE DR",
        "A_CLLI": "SHOKCA64",
        "Z_CLLI": "SHOKCA64",
        "PATH_A_SITE_TYPE": "LOCAL",
        "PATH_Z_SITE_TYPE": "LOCAL",
        "TOPOLOGY": "Point-to-point",
        "PATH_STATUS": "Planned",
        "CLASS_OF_SERVICE": None,
        "EVC_ID": None,
        "SERVICE_TYPE": "COM-DIA",
        "BANDWIDTH": "500 Mbps",
        "BW_SIZE": "500000000",
        "CUSTOMER_ID": "AMAZON RETAIL",
        "CUSTOMER_NAME": "AMAZON RETAIL",
        "ASSIGNED_IP_SUBNET_MASK": "/30",
        "ASSIGNED_GLUE_SUBNET": "2600:5C00:3800::1012/127",
        "ASSIGNED_IP_SUBNET": "108.178.140.232",
        "ASSIGNED_IP_RANGE": "108.178.140.234 THRU 108.178.140.235",
        "GATEWAY_IP_ADDRESS": "108.178.140.233",
        "ASSIGNED_IPV6_GLUE_SUBNET": "2600:5C00:3800::1012/127",
        "ASSIGNED_IPV6_SUBNET": "2600:5C00:474B::/48",
        "ASSIGNED_IPV6_RANGE": "2600:5C00:474B:: THRU 2600:5C00:474B:FFFF:FFFF:FFFF:FFFF:FFFF",
        "IPV4_SERVICE_TYPE": "LAN",
        "IPV6_SERVICE_TYPE": "ROUTED",
        "CUSTOMER_TYPE": "ENTERPRISE",
        "SEQUENCE": "2",
        "MEMBER_NBR": None,
        "LEG_NAME": "1",
        "LEG_INST_ID": "2235554",
        "A_SITE_NAME": "it should grab this item for a_site_name",
        "Z_SITE_NAME": "VNNZCA24-TWC/HUB VNNY3-VAN-NUYS-3-VNNY3 (VNNYCA3)",
        "A_SITE_TYPE": "HUB",
        "Z_SITE_TYPE": "HUB",
        "ELEMENT_TYPE": "PATH",
        "ELEMENT_NAME": "81001.GE40L.VNNZCA242CW.VNNZCA241QW",
        "ELEMENT_REFERENCE": "1320916",
        "ELEMENT_CATEGORY": "ETHERNET TRANSPORT",
        "ELEMENT_STATUS": "Live",
        "ELEMENT_BANDWIDTH": "AGGREGATE",
        "LEGACY_EQUIP_SOURCE": "TWC",
        "CHAN_NAME": "VLAN1400",
        "CHAN_INST_ID": "9216200",
        "SLOT": None,
        "PORT_NAME": None,
        "PORT_INST_ID": None,
        "PORT_ACCESS_ID": None,
        "CONNECTOR_TYPE": None,
        "FQDN": None,
        "MODEL": None,
        "VENDOR": None,
        "TID": "VNNZCA242CW",
        "MANAGEMENT_IP": None,
        "C_VLAN": None,
        "S_VLAN": None,
        "VLAN_OPERATION": None,
        "INITIAL_PATH_NAME": "81.L4XX.000347..CHTR",
        "INITIAL_CIRCUIT_ID": "1972067",
        "LVL": "2",
    },
    {
        "CIRC_PATH_INST_ID": "1972067",
        "PATH_NAME": "81.L4XX.000347..CHTR",
        "PATH_REV": "1",
        "PATH_CATEGORY": "ETHERNET",
        "PATH_A_SITE": "don't grab this item. don't do it to me.",
        "PATH_Z_SITE": "it should grab this item for leg_z_site_name",
        "A_CLLI": "SHOKCA64",
        "Z_CLLI": "SHOKCA64",
        "PATH_A_SITE_TYPE": "LOCAL",
        "PATH_Z_SITE_TYPE": "LOCAL",
        "TOPOLOGY": "Point-to-point",
        "PATH_STATUS": "Planned",
        "CLASS_OF_SERVICE": None,
        "EVC_ID": None,
        "SERVICE_TYPE": "COM-DIA",
        "BANDWIDTH": "500 Mbps",
        "BW_SIZE": "500000000",
        "CUSTOMER_ID": "AMAZON RETAIL",
        "ASSIGNED_IP_SUBNET_MASK": "/30",
        "ASSIGNED_GLUE_SUBNET": "2600:5C00:3800::1012/127",
        "ASSIGNED_IP_SUBNET": "108.178.140.232",
        "ASSIGNED_IP_RANGE": "108.178.140.234 THRU 108.178.140.235",
        "GATEWAY_IP_ADDRESS": "108.178.140.233",
        "ASSIGNED_IPV6_GLUE_SUBNET": "2600:5C00:3800::1012/127",
        "ASSIGNED_IPV6_SUBNET": "2600:5C00:474B::/48",
        "ASSIGNED_IPV6_RANGE": "2600:5C00:474B:: THRU 2600:5C00:474B:FFFF:FFFF:FFFF:FFFF:FFFF",
        "IPV4_SERVICE_TYPE": "LAN",
        "IPV6_SERVICE_TYPE": "ROUTED",
        "CUSTOMER_TYPE": "ENTERPRISE",
        "SEQUENCE": "3",
        "MEMBER_NBR": None,
        "LEG_NAME": "1",
        "LEG_INST_ID": "2235554",
        "A_SITE_NAME": "don't grab this item. don't do it to me.",
        "Z_SITE_NAME": "it should grab this item for z_site_name",
        "A_SITE_TYPE": "HUB",
        "Z_SITE_TYPE": "LOCAL",
        "ELEMENT_TYPE": "PATH",
        "ELEMENT_NAME": "81001.GE10.VNNZCA241QW.SHOKCA642ZW",
        "ELEMENT_REFERENCE": "1974949",
        "ELEMENT_CATEGORY": "ETHERNET TRANSPORT",
        "ELEMENT_STATUS": "Planned",
        "ELEMENT_BANDWIDTH": "10 Gbps",
        "CHAN_NAME": "VLAN1400",
        "CHAN_INST_ID": "9216169",
        "LEGACY_EQUIP_SOURCE": "TWC",
        "SLOT": None,
        "PORT_NAME": None,
        "PORT_INST_ID": None,
        "PORT_ACCESS_ID": None,
        "CONNECTOR_TYPE": None,
        "FQDN": None,
        "MODEL": None,
        "VENDOR": None,
        "TID": None,
        "MANAGEMENT_IP": None,
        "C_VLAN": None,
        "S_VLAN": None,
        "VLAN_OPERATION": None,
        "INITIAL_PATH_NAME": "81.L4XX.000347..CHTR",
        "INITIAL_CIRCUIT_ID": "1972067",
        "LVL": "1",
    },
    {
        "CIRC_PATH_INST_ID": "1972067",
        "PATH_NAME": "81.L4XX.000347..CHTR",
        "PATH_REV": "1",
        "PATH_CATEGORY": "ETHERNET",
        "PATH_A_SITE": "it should grab this item for leg_z_site_name",
        "PATH_Z_SITE": "blah",
        "A_CLLI": "SHOKCA64",
        "Z_CLLI": "SHOKCA64",
        "PATH_A_SITE_TYPE": "LOCAL",
        "PATH_Z_SITE_TYPE": "LOCAL",
        "TOPOLOGY": "Point-to-point",
        "PATH_STATUS": "Planned",
        "CLASS_OF_SERVICE": None,
        "EVC_ID": None,
        "SERVICE_TYPE": "COM-DIA",
        "BANDWIDTH": "500 Mbps",
        "BW_SIZE": "500000000",
        "CUSTOMER_ID": "AMAZON RETAIL",
        "ASSIGNED_IP_SUBNET_MASK": "/30",
        "ASSIGNED_GLUE_SUBNET": "2600:5C00:3800::1012/127",
        "ASSIGNED_IP_SUBNET": "108.178.140.232",
        "ASSIGNED_IP_RANGE": "108.178.140.234 THRU 108.178.140.235",
        "GATEWAY_IP_ADDRESS": "108.178.140.233",
        "ASSIGNED_IPV6_GLUE_SUBNET": "2600:5C00:3800::1012/127",
        "ASSIGNED_IPV6_SUBNET": "2600:5C00:474B::/48",
        "ASSIGNED_IPV6_RANGE": "2600:5C00:474B:: THRU 2600:5C00:474B:FFFF:FFFF:FFFF:FFFF:FFFF",
        "IPV4_SERVICE_TYPE": "LAN",
        "IPV6_SERVICE_TYPE": "ROUTED",
        "CUSTOMER_TYPE": "ENTERPRISE",
        "SEQUENCE": "4",
        "MEMBER_NBR": None,
        "LEG_NAME": "1",
        "LEG_INST_ID": "2235554",
        "A_SITE_NAME": None,
        "Z_SITE_NAME": None,
        "A_SITE_TYPE": "LOCAL",
        "Z_SITE_TYPE": None,
        "ELEMENT_TYPE": "PORT",
        "ELEMENT_NAME": "SHOKCA642ZW/999.9999.999.99/NIU",
        "ELEMENT_REFERENCE": "1438519",
        "ELEMENT_CATEGORY": "NIU",
        "LEGACY_EQUIP_SOURCE": "TWC",
        "ELEMENT_STATUS": "Planned",
        "ELEMENT_BANDWIDTH": "10/100/1000 BASET",
        "CHAN_NAME": None,
        "CHAN_INST_ID": None,
        "SLOT": "CHASSIS",
        "PORT_NAME": "0/11",
        "PORT_INST_ID": "110178310",
        "PORT_ACCESS_ID": "ETH PORT 0/11",
        "CONNECTOR_TYPE": "RJ-45",
        "FQDN": "SHOKCA642ZW.CML.CHTRSE.COM",
        "MODEL": "ETX-2I-10G/4SFPP/4SFP4UTP",
        "VENDOR": "RAD",
        "TID": "SHOKCA642ZW",
        "MANAGEMENT_IP": "DHCP",
        "C_VLAN": None,
        "S_VLAN": None,
        "VLAN_OPERATION": "PUSH",
        "INITIAL_PATH_NAME": "81.L4XX.000347..CHTR",
        "INITIAL_CIRCUIT_ID": "1972067",
        "LVL": "1",
    },
]

v3_l1_info_good = {
    "ipc_path": "WEST",
    "customer_name": "AMAZON RETAIL",
    "customer_id": "AMAZON RETAIL",
    "mx": "VNNZCA242CW",
    "path_name": "81.L4XX.000347..CHTR",
    "path_rev": "1",
    "a_site_name": "it should grab this item for a_site_name",
    "z_site_name": "it should grab this item for z_site_name",
    "leg_name": "1",
    "leg_a_site_name": "it should grab this item for leg_a_site_name",
    "leg_z_site_name": "it should grab this item for leg_z_site_name",
}


l1_info_good = {
    "cloud_region": "WEST",
    "customer_name": "AMAZON RETAIL",
    "mx": "VNNZCA242CW",
    "path_name": "81.L4XX.000347..CHTR",
    "path_rev": "1",
    "a_site_name": "it should grab this item for a_site_name",
    "z_site_name": "it should grab this item for z_site_name",
    "leg_name": "1",
    "leg_a_site_name": "it should grab this item for leg_a_site_name",
    "leg_z_site_name": "it should grab this item for leg_z_site_name",
}


csip_raw = [
    {
        "CIRC_PATH_INST_ID": "1797088",
        "CIRCUIT_NAME": "51001.GE40L.AUSDTXIR9CW.AUSDTXIR0QW",
        "A_SITE_NAME": "AUSDTXIR_TWC/HE-AUSTIN MDC",
        "A_SITE_TYPE": "HEAD END",
        "A_SITE_REGION": "TEXAS",
        "A_ADDRESS": "11921 N MO PAC EXPY",
        "A_CITY": "AUSTIN",
        "A_STATE": "TX",
        "A_ZIP": "78759",
        "A_CLLI": "AUSDTXIR",
        "A_LONGITUDE": "-97.717044",
        "A_LATITUDE": "30.407112",
        "Z_SITE_NAME": "AUSDTXIR_TWC/HE-AUSTIN MDC",
        "Z_SITE_TYPE": "HEAD END",
        "Z_ADDRESS": "11921 N MO PAC EXPY",
        "Z_CITY": "AUSTIN",
        "Z_STATE": "TX",
        "Z_ZIP": "78759",
        "Z_CLLI": "AUSDTXIR",
        "Z_LONGITUDE": "-97.717044",
        "Z_LATITUDE": "30.407112",
        "LEG_NAME": "1",
        "LEG_INST_ID": "2039060",
    }
]

csip_raw_no_city = [
    {
        "CIRC_PATH_INST_ID": "1797088",
        "CIRCUIT_NAME": "51001.GE40L.AUSDTXIR9CW.AUSDTXIR0QW",
        "A_SITE_NAME": "AUSDTXIR_TWC/HE-AUSTIN MDC",
        "A_SITE_TYPE": "HEAD END",
        "A_SITE_REGION": "TEXAS",
        "A_ADDRESS": "11921 N MO PAC EXPY",
        "A_STATE": "TX",
        "A_ZIP": "78759",
        "A_CLLI": "AUSDTXIR",
        "A_LONGITUDE": "-97.717044",
        "A_LATITUDE": "30.407112",
        "Z_SITE_NAME": "AUSDTXIR_TWC/HE-AUSTIN MDC",
        "Z_SITE_TYPE": "HEAD END",
        "Z_ADDRESS": "11921 N MO PAC EXPY",
        "Z_STATE": "TX",
        "Z_ZIP": "78759",
        "Z_CLLI": "AUSDTXIR",
        "Z_LONGITUDE": "-97.717044",
        "Z_LATITUDE": "30.407112",
        "LEG_NAME": "1",
        "LEG_INST_ID": "2039060",
    }
]

csip_polish = {
    "a_state": "TX",
    "z_address": "11921 N MO PAC EXPY",
    "z_city": "AUSTIN",
    "z_state": "TX",
    "z_zip": "78759",
}

route_table_good = {
    "result": {
        "route-information": {
            "route-table": [{"rt": {"rt-destination": "0.0.0.0/0"}}, {"rt": {"rt-destination": "0.0.0.0/0"}}]
        }
    }
}

route_table_no_route_table_key = {"result": {"route-information": {"something": "weird"}}}

route_table_bad = {
    "result": {
        "route-information": {
            "route-table": [{"rt": {"rt-destination": "0.0.0.0/0"}}, {"rt": {"rt-destination": "0.0.0.0/24"}}]
        }
    }
}

fping_good = (
    b"\n       6 targets\n       0 alive\n       6 unreachable\n       0 unknown addresses\n\n       "
    b"6 timeouts (waiting for response)\n      24 ICMP Echos sent\n       0 ICMP Echo Replies received\n"
    b"       0 other ICMP received\n\n 0.00 ms (min round trip time)\n 0.00 ms (avg round trip time)\n "
    b"0.00 ms (max round trip time)\n        4.215 sec (elapsed real time)\n\n"
)


uda_update_good = {
    "pathId": "81.L4XX.000347..CHTR",
    "pathRev": "1",
    "status": "WEB SERVICE",
    "pathInstanceId": "1843845",
    "retString": "Path Updated",
}


test_data_for_charter_isis = (
    ("0001", "UHYTALIIHCW", "/Commercial/LCHTR/Central/Customer"),
    ("0425", "UHYTALIIHCW", "/Commercial/LCHTR/WI-MN/Customer"),
    ("0650", "UHYTALIIHCW", "/Commercial/LCHTR/Michigan/Customer"),
    ("1850", "UHYTALIIHCW", "/Commercial/LCHTR/GA-AL-TN-SC-NC/Alabama/Customer"),
    ("1850", "UHYTGAIIHCW", "/Commercial/LCHTR/GA-AL-TN-SC-NC/Georgia/Customer"),
    ("1850", "UHYTTNIIHCW", "/Commercial/LCHTR/GA-AL-TN-SC-NC/Tennessee/Customer"),
    ("1850", "UHYTSCIIHCW", "/Commercial/LCHTR/GA-AL-TN-SC-NC/Customer"),
    ("1850", "UHYTNCIIHCW", "/Commercial/LCHTR/GA-AL-TN-SC-NC/Customer"),
    ("1900", "UHYTALIIHCW", "/Commercial/LCHTR/Nevada/Customer"),
    ("2200", "UHYTALIIHCW", "/Commercial/LCHTR/SoCal/Customer"),
    ("2225", "UHYTALIIHCW", "/Commercial/LCHTR/SanLuisObispo/Customer"),
    ("2250", "UHYTALIIHCW", "/Commercial/LCHTR/Northwest/Customer"),
    ("2302", "UHYTALIIHCW", "/Commercial/LCHTR/MountainStates/Customer"),
    ("2303", "UHYTALIIHCW", "/Commercial/LCHTR/MountainStates/Customer"),
    ("2304", "UHYTALIIHCW", "/Commercial/LCHTR/MountainStates/Customer"),
    ("2397", "UHYTALIIHCW", "/Commercial/LCHTR/MountainStates/Customer"),
    ("2398", "UHYTALIIHCW", "/Commercial/LCHTR/MountainStates/Customer"),
    ("2400", "UHYTALIIHCW", "/Commercial/LCHTR/Texas/Customer"),
    ("2500", "UHYTALIIHCW", "/Commercial/LCHTR/Nebraska/Customer"),
    ("2ca2", "UHYTALIIHCW", "/Commercial/LCHTR/GA-AL-TN-SC-NC/Alabama/Customer"),
    ("2ca2", "UHYTGAIIHCW", "/Commercial/LCHTR/GA-AL-TN-SC-NC/Georgia/Customer"),
    ("2ca2", "UHYTTNIIHCW", "/Commercial/LCHTR/GA-AL-TN-SC-NC/Tennessee/Customer"),
    ("2ca2", "UHYTSCIIHCW", "/Commercial/LCHTR/GA-AL-TN-SC-NC/Customer"),
    ("2ca2", "UHYTNCIIHCW", "/Commercial/LCHTR/GA-AL-TN-SC-NC/Customer"),
    ("3000", "UHYTALIIHCW", "/Commercial/LCHTR/Louisiana/Customer"),
    ("8350", "UHYTALIIHCW", "/Commercial/LCHTR/NewEngland/Customer"),
    ("1111", "UHYTALIIHCW", None),  # error 501 - area '1111' doesn't exist
    ("1850", "UHYTQQIIHCW", None),  # error 501 - area 1850 exist but region doesn't exist
    ("2ca2", "UHYTQQIIHCW", None),  # error 501 - area 2ca2 exist but region doesn't exist
)


test_data_for_bright_house = (
    ("BKFDCACW", "/Commercial/LBHN/Bakersfield/Customer", None),
    ("BRHNALCW", "/Commercial/LBHN/Birmingham/Customer", None),
    ("IPLZINCW", "/Commercial/LBHN/Indianapolis/Customer", None),
    ("HRFRFLCW", "/Commercial/LBHN/Birmingham/Customer", None),
    ("TAMPFLCW", "/Commercial/LBHN/TampaBay/Customer", None),
    ("SFLDMICW", "/Commercial/LBHN/Detroit/Customer", None),
    ("ORLRFLCW", "/Commercial/LBHN/CentralFL/Customer", None),
    ("LKLFFLCW", "/Commercial/LBHN/TampaBay/Customer", None),
    ("ABDLFLCW", "/Commercial/LBHN/TampaBay/Customer", None),
    ("ALSPFLCW", "/Commercial/LBHN/CentralFL/Customer", None),
    ("APPKFLCW", "/Commercial/LBHN/CentralFL/Customer", None),
    ("AVONINCW", "/Commercial/LBHN/Indianapolis/Customer", None),
    ("BKFDCACW", "/Commercial/LBHN/Bakersfield/Customer", None),
    ("BKFECACW", "/Commercial/LBHN/Bakersfield/Customer", None),
    ("BKFICACW", "/Commercial/LBHN/Bakersfield/Customer", None),
    ("BKVLFLCW", "/Commercial/LBHN/TampaBay/Customer", None),
    ("BLTWFLCW", "/Commercial/LBHN/Birmingham/Customer", None),
    ("BLVWFLCW", "/Commercial/LBHN/CentralFL/Customer", None),
    ("BRHOALCW", "/Commercial/LBHN/Birmingham/Customer", None),
    ("BRHPALCW", "/Commercial/LBHN/Birmingham/Customer", None),
    ("BRNDFLCW", "/Commercial/LBHN/TampaBay/Customer", None),
    ("BRTNFLCW", "/Commercial/LBHN/TampaBay/Customer", None),
    ("BRTOFLCW", "/Commercial/LBHN/TampaBay/Customer", None),
    ("BSMRALCW", "/Commercial/LBHN/Birmingham/Customer", None),
    ("CHTHFLCW", "/Commercial/LBHN/Birmingham/Customer", None),
    ("CLIOALCW", "/Commercial/LBHN/Birmingham/Customer", None),
    ("CLMTFLCW", "/Commercial/LBHN/CentralFL/Customer", None),
    ("CLWSFLCW", "/Commercial/LBHN/TampaBay/Customer", None),
    ("CLWTFLCW", "/Commercial/LBHN/TampaBay/Customer", None),
    ("CNTMFLCW", "/Commercial/LBHN/Birmingham/Customer", None),
    ("CNTRFLCW", "/Commercial/LBHN/Birmingham/Customer", None),
    ("COCOFLCW", "/Commercial/LBHN/CentralFL/Customer", None),
    ("CPCNFLCW", "/Commercial/LBHN/CentralFL/Customer", None),
    ("CRMMINCW", "/Commercial/LBHN/Indianapolis/Customer", None),
    ("CTSGFLCW", "/Commercial/LBHN/TampaBay/Customer", None),
    ("DELDFLCW", "/Commercial/LBHN/CentralFL/Customer", None),
    ("DELNCACW", "/Commercial/LBHN/Bakersfield/Customer", None),
    ("DFSPFLCW", "/Commercial/LBHN/Birmingham/Customer", None),
    ("DLNDFLCW", "/Commercial/LBHN/CentralFL/Customer", None),
    ("DLTNFLCW", "/Commercial/LBHN/CentralFL/Customer", None),
    ("DNDNFLCW", "/Commercial/LBHN/TampaBay/Customer", None),
    ("DOVRFLCW", "/Commercial/LBHN/TampaBay/Customer", None),
    ("DVPTFLCW", "/Commercial/LBHN/TampaBay/Customer", None),
    ("DYBHFLCW", "/Commercial/LBHN/CentralFL/Customer", None),
    ("EDWRFLCW", "/Commercial/LBHN/CentralFL/Customer", None),
    ("ELFSFLCW", "/Commercial/LBHN/TampaBay/Customer", None),
    ("ELTNFLCW", "/Commercial/LBHN/TampaBay/Customer", None),
    ("EUFLALCW", "/Commercial/LBHN/Birmingham/Customer", None),
    ("FMHLMICW", "/Commercial/LBHN/Detroit/Customer", None),
    ("FTVLINCW", "/Commercial/LBHN/Indianapolis/Customer", None),
    ("GCVLFLCW", "/Commercial/LBHN/Birmingham/Customer", None),
    ("GENVALCW", "/Commercial/LBHN/Birmingham/Customer", None),
    ("GNVLALCW", "/Commercial/LBHN/Birmingham/Customer", None),
    ("HDSNFLCW", "/Commercial/LBHN/TampaBay/Customer", None),
    ("HNCYFLCW", "/Commercial/LBHN/TampaBay/Customer", None),
    ("INVRFLCW", "/Commercial/LBHN/TampaBay/Customer", None),
    ("IPLBINCW", "/Commercial/LBHN/Indianapolis/Customer", None),
    ("IPLTINCW", "/Commercial/LBHN/Indianapolis/Customer", None),
    ("KSSNFLCW", "/Commercial/LBHN/CentralFL/Customer", None),
    ("LAMTCACW", "/Commercial/LBHN/Bakersfield/Customer", None),
    ("LCNTFLCW", "/Commercial/LBHN/TampaBay/Customer", None),
    ("LIVNMICW", "/Commercial/LBHN/Detroit/Customer", None),
    ("LKLEFLCW", "/Commercial/LBHN/TampaBay/Customer", None),
    ("LKLFFLCW", "/Commercial/LBHN/TampaBay/Customer", None),
    ("LRGOFLCW", "/Commercial/LBHN/TampaBay/Customer", None),
    ("LUTZFLCW", "/Commercial/LBHN/TampaBay/Customer", None),
    ("MARNINCW", "/Commercial/LBHN/Indianapolis/Customer", None),
    ("MLBHFLCW", "/Commercial/LBHN/CentralFL/Customer", None),
    ("MLBKALCW", "/Commercial/LBHN/Birmingham/Customer", None),
    ("MLBRFLCW", "/Commercial/LBHN/CentralFL/Customer", None),
    ("MLBSFLCW", "/Commercial/LBHN/CentralFL/Customer", None),
    ("MRISFLCW", "/Commercial/LBHN/CentralFL/Customer", None),
    ("NPRCFLCW", "/Commercial/LBHN/TampaBay/Customer", None),
    ("NSBHFLCW", "/Commercial/LBHN/CentralFL/Customer", None),
    ("OCAMFLCW", "/Commercial/LBHN/CentralFL/Customer", None),
    ("OCOEFLCW", "/Commercial/LBHN/CentralFL/Customer", None),
    ("ORBHFLCW", "/Commercial/LBHN/CentralFL/Customer", None),
    ("ORLEFLCW", "/Commercial/LBHN/CentralFL/Customer", None),
    ("ORLHFLCW", "/Commercial/LBHN/CentralFL/Customer", None),
    ("ORLJFLCW", "/Commercial/LBHN/CentralFL/Customer", None),
    ("ORLNFLCW", "/Commercial/LBHN/CentralFL/Customer", None),
    ("OVIDFLCW", "/Commercial/LBHN/CentralFL/Customer", None),
    ("PLBYFLCW", "/Commercial/LBHN/CentralFL/Customer", None),
    ("PLCSFLCW", "/Commercial/LBHN/CentralFL/Customer", None),
    ("PLHRFLCW", "/Commercial/LBHN/TampaBay/Customer", None),
    ("PRSHFLCW", "/Commercial/LBHN/TampaBay/Customer", None),
    ("PTCYFLCW", "/Commercial/LBHN/TampaBay/Customer", None),
    ("PTORFLCW", "/Commercial/LBHN/CentralFL/Customer", None),
    ("RSKNFLCW", "/Commercial/LBHN/TampaBay/Customer", None),
    ("SEMLFLCW", "/Commercial/LBHN/TampaBay/Customer", None),
    ("SFHRFLCW", "/Commercial/LBHN/TampaBay/Customer", None),
    ("SHHCFLCW", "/Commercial/LBHN/TampaBay/Customer", None),
    ("SLCMALCW", "/Commercial/LBHN/Birmingham/Customer", None),
    ("SNANFLCW", "/Commercial/LBHN/TampaBay/Customer", None),
    ("SNFRFLCW", "/Commercial/LBHN/CentralFL/Customer", None),
    ("SPBGFLCW", "/Commercial/LBHN/TampaBay/Customer", None),
    ("SPBKFLCW", "/Commercial/LBHN/TampaBay/Customer", None),
    ("SRSVFLCW", "/Commercial/LBHN/TampaBay/Customer", None),
    ("STBHFLCW", "/Commercial/LBHN/CentralFL/Customer", None),
    ("STCDFLCW", "/Commercial/LBHN/CentralFL/Customer", None),
    ("TAFTCACW", "/Commercial/LBHN/Bakersfield/Customer", None),
    ("TAMPFLCW", "/Commercial/LBHN/TampaBay/Customer", None),
    ("TAMQFLCW", "/Commercial/LBHN/TampaBay/Customer", None),
    ("TAMRFLCW", "/Commercial/LBHN/TampaBay/Customer", None),
    ("TAMVFLCW", "/Commercial/LBHN/TampaBay/Customer", None),
    ("TAMWFLCW", "/Commercial/LBHN/TampaBay/Customer", None),
    ("THCHCACW", "/Commercial/LBHN/Bakersfield/Customer", None),
    ("TLLSALCW", "/Commercial/LBHN/Birmingham/Customer", None),
    ("TRSPFLCW", "/Commercial/LBHN/TampaBay/Customer", None),
    ("TTVLFLCW", "/Commercial/LBHN/CentralFL/Customer", None),
    ("TWCNFLCW", "/Commercial/LBHN/TampaBay/Customer", None),
    ("WASCCACW", "/Commercial/LBHN/Bakersfield/Customer", None),
    ("WIMMFLCW", "/Commercial/LBHN/TampaBay/Customer", None),
    ("WKWCFLCW", "/Commercial/LBHN/TampaBay/Customer", None),
    ("WLCHFLCW", "/Commercial/LBHN/TampaBay/Customer", None),
    ("WLWDFLCW", "/Commercial/LBHN/CentralFL/Customer", None),
    ("WNGRFLCW", "/Commercial/LBHN/CentralFL/Customer", None),
    ("WNHNFLCW", "/Commercial/LBHN/TampaBay/Customer", None),
    ("WNPKFLCW", "/Commercial/LBHN/CentralFL/Customer", None),
    ("WNSPFLCW", "/Commercial/LBHN/CentralFL/Customer", None),
    ("WTMPALCW", "/Commercial/LBHN/Birmingham/Customer", None),
    ("ZIVLINCW", "/Commercial/LBHN/Indianapolis/Customer", None),
    ("ZZZZCACW", "/Commercial/LBHN/Bakersfield/Customer", "BKFD"),
    ("ZZZZALCW", "/Commercial/LBHN/Birmingham/Customer", "BHAM"),
    ("ZZZZMICW", "/Commercial/LBHN/Detroit/Customer", "DETR"),
    ("ZZZZINCW", "/Commercial/LBHN/Indianapolis/Customer", "INDP"),
    ("ZZZZFLCW", "/Commercial/LBHN/CentralFL/Customer", "ORLD"),
    ("ZZZZFLCW", "/Commercial/LBHN/TampaBay/Customer", "TAMP"),
    ("UGIIJDCW", None, None),  # error 501
    ("UGIIJDCW", None, None),  # error 501
    ("UJKLLHCW", None, "UUUU"),  # error 501
)

# ### Begin LCHTR IS-IS mocks ### #
# Mimic Postman Examples

mock_import_calls = [
    # 0 ipv4
    (
        {
            "v4_glue_block": "11.11.11.0/27",
            "v4_glue_net": "11.11.11.0",
            "v4_glue_cidr": "/27",
            "v4_glue_gateway": "11.11.11.1/27",
        },
        "11.11.11.0",
        "11.11.11.0",
    ),
    # 1 ipv6 glue
    (
        {"v6_glue_block": "2605:A40A:7E::18/127", "v6_glue_net": "2605:A40A:7E::18", "v6_glue_cidr": "/127"},
        "11.11.11.0",
        "11.11.11.0",
    ),
    # 2 ipv6 routed
    (
        {"v6_route_block": "2605:A40A:20B::/48", "v6_route_net": "2605:A40A:20B::", "v6_route_cidr": "/48"},
        "11.11.11.0",
        "11.11.11.0",
    ),
]

mock_mx_interfaces = {
    "command": "get-interfaces-config.json",
    "result": {
        "configuration": {
            "interfaces": {
                "ae17": {
                    "description": "AGG:arsncabs0qw:ae17:10.28.128.2:53001.GE40L.ARSNCABS1CW.ARSNCABS0QW",
                    "name": "ae17",
                    "unit": [
                        {
                            "description": "CUST:FIA:Northland Cable@7203 SANDS LANE:53.L1XX.000102..TWCC:",
                            "family": {"inet": {"address": [{"name": "71.94.42.9/29"}]}},
                        }
                    ],
                }
            }
        }
    },
}
