.bpocore-cli-onboard:
  image: registry.blueplanet.com/blueplanet/devtools/common-ci-cd-automations/bpocore-cli-onboard:0.0.1
  stage: build
  script:
    - if [[ -z "${BPOCORE_BASE_URL}" ]]; then echo "FAILURE. BPOCORE_BASE_URL env var must be set." && false;fi
    - j2 /usr/local/src/default.yaml.j2 > default.yaml
    - cat default.yaml | yq .base_url | xargs curl -k # Check connectivity to BPO
    - bpocore --site-config-dir ./ assets push-identity
    - bpocore --site-config-dir ./ assets pull-identity
    - bpocore --site-config-dir ./ onboard ${BPOCORE_ONBOARD_EXTRAS} model-definitions
