REQUIRED_TPE_FRE_VALUES = {
    "PE": {
        "JUNIPER": {
            "FIA": {
                "FRE": [
                    "ipv4",
                    "ipv6",
                    "vlan",
                    "ms_vlan",
                    "nextipv4hop",
                    "nextipv6hop",
                    "bandwidth_description",
                    "e_bwProfileFlowParameters",
                    "in_bwProfileFlowParameters",
                ],
                "Client TPE": ["apply-groups"],
            },
            "CTBH 4G": {
                "FRE": [
                    "bwProfileFlowParameters",
                    "vlan",
                    "ms_vlan",
                    "cos",
                    "sub_interace UserLabel",
                    "remoteCarrierName",
                    "siteNetworkAccessId",
                ],
                "Client TPE": ["apply-groups", "bwProfileFlowParameters"],
            },
            "ELINE": {
                "FRE": [
                    "bwProfileFlowParameters",
                    "vlan",
                    "ms_vlan",
                    "cos",
                    "sub_interace UserLabel",
                    "remoteCarrierName",
                    "siteNetworkAccessId",
                ],
                "Client TPE": ["apply-groups", "bwProfileFlowParameters"],
            },
            "ELAN": {
                "FRE": ["routeTarget", "bandwidth", "vlan-id", "ms_vlan", "vlanId"],
                "Client TPE": ["apply-groups"],
            },
            "VOICE": {
                "FRE": [
                    "ipv4",
                    "vlan",
                    "ms_vlan",
                ],
                "Client TPE": ["apply-groups"],
            },
            "NNI": {"FRE": ["port_slotted"], "Client TPE": ["description"]},
        },
        "NOKIA": {
            "CTBH 4G": {
                "FRE": [
                    "customer_name",
                    # "customer_description", # This is supose to be the same as service_description
                    "service_type",
                    "service_id",
                    "service_name",
                    "service_description",
                    "service_mtu",
                    "sap",
                    "sdp",
                    "vlan",
                    "qos_policy_id",
                    # "qos_description",
                    "rate",
                    "cir",
                    "cbs",
                    "port",
                    "port_description",
                    "port_speed",
                ],
                "Client TPE": [],
            }
        },
        "CISCO": {
            "FIA": {
                "FRE": [
                    "ipv4",
                    "ipv6",
                    "vlan",
                    "state",
                    "subnet",
                    "orchState",
                    "bandwidth",
                    "ipv4AccessGroup",
                    "ipv6AccessGroup",
                    "portDescription",
                    "serviceDescription",
                    "servicePolicyInput",
                    "servicePolicyOutput",
                ]
            },
            "ELINE": {
                "FRE": [
                    "evc",
                    "vlan",
                    "state",
                    "orchState",
                    "bandwidth",
                    "neighborIp",
                    "portDescription",
                    "serviceDescription",
                    "servicePolicyInput",
                    "servicePolicyOutput",
                    "l2vpnLocalSegment1",
                    "l2vpnRemoteSegment2",
                ]
            },
            "CTBH 4G": {
                "FRE": [
                    "evc",
                    "vlan",
                    "state",
                    "orchState",
                    "bandwidth",
                    "neighborIp",
                    "portDescription",
                    "serviceDescription",
                    "servicePolicyInput",
                    "servicePolicyOutput",
                    "l2vpnLocalSegment1",
                    "l2vpnRemoteSegment2",
                ]
            },
            "ELAN": {
                "FRE": [
                    "vlan",
                    "state",
                    "orchState",
                    "bandwidth",
                    "portDescription",
                    "serviceDescription",
                    "servicePolicyInput",
                    "bridgeDomainState",
                ]
            },
            "VOICE": {
                "FRE": [
                    "ipv4",
                    "vlan",
                    "state",
                    "subnet",
                    "orchState",
                    "bandwidth",
                    "portDescription",
                    "serviceDescription",
                    "servicePolicyInput",
                    "servicePolicyOutput",
                ]
            },
            "NNI": {"FRE": ["port_slotted"], "Client TPE": ["description"]},
        },
    },
    "AGG": {
        "JUNIPER": {
            "FIA": {
                "FRE": [
                    "VLAN",
                    "ms_vlan",
                ],
                "Client TPE": ["apply-groups"],
            },
            "ELINE": {
                "FRE": [
                    "VLAN",
                    "ms_vlan",
                ],
                "Client TPE": ["apply-groups"],
            },
            "CTBH 4G": {
                "FRE": [
                    "VLAN",
                    "ms_vlan",
                ],
                "Client TPE": ["apply-groups"],
            },
            "ELAN": {
                "FRE": ["VLAN", "ms_vlan", "vlan_name"],
                "Client TPE": ["apply-groups"],
            },
            "VOICE": {
                "FRE": [
                    "VLAN",
                    "ms_vlan",
                ],
                "Client TPE": ["apply-groups"],
            },
        }
    },
    "MTU": {
        "JUNIPER": {
            "FIA": {
                "FRE": ["VLAN", "ms_vlan"],
                "Client TPE": ["apply-groups"],
            },
            "ELINE": {
                "FRE": ["VLAN", "ms_vlan"],
                "Client TPE": ["apply-groups"],
            },
            "CTBH 4G": {
                "FRE": ["VLAN", "ms_vlan"],
                "Client TPE": ["apply-groups"],
            },
            "ELAN": {
                "FRE": ["VLAN", "ms_vlan", "vlan_name"],
                "Client TPE": [],
            },
            "VOICE": {
                "FRE": ["VLAN", "ms_vlan"],
                "Client TPE": ["apply-groups"],
            },
        },
        "ADVA": {
            "FIA": {
                "FRE": [
                    # "ms_vlan",
                    "serviceName",
                    "orchState",
                    "value",
                    "epAccessA2NFlowCir",
                    "epAccessA2NFlowEir",
                    "epAccessFlowCVlanTag",
                    "epAccessFlowCVlanTagControl",
                    "circuitName",
                    "egressAction",
                    "epAccessFlowCVlanTag",
                ],
                "Client TPE": ["state", "userLabel"],
                "Client PTP": [],
                "Network TPE": [],
            },
            "ELINE": {
                "FRE": [
                    "ms_vlan",
                    "serviceName",
                    "orchState",
                    "value",
                    "epAccessA2NFlowCir",
                    "epAccessA2NFlowEir",
                    "epAccessFlowCVlanTag",
                    "epAccessFlowCVlanTagControl",
                    "circuitName",
                    "egressAction",
                    "epAccessFlowCVlanTag",
                ],
                "Client TPE": ["state", "userLabel"],
                "Client PTP": [],
                "Network TPE": [],
            },
            "CTBH 4G": {
                "FRE": [
                    "ms_vlan",
                    "serviceName",
                    "orchState",
                    "value",
                    "epAccessA2NFlowCir",
                    "epAccessA2NFlowEir",
                    "epAccessFlowCVlanTag",
                    "epAccessFlowCVlanTagControl",
                    "circuitName",
                    "egressAction",
                    "epAccessFlowCVlanTag",
                ],
                "Client TPE": ["state", "userLabel"],
                "Client PTP": [],
                "Network TPE": [],
            },
            "ELAN": {
                "FRE": [
                    "ms_vlan",
                    "adminState",
                    "epAccessA2NFlowCir",
                    "circuitName",
                    "egressAction",
                    "epAccessFlowCVlanTag",
                ],
                "Client TPE": [
                    "state",
                    "userLabel",
                    "eir",
                    "cir",
                    "c_tag_pbit",
                    "vlanId",
                ],
                "Client PTP": ["state", "userLabel"],
                "Network TPE": [
                    "state",
                    "userLabel",
                    "eir",
                    "cir",
                    "c_tag_pbit",
                    "vlanId",
                ],
            },
            "VOICE": {
                "FRE": [
                    "ms_vlan",
                    "serviceName",
                    "orchState",
                    "value",
                    "epAccessA2NFlowCir",
                    "epAccessA2NFlowEir",
                    "epAccessFlowCVlanTag",
                    "epAccessFlowCVlanTagControl",
                    "circuitName",
                    "egressAction",
                    "epAccessFlowCVlanTag",
                ],
                "Client TPE": ["state", "userLabel"],
                "Client PTP": [],
                "Network TPE": [],
            },
        },
        "RAD": {
            "FIA": {
                "FRE": [
                    "name",
                    "vlan",
                    # "ms_vlan",
                    # "mac_l2cp",
                    "admin_state",
                    # "operation_state",
                    "service_name_IN",
                    "service_name_OUT",
                    "egress_port_id_IN",
                    "egress_port_id_OUT",
                    "ingress_port_id_IN",
                    "ingress_port_id_OUT",
                    # "ms_egress_port_id_IN",
                    # "ms_egress_port_id_OUT",
                    # "ms_ingress_port_id_IN",
                    # "ms_ingress_port_id_OUT",
                ],
                "Client TPE": [],
            },
            "CTBH 4G": {
                "FRE": [
                    "name",
                    "vlan",
                    # "ms_vlan",
                    # "mac_l2cp",
                    "admin_state",
                    # "operation_state",
                    "service_name_IN",
                    "service_name_OUT",
                    "egress_port_id_IN",
                    "egress_port_id_OUT",
                    "ingress_port_id_IN",
                    "ingress_port_id_OUT",
                    # "ms_egress_port_id_IN",
                    # "ms_egress_port_id_OUT",
                    # "ms_ingress_port_id_IN",
                    # "ms_ingress_port_id_OUT",
                ],
                "Client TPE": [],
            },
            "ELINE": {
                "FRE": [
                    "name",
                    "vlan",
                    # "ms_vlan",
                    # "mac_l2cp",
                    "admin_state",
                    # "operation_state",
                    "service_name_IN",
                    "service_name_OUT",
                    "egress_port_id_IN",
                    "egress_port_id_OUT",
                    "ingress_port_id_IN",
                    "ingress_port_id_OUT",
                    # "ms_egress_port_id_IN",
                    # "ms_egress_port_id_OUT",
                    # "ms_ingress_port_id_IN",
                    # "ms_ingress_port_id_OUT",
                ],
                "Client TPE": [],
            },
            "ELAN": {
                "FRE": [
                    "name",
                    "vlan",
                    # "ms_vlan",
                    # "mac_l2cp",
                    "admin_state",
                    # "operation_state",
                    "service_name_IN",
                    "service_name_OUT",
                    "egress_port_id_IN",
                    "egress_port_id_OUT",
                    "ingress_port_id_IN",
                    "ingress_port_id_OUT",
                    # "ms_egress_port_id_IN",
                    # "ms_egress_port_id_OUT",
                    # "ms_ingress_port_id_IN",
                    # "ms_ingress_port_id_OUT",
                ],
                "Client TPE": [],
            },
            "VOICE": {
                "FRE": [
                    "name",
                    "vlan",
                    # "ms_vlan",
                    # "mac_l2cp",
                    "admin_state",
                    # "operation_state",
                    "service_name_IN",
                    "service_name_OUT",
                    "egress_port_id_IN",
                    "egress_port_id_OUT",
                    "ingress_port_id_IN",
                    "ingress_port_id_OUT",
                    # "ms_egress_port_id_IN",
                    # "ms_egress_port_id_OUT",
                    # "ms_ingress_port_id_IN",
                    # "ms_ingress_port_id_OUT",
                ],
                "Client TPE": [],
            },
        },
        "CISCO": {
            "FIA": {
                "FRE": [
                    "vlan",
                    "state",
                    "orchState",
                    "adminState",
                    "portDescription",
                    "serviceDescription",
                ]
            },
            "ELINE": {
                "FRE": [
                    "vlan",
                    "state",
                    "orchState",
                    "adminState",
                    "portDescription",
                    "serviceDescription",
                ]
            },
            "CTBH 4G": {
                "FRE": [
                    "vlan",
                    "state",
                    "orchState",
                    "adminState",
                    "portDescription",
                    "serviceDescription",
                ]
            },
            "ELAN": {
                "FRE": [
                    "vlan",
                    "state",
                    "orchState",
                    "adminState",
                    "portDescription",
                    "serviceDescription",
                ]
            },
            "VOICE": {
                "FRE": [
                    "vlan",
                    "state",
                    "orchState",
                    "adminState",
                    "portDescription",
                    "serviceDescription",
                ]
            },
        },
    },
    "CPE": {
        "JUNIPER": {"NNI": {"FRE": ["port_slotted"], "Client TPE": ["description"]}},
        "ADVA": {
            "FIA": {
                "FRE": [
                    "ms_vlan",
                    "serviceName",
                    "orchState",
                    "value",
                    "epAccessA2NFlowCir",
                    "epAccessA2NFlowEir",
                    "epAccessFlowCVlanTag",
                    "epAccessFlowCVlanTagControl",
                    "circuitName",
                    "egressAction",
                    "epAccessFlowCVlanTag",
                ],
                "Client TPE": [
                    "state",
                    "userLabel",
                    "cir",
                    "eir",
                    "c_tag_pbit",
                    "vlanId",
                ],
                "Client PTP": ["state", "userLabel"],
                "Network TPE": [],
            },
            "ELINE": {
                "FRE": [
                    "ms_vlan",
                    "serviceName",
                    "orchState",
                    "value",
                    "epAccessA2NFlowCir",
                    "epAccessA2NFlowEir",
                    "epAccessFlowCVlanTag",
                    "epAccessFlowCVlanTagControl",
                    "circuitName",
                    "egressAction",
                    "epAccessFlowCVlanTag",
                ],
                "Client TPE": [
                    "state",
                    "userLabel",
                    "cir",
                    "eir",
                    "c_tag_pbit",
                    "vlanId",
                ],
                "Client PTP": ["state", "userLabel"],
                "Network TPE": [],
            },
            "CTBH 4G": {
                "FRE": [
                    "ms_vlan",
                    "serviceName",
                    "orchState",
                    "value",
                    "epAccessA2NFlowCir",
                    "epAccessA2NFlowEir",
                    "epAccessFlowCVlanTag",
                    "epAccessFlowCVlanTagControl",
                    "circuitName",
                    "egressAction",
                    "epAccessFlowCVlanTag",
                ],
                "Client TPE": [
                    "state",
                    "userLabel",
                    "cir",
                    "eir",
                    "c_tag_pbit",
                    "vlanId",
                ],
                "Client PTP": ["state", "userLabel"],
                "Network TPE": [],
            },
            "ELAN": {
                "FRE": [
                    "ms_vlan",
                    "adminState",
                    "epAccessA2NFlowCir",
                    "circuitName",
                    "egressAction",
                    "epAccessFlowCVlanTag",
                ],
                "Client TPE": [
                    "state",
                    "userLabel",
                    "cir",
                    "eir",
                    "c_tag_pbit",
                    "vlanId",
                ],
                "Client PTP": ["state", "userLabel"],
                "Network TPE": [
                    "state",
                    "userLabel",
                    "cir",
                    "eir",
                    "c_tag_pbit",
                    "vlanId",
                ],
            },
            "VOICE": {
                "FRE": [
                    "ms_vlan",
                    "serviceName",
                    "orchState",
                    "value",
                    "epAccessA2NFlowCir",
                    "epAccessA2NFlowEir",
                    "epAccessFlowCVlanTag",
                    "epAccessFlowCVlanTagControl",
                    "circuitName",
                    "egressAction",
                    "epAccessFlowCVlanTag",
                ],
                "Client TPE": [
                    "state",
                    "userLabel",
                    "cir",
                    "eir",
                    "c_tag_pbit",
                    "vlanId",
                ],
                "Client PTP": ["state", "userLabel"],
                "Network TPE": [],
            },
        },
        "RAD": {
            "FIA": {
                "FRE": [
                    "name",
                    "vlan",
                    # "p_bit",
                    # "ms_vlan",
                    # "mac_l2cp",
                    "admin_state",
                    "policer_name",
                    # "operation_state",
                    "service_name_IN",
                    "service_name_OUT",
                    "egress_port_id_IN",
                    "egress_port_id_OUT",
                    "ingress_port_id_IN",
                    "ingress_port_id_OUT",
                    # "ms_egress_port_id_IN",
                    # "ms_egress_port_id_OUT",
                    # "ms_ingress_port_id_IN",
                    # "ms_ingress_port_id_OUT",
                ],
                "Client TPE": [],
            },
            "ELINE": {
                "FRE": [
                    "name",
                    "vlan",
                    "p_bit",
                    # "ms_vlan",
                    # "mac_l2cp",
                    "admin_state",
                    "policer_name",
                    # "operation_state",
                    "service_name_IN",
                    "service_name_OUT",
                    "egress_port_id_IN",
                    "egress_port_id_OUT",
                    "ingress_port_id_IN",
                    "ingress_port_id_OUT",
                    # "ms_egress_port_id_IN",
                    # "ms_egress_port_id_OUT",
                    # "ms_ingress_port_id_IN",
                    # "ms_ingress_port_id_OUT",
                ],
                "Client TPE": [],
            },
            "CTBH 4G": {
                "FRE": [
                    "name",
                    "vlan",
                    "p_bit",
                    # "ms_vlan",
                    # "mac_l2cp",
                    "admin_state",
                    "policer_name",
                    # "operation_state",
                    "service_name_IN",
                    "service_name_OUT",
                    "egress_port_id_IN",
                    "egress_port_id_OUT",
                    "ingress_port_id_IN",
                    "ingress_port_id_OUT",
                    # "ms_egress_port_id_IN",
                    # "ms_egress_port_id_OUT",
                    # "ms_ingress_port_id_IN",
                    # "ms_ingress_port_id_OUT",
                ],
                "Client TPE": [],
            },
            "ELAN": {
                "FRE": [
                    "name",
                    "vlan",
                    "p_bit",
                    # "ms_vlan",
                    # "mac_l2cp",
                    "admin_state",
                    "policer_name",
                    # "operation_state",
                    "service_name_IN",
                    "service_name_OUT",
                    "egress_port_id_IN",
                    "egress_port_id_OUT",
                    "ingress_port_id_IN",
                    "ingress_port_id_OUT",
                    # "ms_egress_port_id_IN",
                    # "ms_egress_port_id_OUT",
                    # "ms_ingress_port_id_IN",
                    # "ms_ingress_port_id_OUT",
                ],
                "Client TPE": [],
            },
            "VOICE": {
                "FRE": [
                    "name",
                    "vlan",
                    "p_bit",
                    # "ms_vlan",
                    # "mac_l2cp",
                    "admin_state",
                    "policer_name",
                    # "operation_state",
                    "service_name_IN",
                    "service_name_OUT",
                    "egress_port_id_IN",
                    "egress_port_id_OUT",
                    "ingress_port_id_IN",
                    "ingress_port_id_OUT",
                    # "ms_egress_port_id_IN",
                    # "ms_egress_port_id_OUT",
                    # "ms_ingress_port_id_IN",
                    # "ms_ingress_port_id_OUT",
                ],
                "Client TPE": [],
            },
            "NNI": {"FRE": ["port_slotted"], "Client TPE": ["description"]},
        },
        "CISCO": {
            "FIA": {
                "FRE": [
                    "vlan",
                    "state",
                    "orchState",
                    "bandwidth",
                    "adminState",
                    "operationalState",
                    "servicePolicyInput",
                    "portDescription",
                ]
            },
            "ELINE": {
                "FRE": [
                    "vlan",
                    "state",
                    "orchState",
                    "bandwidth",
                    "adminState",
                    "operationalState",
                    "servicePolicyInput",
                    "portDescription",
                ]
            },
            "CTBH 4G": {
                "FRE": [
                    "vlan",
                    "state",
                    "orchState",
                    "bandwidth",
                    "adminState",
                    "operationalState",
                    "servicePolicyInput",
                    "portDescription",
                ]
            },
            "ELAN": {
                "FRE": [
                    "vlan",
                    "state",
                    "orchState",
                    "bandwidth",
                    "adminState",
                    "operationalState",
                    "servicePolicyInput",
                    "portDescription",
                ]
            },
            "VOICE": {
                "FRE": [
                    "vlan",
                    "state",
                    "orchState",
                    "bandwidth",
                    "adminState",
                    "operationalState",
                    "servicePolicyInput",
                    "portDescription",
                ]
            },
            "NNI": {"FRE": ["port_slotted"], "Client TPE": ["description"]},
        },
    },
}


REQUIRED_TPE_FRE_VALUES_ADVA_PRO = {
    "MTU": {
        "ADVA": {
            "FIA": {
                "FRE": [
                    "ms_vlan",
                    "serviceName",
                    "orchState",
                    "value",
                    "epAccessA2NFlowCir",
                    "epAccessA2NFlowEir",
                    "epAccessFlowCVlanTag",
                    "epAccessFlowCVlanTagControl",
                    "circuitName",
                    "egressAction",
                    "epAccessFlowCVlanTag",
                ],
                "Client TPE": ["state", "userLabel", "eir", "cir", "vlanId"],
                "Client PTP": ["state", "userLabel"],
                "Network TPE": ["state", "userLabel", "eir", "cir", "vlanId"],
            },
            "ELINE": {
                "FRE": [
                    "ms_vlan",
                    "serviceName",
                    "orchState",
                    "value",
                    "epAccessA2NFlowCir",
                    "epAccessA2NFlowEir",
                    "c_tag_pbit",
                    "epAccessFlowCVlanTagControl",
                    "circuitName",
                    "egressAction",
                    "epAccessFlowCVlanTag",
                ],
                "Client TPE": ["state", "userLabel", "eir", "cir", "vlanId"],
                "Client PTP": ["state", "userLabel"],
                "Network TPE": ["state", "userLabel", "eir", "cir", "vlanId"],
            },
            "CTBH 4G": {
                "FRE": [
                    "ms_vlan",
                    "serviceName",
                    "orchState",
                    "value",
                    "epAccessA2NFlowCir",
                    "epAccessA2NFlowEir",
                    "c_tag_pbit",
                    "epAccessFlowCVlanTagControl",
                    "circuitName",
                    "egressAction",
                    "epAccessFlowCVlanTag",
                ],
                "Client TPE": ["state", "userLabel", "eir", "cir", "vlanId"],
                "Client PTP": ["state", "userLabel"],
                "Network TPE": ["state", "userLabel", "eir", "cir", "vlanId"],
            },
            "ELAN": {
                "FRE": [
                    "ms_vlan",
                    "adminState",
                    "epAccessA2NFlowCir",
                    "circuitName",
                    "egressAction",
                    "c_tag_pbit",
                ],
                "Client TPE": ["state", "userLabel", "eir", "cir", "vlanId"],
                "Client PTP": ["state", "userLabel"],
                "Network TPE": ["state", "userLabel", "eir", "cir", "vlanId"],
            },
            "VOICE": {
                "FRE": [
                    "ms_vlan",
                    "serviceName",
                    "orchState",
                    "value",
                    "epAccessA2NFlowCir",
                    "epAccessA2NFlowEir",
                    "epAccessFlowCVlanTag",
                    "epAccessFlowCVlanTagControl",
                    "circuitName",
                    "egressAction",
                    "c_tag_pbit",
                ],
                "Client TPE": ["state", "userLabel", "eir", "cir", "vlanId"],
                "Client PTP": ["state", "userLabel"],
                "Network TPE": ["state", "userLabel", "eir", "cir", "vlanId"],
            },
        },
    },
    "CPE": {
        "ADVA": {
            "FIA": {
                "FRE": [
                    "ms_vlan",
                    "serviceName",
                    "orchState",
                    "value",
                    "epAccessA2NFlowCir",
                    "epAccessA2NFlowEir",
                    "epAccessFlowCVlanTag",
                    "epAccessFlowCVlanTagControl",
                    "circuitName",
                    "egressAction",
                    "epAccessFlowCVlanTag",
                ],
                "Client TPE": ["state", "userLabel", "eir", "cir", "vlanId"],
                "Client PTP": ["state", "userLabel"],
                "Network TPE": ["state", "eir", "cir", "vlanId"],
            },
            "ELINE": {
                "FRE": [
                    "ms_vlan",
                    "serviceName",
                    "orchState",
                    "value",
                    "epAccessA2NFlowCir",
                    "epAccessA2NFlowEir",
                    "epAccessFlowCVlanTag",
                    "epAccessFlowCVlanTagControl",
                    "circuitName",
                    "egressAction",
                    "c_tag_pbit",
                ],
                "Client TPE": [
                    "state",
                    "userLabel",
                    "cir",
                    "eir",
                    "c_tag_pbit",
                    "vlanId",
                ],
                "Client PTP": ["state", "userLabel"],
                "Network TPE": ["state", "cir", "eir", "c_tag_pbit", "vlanId"],
            },
            "CTBH 4G": {
                "FRE": [
                    "ms_vlan",
                    "serviceName",
                    "orchState",
                    "value",
                    "epAccessA2NFlowCir",
                    "epAccessA2NFlowEir",
                    "epAccessFlowCVlanTag",
                    "epAccessFlowCVlanTagControl",
                    "circuitName",
                    "egressAction",
                    "c_tag_pbit",
                ],
                "Client TPE": [
                    "state",
                    "userLabel",
                    "cir",
                    "eir",
                    "c_tag_pbit",
                    "vlanId",
                ],
                "Client PTP": ["state", "userLabel"],
                "Network TPE": ["state", "cir", "eir", "c_tag_pbit", "vlanId"],
            },
            "ELAN": {
                "FRE": [
                    "ms_vlan",
                    "adminState",
                    "epAccessA2NFlowCir",
                    "circuitName",
                    "egressAction",
                    "c_tag_pbit",
                ],
                "Client TPE": [
                    "state",
                    "userLabel",
                    "cir",
                    "eir",
                    "c_tag_pbit",
                    "vlanId",
                ],
                "Client PTP": ["state", "userLabel"],
                "Network TPE": ["state", "cir", "eir", "c_tag_pbit", "vlanId"],
            },
            "VOICE": {
                "FRE": [
                    "ms_vlan",
                    "serviceName",
                    "orchState",
                    "value",
                    "epAccessA2NFlowCir",
                    "epAccessA2NFlowEir",
                    "epAccessFlowCVlanTag",
                    "epAccessFlowCVlanTagControl",
                    "circuitName",
                    "egressAction",
                    "epAccessFlowCVlanTag",
                ],
                "Client TPE": ["state", "userLabel", "eir", "cir", "vlanId"],
                "Client PTP": ["state", "userLabel"],
                "Network TPE": ["state", "eir", "cir", "vlanId"],
            },
        },
    },
}
