.solution-build:
  image: registry.blueplanet.com/blueplanet/devtools/common-ci-cd-automations/solution-build-image:0.0.5
  stage: build
  tags:
    - docker
  script:
    - if [[ -z "${CI_REGISTRY_IMAGE}" ]]; then echo "FAILURE.  Enable docker registry for the project. https://docs.gitlab.com/ee/user/project/container_registry.html#enable-the-container-registry-for-your-project" && false;fi
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - source commonci_set_env_vars
    - if [[ -z "${VENDOR}" ]]; then echo "FAILURE.  Enable the docker registry on the project. https://docs.gitlab.com/ee/user/project/container_registry.html#enable-the-container-registry-for-your-project" && false;fi
    - j2 solution/fig.j2 > solution/fig.yml
    - cat solution/fig.yml
    - solmaker build --registry=$REGISTRY --tag=$IMAGE_VERSION --vendor=$VENDOR solution/fig.yml
    - docker push $REGISTRY/$VENDOR/solution-$NAME:$IMAGE_VERSION
    - docker tag $REGISTRY/$VENDOR/solution-$NAME:$IMAGE_VERSION $REGISTRY/$VENDOR/solution-$NAME:$VERSION
    - if [ "$CI_COMMIT_REF_NAME" == "master" ]; then docker push $REGISTRY/$VENDOR/solution-$NAME:$VERSION && echo "SUCCESS. Pushed $REGISTRY/$VENDOR/solution-$NAME:$VERSION"; fi
    - echo "SUCCESS. Pushed $REGISTRY/$VENDOR/solution-$NAME:$IMAGE_VERSION"
  except:
    variables:
    - $CI_COMMIT_MESSAGE =~ /\[skip[ _-]image?\]/i
    - $SCHEDULE_SKIP =~ /\[skip[ _-]image?\]/i
