#Requires the Enviornment variable set $SlackUser
#Slack user can look like this
#SlackUser=@btwynham
#Slachuser=@channelName
#I believe you can have multiple individual users as well not sure on that format as of now

stages:
    - SlackMessage

SlackMessage:
  stage: SlackMessage
  tags:
    - docker
  image: registry.blueplanet.com/blueplanet/devtools/common-ci-cd-automations/build-image:0.0.8
  script:
    - printenv
    - curl https://slack.com/api/chat.postMessage -X POST -d "token=xoxp-3679967085-9749841941-70147353364-dc7c014649&channel=$SlackUser&text=\"FailedPipelineURL=$CI_PIPELINE_URL Branch=$CI_COMMIT_REF_NAME\"&username=TeamCity&as_user=false&pretty=1"
  rules:
    - when: on_failure
