.onboard:test:
  image: registry.blueplanet.com/blueplanet/devtools/common-ci-cd-automations/onboard-test:latest
  stage: test
  tags:
    - aws
  before_script:
    - python /main.py &>bpocore.log &
    - |
      i="0"
      while [[ $i -lt 15 ]]; do
        [[ $( bpocore ping ) = "up" ]] && break
        echo "Waiting for bpocore to come up"
        sleep 5
        i=$(($i+1))
      done
    - bpocore assets push-identity
    - ssh-keyscan -t ecdsa localhost >> ~/.ssh/known_hosts
  script:
    - bpocore onboard ./model-definitions
  artifacts:
    paths:
      - bpocore.log
    when: on_failure
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" || $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
