name: Docker Build and Publish

on:
  push:
    branches: [ main, develop ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ main, develop ]

env:
  REGISTRY: ghcr.io
  IMAGE_PREFIX: ${{ github.repository }}

jobs:
  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        component:
          - name: correlation-engine
            context: ./correlation-engine
            dockerfile: ./correlation-engine/Dockerfile
          - name: gateway
            context: ./gateway
            dockerfile: ./gateway/Dockerfile
          # - name: beorn
          #   context: ./sense-apps/beorn
          #   dockerfile: ./sense-apps/beorn/Dockerfile
          # - name: palantir
          #   context: ./sense-apps/palantir
          #   dockerfile: ./sense-apps/palantir/Dockerfile
          # - name: arda
          #   context: ./sense-apps/arda
          #   dockerfile: ./sense-apps/arda/Dockerfile

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/${{ matrix.component.name }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.component.context }}
          file: ${{ matrix.component.dockerfile }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            ARTIFACTORY_USER=${{ secrets.ARTIFACTORY_USER }}
            ARTIFACTORY_TOKEN=${{ secrets.ARTIFACTORY_TOKEN }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}