# Job for RAs
# Includes linting, ra unittests, app build etc

include:
  - local: 'code-quality/.code-climate.yml'
  - local: 'lint/.lint-gitlab-ci-template-master.yml'
  - local: 'ra-test/.ra-unittest-ps.yml'
  - local: 'auto-build/.auto-uprev-version.yml'
  - local: 'auto-build/.auto-build-app.yml'
  - local: 'auto-build/.update-app-in-remote-fig-repo.yml'
  - local: 'auto-build/.auto-release.yml'

stages:
  - lint
  - test
  - uprev
  - build
  - update-remote-solution
  - release

# Lint

# code quality jobs will run in the lint stages in all cases except when the version file has been modified.
.code-quality-pre-bump:
  extends: .code-quality
  stage: lint
  only:
    refs:
      - merge_requests
      - master
      - tags
      - /^release\/\d+\.\d+.*$/
  except:
    changes:
      - "version.json"

.code-quality-post-bump:
  extends: .code-quality
  stage: .post
  only:
    refs:
      - merge_requests
      - master
      - tags
      - /^release\/\d+\.\d+.*$/
    changes:
      - "version.json"

flake8-py27:
  extends: .flake8-py27

hocon-lint:
  extends: .hocon-lint

json-lint:
  extends: .json-lint

legacy-script-check:
  extends: .legacy-script-check
  when: manual

python-version-check:
  extends: .python-version-check
  when: manual

plansdk-deprecated-check:
  extends: .plansdk-deprecated-check
  when: manual

# Test

ra-unit-test:
  allow_failure: true
  image: registry.blueplanet.com/blueplanet/registry/base-image-devops-toolkit:20200910-py2.7
  extends: .ra-unit-test

# Uprev

uprev:
  extends: .uprev
  except:
    changes:
      - version.json
      - triggers
    variables:
      - $SKIP_UPREV =~ /true/
    refs:
      - schedules
  only:
    refs:
      - master
      - /^release\/\d+\.\d+.*$/
# Build

build-app:
  extends: .build-app
  only:
    refs:
      - master
      - develop
      - /^release\/\d+\.\d+.*$/
    changes:
      - version.json
  except:
    - schedules

mr-build-app:
  extends: .build-app
  only:
    - merge_requests
  except:
    - schedules
  when: manual

# Update remote

#update-remote-solution:
#  extends: .update-remote-solution
#  only:
#    refs:
#      - master
#      - /^release\/\d+\.\d+.*$/
#    changes:
#      - version.json

# Release

release:
  extends: .release
  except:
    variables:
      - $SKIP_RELEASE =~ /true/
    refs:
      - schedules
  only:
    changes:
      - version.json
    refs:
      - master
      - /^release\/\d+\.\d+.*$/
  when: manual
