# Job for a solution non-ra onboard type app with built in pypi server
# Includes linting, app & solution build etc

include:
  - local: 'lint/.lint-gitlab-ci-template-master.yml'
  - local: 'auto-build/.auto-uprev-version.yml'
  - local: 'auto-build/.auto-build-app.yml'
  - local: 'auto-build/.auto-build-pypi-master.yml'
  - local: 'auto-build/.auto-build-solution.yml'
  - local: 'auto-build/.auto-build-solution-did.yml'
  - local: 'auto-build/.auto-release.yml'

variables:
  PYPI: 'https://artifactory.ciena.com/api/pypi/blueplanet-pypi/simple'

stages:
  - lint
  - test
  - uprev
  - build
  - package
  - release
  - sanityTest

# Lint

flake8:
  extends: .flake8

hocon-lint:
  extends: .hocon-lint

json-lint:
  extends: .json-lint

legacy-script-check:
  extends: .legacy-script-check

python-version-check:
  extends: .python-version-check

plansdk-deprecated-check:
  extends: .plansdk-deprecated-check

# uprev

uprev:
  extends: .uprev
  except:
    changes:
      - version.json
      - triggers
    variables:
      - $SKIP_UPREV =~ /true/
    refs:
      - schedules
  only:
    refs:
      - develop
      - /^release\/\d+\.\d+.*$/

# Build
manual-start-build:
  stage: build
  script:
    echo "Starting solution build"
  only:
    - develop
    - merge_requests
  when: manual

build-app:
  extends: .build-app
  only:
    refs:
      - /^release\/\d+\.\d+.*$/
    changes:
      - version.json
  except:
    - schedules

mr-build-app:
  extends: .build-app
  needs: [manual-start-build]
  only:
    - develop
    - merge_requests
  except:
    - schedules

pypi-build:
  extends: .pypi-build
  variables:
    DOCKER_CLI_EXPERIMENTAL: "enabled"
    PUSH_PYPI_SOLUTION: "false"
  only:
    refs:
      - /^release\/\d+\.\d+.*$/
    changes:
      - version.json
  except:
    - schedules

mr-pypi-build:
  extends: .pypi-build
  variables:
    DOCKER_CLI_EXPERIMENTAL: "enabled"
  needs: [manual-start-build]
  only:
    - develop
    - merge_requests
  except:
    - schedules

build-solution:
  extends: .build-solution
  variables:
    BUNDLED_SOLUTION: "true"
  needs: [build-app, pypi-build]
  only:
    refs:
      - /^release\/\d+\.\d+.*$/
    changes:
      - version.json

mr-build-solution:
  extends: .build-solution
  variables:
    BUNDLED_SOLUTION: "true"
  needs: [mr-build-app, mr-pypi-build]
  only:
    - develop
    - merge_requests

# Package

#build-did:
#  extends: .build-did
#  only:
#    changes:
#      - version.json
#    refs:
#      - master
#      - /^release\/\d+\.\d+.*$/

#.mr-build-did:
#  extends: .build-did
#  only:
#    refs:
#      - merge_requests

# Release

#release:
#  extends: .release
#  except:
#    variables:
#      - $SKIP_RELEASE =~ /true/
#    refs:
#      - schedules
#  only:
#    changes:
#      - version.json
#    refs:
#      - master
#      - /^release\/\d+\.\d+.*$/
#  when: manual
