# Job for a single solution non-ra onboard type app
# Includes linting, app & solution build etc

include:
  - local: 'code-quality/.code-climate.yml'
  - local: 'lint/.lint-gitlab-ci-template-master.yml'
  - local: 'bpmn/.mvn-package.yml'
  - local: 'auto-build/.auto-uprev-version.yml'
  - local: 'auto-build/.auto-build-app.yml'
  - local: 'auto-build/.auto-build-solution.yml'
  - local: 'auto-build/.auto-build-solution-did.yml'
  - local: 'auto-build/.auto-release.yml'

variables:
  PYPI: 'https://artifactory.ciena.com/api/pypi/blueplanet-pypi/simple'

stages:
  - lint
  - test
  - uprev
  - compile
  - build
  - package
  - release
  - sanityTest

# Lint

# code quality jobs will run in the lint stages in all cases except when the version file has been modified.
.code-quality-pre-bump:
  extends: .code-quality
  stage: lint
  only:
    refs:
      - merge_requests
      - master
      - tags
      - /^release\/\d+\.\d+.*$/
  except:
    changes:
      - "version.json"

.code-quality-post-bump:
  extends: .code-quality
  stage: .post
  only:
    refs:
      - merge_requests
      - master
      - tags
      - /^release\/\d+\.\d+.*$/
    changes:
      - "version.json"

flake8:
  extends: .flake8

hocon-lint:
  extends: .hocon-lint

json-lint:
  extends: .json-lint

legacy-script-check:
  extends: .legacy-script-check

python-version-check:
  extends: .python-version-check

plansdk-deprecated-check:
  extends: .plansdk-deprecated-check

# uprev
uprev:
  extends: .uprev
  except:
    changes:
      - version.json
      - triggers
    variables:
      - $SKIP_UPREV =~ /true/
    refs:
      - schedules
  only:
    refs:
      - master
      - /^release\/\d+\.\d+.*$/

# compile:
mvn-package:
  extends: .mvn-package

mr-mvn-package:
  extends: .mvn-package
  needs: []
  only:
    - merge_requests
  when: manual

# Build
build-app:
  extends: .build-app
  dependencies: ["mvn-package"]
  only:
    refs:
      - master
      - /^release\/\d+\.\d+.*$/
    changes:
      - version.json
  except:
    - schedules

mr-build-app:
  extends: .build-app
  needs: []
  dependencies: ["mr-mvn-package"]
  only:
    - merge_requests
  except:
    - schedules
  when: manual

build-solution:
  extends: .build-solution
  only:
    refs:
      - master
      - /^release\/\d+\.\d+.*$/
    changes:
      - version.json

mr-build-solution:
  extends: .build-solution
  needs: []
  only:
    - merge_requests
  when: manual

# Package

build-did:
  extends: .build-did
  only:
    changes:
      - version.json
    refs:
      - master
      - /^release\/\d+\.\d+.*$/

mr-build-did:
  extends: .build-did
  only:
    refs:
      - merge_requests

# Release

release:
  extends: .release
  except:
    variables:
      - $SKIP_RELEASE =~ /true/
    refs:
      - schedules
  only:
    changes:
      - version.json
    refs:
      - master
      - /^release\/\d+\.\d+.*$/
  when: manual
