# Job for RAs
# Includes linting, ra unittests, app build etc

include:
  - local: 'code-quality/.code-climate.yml'
  - local: 'lint/.lint-gitlab-ci-template-master.yml'
  - local: 'ra-test/.ra-unittest-ps.yml'
  - local: 'auto-build/.auto-build-app.yml'
  - local: 'auto-build/.auto-uprev-version.yml'
  - local: 'auto-build/.auto-build-solution.yml'
  - local: 'auto-build/.auto-release.yml'
  - local: 'auto-build/.auto-build-solution-did.yml'

stages:
  - lint
  - test
  - uprev
  - build
  - package
  - release
  - sanityTest

# Lint

# code quality jobs will run in the lint stages in all cases except when the version file has been modified.
#.code-quality-pre-bump:
#  extends: .code-quality
#  stage: lint
#  only:
#    refs:
#      - merge_requests
#      - master
#      - tags
#      - /^release\/\d+\.\d+.*$/
#  except:
#    changes:
#     - "version.json"

#.code-quality-post-bump:
#  extends: .code-quality
#  stage: .post
#  only:
#    refs:
#      - merge_requests
#      - master
#      - tags
#      - /^release\/\d+\.\d+.*$/
#    changes:
#      - "version.json"

flake8-py27:
  extends: .flake8-py27

hocon-lint:
  extends: .hocon-lint

json-lint:
  extends: .json-lint

# Test

ra-unit-test:
  allow_failure: true
  image: $REGISTRY_NAME/docker/blueplanet/base-image-devops-toolkit:20200910-py2.7
  extends: .ra-unit-test

# Uprev

uprev:
  extends: .uprev
  except:
    changes:
      - version.json
      - triggers
    variables:
      - $SKIP_UPREV =~ /true/
    refs:
      - schedules
  only:
    refs:
      - develop
      - master
      - /^release\/\d+\.\d+.*$/

# Build

build-app:
  extends: .build-app
  only:
    refs:
      - master
      - develop
      - /^release\/\d+\.\d+.*$/
    changes:
      - version.json
  except:
    - schedules

mr-build-app:
  extends: .build-app
  only:
    - merge_requests
  except:
    - schedules
  when: manual

build-solution:
  extends: .build-solution
  needs: [build-app]
  only:
    refs:
      - master
      - develop
      - /^release\/\d+\.\d+.*$/
    changes:
      - version.json

mr-build-solution:
  extends: .build-solution
  needs: [mr-build-app]
  only:
    - merge_requests

# Package

#build-did:
#  extends: .build-did
#  only:
#    changes:
#      - version.json
#    refs:
#      - master
#      - /^release\/\d+\.\d+.*$/

#.mr-build-did:
#  extends: .build-did
#  only:
#    refs:
#      - merge_requests

# Release

release:
  extends: .release
  except:
    variables:
      - $SKIP_RELEASE =~ /true/
    refs:
      - schedules
  only:
    changes:
      - version.json
    refs:
      - master
      - /^release\/\d+\.\d+.*$/
  when: manual
