# Job for a single solution non-ra onboard type app
# Includes linting, app & solution build etc

include:
  - local: 'lint/.lint-gitlab-ci-template-master.yml'
  - local: 'auto-build/.auto-uprev-version.yml'
  - local: 'auto-build/.auto-build-app.yml'
  - local: 'auto-build/.auto-build-solution.yml'
  - local: 'auto-build/.auto-build-solution-did.yml'
  - local: 'auto-build/.auto-release.yml'

variables:
  PYPI: 'https://artifactory.ciena.com/api/pypi/blueplanet-pypi/simple'

stages:
  - lint
  - test
  - uprev
  - build
  - package
  - release
  - sanityTest

# Lint

flake8:
  extends: .flake8

hocon-lint:
  extends: .hocon-lint

json-lint:
  extends: .json-lint

legacy-script-check:
  extends: .legacy-script-check

python-version-check:
  extends: .python-version-check

plansdk-deprecated-check:
  extends: .plansdk-deprecated-check

# uprev

uprev:
  extends: .uprev
  except:
    changes:
      - version.json
      - triggers
    variables:
      - $SKIP_UPREV =~ /true/
    refs:
      - schedules
  only:
    refs:
      - develop
      - /^release\/\d+\.\d+.*$/
# Build

build-app:
  extends: .build-app
  only:
    refs:
      - tags
    variables:
      - $CI_COMMIT_TAG =~ /^release\/\d+\.\d+.*$/
  except:
    - schedules

mr-build-app:
  extends: .build-app
  only:
    - develop
    - merge_requests
  except:
    - schedules
  when: manual

build-solution:
  extends: .build-solution
  needs: [build-app]
  only:
    refs:
      - tags
    variables:
      - $CI_COMMIT_TAG =~ /^release\/\d+\.\d+.*$/

mr-build-solution:
  extends: .build-solution
  needs: [mr-build-app]
  only:
    - develop
    - merge_requests

# Package

#build-did:
#  extends: .build-did
#  only:
#    changes:
#      - version.json
#    refs:
#      - master
#      - /^release\/\d+\.\d+.*$/

#.mr-build-did:
#  extends: .build-did
#  only:
#    refs:
#      - merge_requests

# Release

#release:
#  extends: .release
#  except:
#    variables:
#      - $SKIP_RELEASE =~ /true/
#    refs:
#      - schedules
#  only:
#    changes:
#      - version.json
#    refs:
#      - master
#      - /^release\/\d+\.\d+.*$/
#  when: manual
