.ra-unit-test:
  image: artifactory.spectrumtoolbox.com/artifactory/docker/blueplanet/base-image-devops-toolkit:20220816-py3.8
  stage: test
  tags:
    - mdso
  script:
    - >
      if [[ ! "curl artifactory.spectrumtoolbox.com" ]]; then
          echo "
          *********************************************
          *
          * FAILURE.  artifactory not reachable
          *
          *********************************************"
          exit 1
      else
          EXTRA_PYPI="--extra-index-url https://artifactory.spectrumtoolbox.com/api/pypi/blueplanet-ubuntu-focal-pypi/simple"
      fi
    - apt-get update && apt-get install -y build-essential jq python3.8 python-dev python3.8-dev psmisc libpq-dev
    - export NAME=$(python setup.py --name)
    - pip install -i https://pypi.org/simple $EXTRA_PYPI -r requirements.txt -e .
    - export RASDK_SETTINGS_MODULE=$NAME.settings
    - rpsdk-validator $NAME.settings
    - bpprov-cli validate $NAME/model
    - bpprov-cli test $NAME/model --coverage
    - bpprov-cli test-error $NAME/model
  coverage: '/Coverage: \d+% \(\d+\/\d+\)/'
  only:
    refs:
      - merge_requests
      - master
      - tags
