mock_granite_circuit_devices = [
    {
        "CIRC_PATH_INST_ID": "1334717",
        "PATH_NAME": "33.L1XX.006714..TWCC",
        "PATH_REV": "1",
        "PATH_CATEGORY": "ETHERNET",
        "PATH_A_SITE": "WNSLNCPV-TWC/HUB WS-WINSTON",
        "PATH_Z_SITE": "WNSLNCKX-KUEHNE NAGEL//3929 WESTPOINT BLVD",
        "A_CLLI": "WNSLNCPV",
        "Z_CLLI": "WNSLNCKX",
        "PATH_A_SITE_TYPE": "HUB",
        "PATH_Z_SITE_TYPE": "LOCAL",
        "TOPOLOGY": "Point-to-point",
        "PATH_STATUS": "Pending Decommission",
        "CLASS_OF_SERVICE": None,
        "SLM_ELIGIBILITY": "ELIGIBLE DESIGN",
        "EVC_ID": None,
        "SERVICE_TYPE": "CAR-DIA",
        "BANDWIDTH": "25 Mbps",
        "BW_SIZE": "25000000",
        "CUSTOMER_ID": "ACCT-04400732",
        "CUSTOMER_NAME": "MASSCOMM",
        "IPV4_GLUE_SUBNET": None,
        "IPV4_ASSIGNED_SUBNETS": "173.95.101.40",
        "IPV4_ASSIGNED_GATEWAY": "173.95.101.41",
        "IPV4_SERVICE_TYPE": "LAN",
        "IPV6_GLUE_SUBNET": "2606:A000:0:8::F:3096/127",
        "IPV6_ASSIGNED_SUBNETS": "2600:5800:8C6::/48",
        "IPV6_SERVICE_TYPE": "ROUTED",
        "CUSTOMER_TYPE": "CARRIER ACCESS",
        "ORDER_REFERENCE": "4.",
        "PARENT_SEQUENCE": None,
        "PARENT_MEMBER_NBR": None,
        "SEQUENCE": "4",
        "MEMBER_NBR": None,
        "LEG_NAME": "1",
        "LEG_INST_ID": "1533950",
        "A_SITE_NAME": "WNSLNCKX-KUEHNE NAGEL//3929 WESTPOINT BLVD",
        "Z_SITE_NAME": None,
        "ELEMENT_TYPE": "PORT",
        "ELEMENT_NAME": "WNSLNCKX2ZW/999.9999.999.99",
        "ELEMENT_REFERENCE": "1037108",
        "ELEMENT_CATEGORY": "NIU",
        "ELEMENT_STATUS": "Pending Decommission",
        "ELEMENT_BANDWIDTH": "10/100/1000 BASET",
        "NEXT_PATH_INST_ID": None,
        "PREV_PATH_INST_ID": None,
        "CHAN_NAME": None,
        "CHAN_INST_ID": None,
        "SLOT": "FIXED PORTS",
        "PORT_NAME": "USER 3",
        "PORT_INST_ID": "103833216",
        "PORT_ACCESS_ID": "ETH PORT 3",
        "CONNECTOR_TYPE": "RJ-45",
        "FQDN": "WNSLNCKX2ZW.CML.CHTRSE.COM",
        "MODEL": "ETX203AX/2SFP/2UTP2SFP",
        "VENDOR": "RAD",
        "TID": "WNSLNCKX2ZW",
        "LEGACY_EQUIP_SOURCE": "L-TWC",
        "PURCHASING_GROUP": "ENTERPRISE",
        "IPV4_ADDRESS": "DHCP",
        "IPV6_ADDRESS": None,
        "C_VLAN": None,
        "CUST_S_VLAN": None,
        "S_VLAN": "1162",
        "VLAN_OPERATION": "PUSH",
        "PORT_ROLE": "UNI-EP",
        "INITIAL_PATH_NAME": "33.L1XX.006714..TWCC",
        "INITIAL_CIRCUIT_ID": "1334717",
        "LVL": "1",
    },
    {
        "CIRC_PATH_INST_ID": "1128201",
        "PATH_NAME": "33001.GE40L.WNSLNCPV1CW.WNSLNCPV0QW",
        "PATH_REV": "1",
        "PATH_CATEGORY": "ETHERNET TRANSPORT",
        "PATH_A_SITE": "WNSLNCPV-TWC/HUB WS-WINSTON",
        "PATH_Z_SITE": "WNSLNCPV-TWC/HUB WS-WINSTON",
        "A_CLLI": "WNSLNCPV",
        "Z_CLLI": "WNSLNCPV",
        "PATH_A_SITE_TYPE": "HUB",
        "PATH_Z_SITE_TYPE": "HUB",
        "TOPOLOGY": "Point-to-point",
        "PATH_STATUS": "Live",
        "CLASS_OF_SERVICE": None,
        "SLM_ELIGIBILITY": None,
        "EVC_ID": None,
        "SERVICE_TYPE": "INT-EDGE TRANSPORT",
        "BANDWIDTH": "AGGREGATE",
        "BW_SIZE": "0",
        "CUSTOMER_ID": None,
        "CUSTOMER_NAME": None,
        "IPV4_GLUE_SUBNET": None,
        "IPV4_ASSIGNED_SUBNETS": None,
        "IPV4_ASSIGNED_GATEWAY": None,
        "IPV4_SERVICE_TYPE": None,
        "IPV6_GLUE_SUBNET": None,
        "IPV6_ASSIGNED_SUBNETS": None,
        "IPV6_SERVICE_TYPE": None,
        "CUSTOMER_TYPE": None,
        "ORDER_REFERENCE": "2.1.1.",
        "PARENT_SEQUENCE": "2",
        "PARENT_MEMBER_NBR": "1",
        "SEQUENCE": "1",
        "MEMBER_NBR": None,
        "LEG_NAME": "AE17/AE17 80G",
        "LEG_INST_ID": "1313051",
        "A_SITE_NAME": "WNSLNCPV-TWC/HUB WS-WINSTON",
        "Z_SITE_NAME": None,
        "ELEMENT_TYPE": "PORT",
        "ELEMENT_NAME": "WNSLNCPV1CW/001.0001.102.11/RTR",
        "ELEMENT_REFERENCE": "514200",
        "ELEMENT_CATEGORY": "ROUTER",
        "ELEMENT_STATUS": "Live",
        "ELEMENT_BANDWIDTH": "40 Gbps",
        "NEXT_PATH_INST_ID": None,
        "PREV_PATH_INST_ID": None,
        "CHAN_NAME": "VLAN1162",
        "CHAN_INST_ID": "7163953",
        "SLOT": "3/0",
        "PORT_NAME": "1",
        "PORT_INST_ID": "103005919",
        "PORT_ACCESS_ID": "ET-4/3/0",
        "CONNECTOR_TYPE": "OTHER",
        "FQDN": "WNSLNCPV1CW.CHTRSE.COM",
        "MODEL": "MX960",
        "VENDOR": "JUNIPER",
        "TID": "WNSLNCPV1CW",
        "LEGACY_EQUIP_SOURCE": "L-TWC",
        "PURCHASING_GROUP": "ENTERPRISE",
        "IPV4_ADDRESS": "24.199.192.102/32",
        "IPV6_ADDRESS": "2606:A000::F:66/128",
        "C_VLAN": None,
        "CUST_S_VLAN": None,
        "S_VLAN": None,
        "VLAN_OPERATION": None,
        "PORT_ROLE": None,
        "INITIAL_PATH_NAME": "33.L1XX.006714..TWCC",
        "INITIAL_CIRCUIT_ID": "1334717",
        "LVL": "2",
    },
    {
        "CIRC_PATH_INST_ID": "1128201",
        "PATH_NAME": "33001.GE40L.WNSLNCPV1CW.WNSLNCPV0QW",
        "PATH_REV": "1",
        "PATH_CATEGORY": "ETHERNET TRANSPORT",
        "PATH_A_SITE": "WNSLNCPV-TWC/HUB WS-WINSTON",
        "PATH_Z_SITE": "WNSLNCPV-TWC/HUB WS-WINSTON",
        "A_CLLI": "WNSLNCPV",
        "Z_CLLI": "WNSLNCPV",
        "PATH_A_SITE_TYPE": "HUB",
        "PATH_Z_SITE_TYPE": "HUB",
        "TOPOLOGY": "Point-to-point",
        "PATH_STATUS": "Live",
        "CLASS_OF_SERVICE": None,
        "SLM_ELIGIBILITY": None,
        "EVC_ID": None,
        "SERVICE_TYPE": "INT-EDGE TRANSPORT",
        "BANDWIDTH": "AGGREGATE",
        "BW_SIZE": "0",
        "CUSTOMER_ID": None,
        "CUSTOMER_NAME": None,
        "IPV4_GLUE_SUBNET": None,
        "IPV4_ASSIGNED_SUBNETS": None,
        "IPV4_ASSIGNED_GATEWAY": None,
        "IPV4_SERVICE_TYPE": None,
        "IPV6_GLUE_SUBNET": None,
        "IPV6_ASSIGNED_SUBNETS": None,
        "IPV6_SERVICE_TYPE": None,
        "CUSTOMER_TYPE": None,
        "ORDER_REFERENCE": "2.1.2.",
        "PARENT_SEQUENCE": "2",
        "PARENT_MEMBER_NBR": "1",
        "SEQUENCE": "2",
        "MEMBER_NBR": None,
        "LEG_NAME": "AE17/AE17 80G",
        "LEG_INST_ID": "1313051",
        "A_SITE_NAME": "WNSLNCPV-TWC/HUB WS-WINSTON",
        "Z_SITE_NAME": None,
        "ELEMENT_TYPE": "PORT",
        "ELEMENT_NAME": "WNSLNCPV1CW/001.0001.102.11/RTR",
        "ELEMENT_REFERENCE": "514200",
        "ELEMENT_CATEGORY": "ROUTER",
        "ELEMENT_STATUS": "Live",
        "ELEMENT_BANDWIDTH": "40 Gbps",
        "NEXT_PATH_INST_ID": None,
        "PREV_PATH_INST_ID": None,
        "CHAN_NAME": "VLAN1162",
        "CHAN_INST_ID": "7163953",
        "SLOT": "3/0",
        "PORT_NAME": "1",
        "PORT_INST_ID": "103005944",
        "PORT_ACCESS_ID": "ET-8/3/0",
        "CONNECTOR_TYPE": "OTHER",
        "FQDN": "WNSLNCPV1CW.CHTRSE.COM",
        "MODEL": "MX960",
        "VENDOR": "JUNIPER",
        "TID": "WNSLNCPV1CW",
        "LEGACY_EQUIP_SOURCE": "L-TWC",
        "PURCHASING_GROUP": "ENTERPRISE",
        "IPV4_ADDRESS": "24.199.192.102/32",
        "IPV6_ADDRESS": "2606:A000::F:66/128",
        "C_VLAN": None,
        "CUST_S_VLAN": None,
        "S_VLAN": None,
        "VLAN_OPERATION": None,
        "PORT_ROLE": None,
        "INITIAL_PATH_NAME": "33.L1XX.006714..TWCC",
        "INITIAL_CIRCUIT_ID": "1334717",
        "LVL": "2",
    },
    {
        "CIRC_PATH_INST_ID": "1128201",
        "PATH_NAME": "33001.GE40L.WNSLNCPV1CW.WNSLNCPV0QW",
        "PATH_REV": "1",
        "PATH_CATEGORY": "ETHERNET TRANSPORT",
        "PATH_A_SITE": "WNSLNCPV-TWC/HUB WS-WINSTON",
        "PATH_Z_SITE": "WNSLNCPV-TWC/HUB WS-WINSTON",
        "A_CLLI": "WNSLNCPV",
        "Z_CLLI": "WNSLNCPV",
        "PATH_A_SITE_TYPE": "HUB",
        "PATH_Z_SITE_TYPE": "HUB",
        "TOPOLOGY": "Point-to-point",
        "PATH_STATUS": "Live",
        "CLASS_OF_SERVICE": None,
        "SLM_ELIGIBILITY": None,
        "EVC_ID": None,
        "SERVICE_TYPE": "INT-EDGE TRANSPORT",
        "BANDWIDTH": "AGGREGATE",
        "BW_SIZE": "0",
        "CUSTOMER_ID": None,
        "CUSTOMER_NAME": None,
        "IPV4_GLUE_SUBNET": None,
        "IPV4_ASSIGNED_SUBNETS": None,
        "IPV4_ASSIGNED_GATEWAY": None,
        "IPV4_SERVICE_TYPE": None,
        "IPV6_GLUE_SUBNET": None,
        "IPV6_ASSIGNED_SUBNETS": None,
        "IPV6_SERVICE_TYPE": None,
        "CUSTOMER_TYPE": None,
        "ORDER_REFERENCE": "2.2.1.",
        "PARENT_SEQUENCE": "2",
        "PARENT_MEMBER_NBR": "2",
        "SEQUENCE": "1",
        "MEMBER_NBR": None,
        "LEG_NAME": "AE17/AE17 80G",
        "LEG_INST_ID": "1313051",
        "A_SITE_NAME": "WNSLNCPV-TWC/HUB WS-WINSTON",
        "Z_SITE_NAME": None,
        "ELEMENT_TYPE": "PORT",
        "ELEMENT_NAME": "WNSLNCPV0QW/001.0004.010.26/SWT#0",
        "ELEMENT_REFERENCE": "895569",
        "ELEMENT_CATEGORY": "SWITCH",
        "ELEMENT_STATUS": "Live",
        "ELEMENT_BANDWIDTH": "40 Gbps",
        "NEXT_PATH_INST_ID": None,
        "PREV_PATH_INST_ID": None,
        "CHAN_NAME": "VLAN1162",
        "CHAN_INST_ID": "7163953",
        "SLOT": "96",
        "PORT_NAME": "1",
        "PORT_INST_ID": "101202650",
        "PORT_ACCESS_ID": "ET-0/0/96",
        "CONNECTOR_TYPE": "OTHER",
        "FQDN": "WNSLNCPV0QW.CHTRSE.COM",
        "MODEL": "QFX5100-96S",
        "VENDOR": "JUNIPER",
        "TID": "WNSLNCPV0QW",
        "LEGACY_EQUIP_SOURCE": "L-TWC",
        "PURCHASING_GROUP": "ENTERPRISE",
        "IPV4_ADDRESS": "10.20.102.126/24",
        "IPV6_ADDRESS": None,
        "C_VLAN": None,
        "CUST_S_VLAN": None,
        "S_VLAN": None,
        "VLAN_OPERATION": None,
        "PORT_ROLE": None,
        "INITIAL_PATH_NAME": "33.L1XX.006714..TWCC",
        "INITIAL_CIRCUIT_ID": "1334717",
        "LVL": "2",
    },
    {
        "CIRC_PATH_INST_ID": "1128201",
        "PATH_NAME": "33001.GE40L.WNSLNCPV1CW.WNSLNCPV0QW",
        "PATH_REV": "1",
        "PATH_CATEGORY": "ETHERNET TRANSPORT",
        "PATH_A_SITE": "WNSLNCPV-TWC/HUB WS-WINSTON",
        "PATH_Z_SITE": "WNSLNCPV-TWC/HUB WS-WINSTON",
        "A_CLLI": "WNSLNCPV",
        "Z_CLLI": "WNSLNCPV",
        "PATH_A_SITE_TYPE": "HUB",
        "PATH_Z_SITE_TYPE": "HUB",
        "TOPOLOGY": "Point-to-point",
        "PATH_STATUS": "Live",
        "CLASS_OF_SERVICE": None,
        "SLM_ELIGIBILITY": None,
        "EVC_ID": None,
        "SERVICE_TYPE": "INT-EDGE TRANSPORT",
        "BANDWIDTH": "AGGREGATE",
        "BW_SIZE": "0",
        "CUSTOMER_ID": None,
        "CUSTOMER_NAME": None,
        "IPV4_GLUE_SUBNET": None,
        "IPV4_ASSIGNED_SUBNETS": None,
        "IPV4_ASSIGNED_GATEWAY": None,
        "IPV4_SERVICE_TYPE": None,
        "IPV6_GLUE_SUBNET": None,
        "IPV6_ASSIGNED_SUBNETS": None,
        "IPV6_SERVICE_TYPE": None,
        "CUSTOMER_TYPE": None,
        "ORDER_REFERENCE": "2.2.2.",
        "PARENT_SEQUENCE": "2",
        "PARENT_MEMBER_NBR": "2",
        "SEQUENCE": "2",
        "MEMBER_NBR": None,
        "LEG_NAME": "AE17/AE17 80G",
        "LEG_INST_ID": "1313051",
        "A_SITE_NAME": "WNSLNCPV-TWC/HUB WS-WINSTON",
        "Z_SITE_NAME": None,
        "ELEMENT_TYPE": "PORT",
        "ELEMENT_NAME": "WNSLNCPV0QW/001.0004.010.23/SWT#1",
        "ELEMENT_REFERENCE": "895581",
        "ELEMENT_CATEGORY": "SWITCH",
        "ELEMENT_STATUS": "Live",
        "ELEMENT_BANDWIDTH": "40 Gbps",
        "NEXT_PATH_INST_ID": None,
        "PREV_PATH_INST_ID": None,
        "CHAN_NAME": "VLAN1162",
        "CHAN_INST_ID": "7163953",
        "SLOT": "96",
        "PORT_NAME": "1",
        "PORT_INST_ID": "101202795",
        "PORT_ACCESS_ID": "ET-1/0/96",
        "CONNECTOR_TYPE": "OTHER",
        "FQDN": "WNSLNCPV0QW.CHTRSE.COM",
        "MODEL": "QFX5100-96S",
        "VENDOR": "JUNIPER",
        "TID": "WNSLNCPV0QW",
        "LEGACY_EQUIP_SOURCE": "L-TWC",
        "PURCHASING_GROUP": "ENTERPRISE",
        "IPV4_ADDRESS": "10.20.102.126/24",
        "IPV6_ADDRESS": None,
        "C_VLAN": None,
        "CUST_S_VLAN": None,
        "S_VLAN": None,
        "VLAN_OPERATION": None,
        "PORT_ROLE": None,
        "INITIAL_PATH_NAME": "33.L1XX.006714..TWCC",
        "INITIAL_CIRCUIT_ID": "1334717",
        "LVL": "2",
    },
    {
        "CIRC_PATH_INST_ID": "1343761",
        "PATH_NAME": "33001.GE1.WNSLNCPV0QW.WNSLNCKX2ZW",
        "PATH_REV": "1",
        "PATH_CATEGORY": "ETHERNET TRANSPORT",
        "PATH_A_SITE": "WNSLNCPV-TWC/HUB WS-WINSTON",
        "PATH_Z_SITE": "WNSLNCKX-KUEHNE NAGEL//3929 WESTPOINT BLVD",
        "A_CLLI": "WNSLNCPV",
        "Z_CLLI": "WNSLNCKX",
        "PATH_A_SITE_TYPE": "HUB",
        "PATH_Z_SITE_TYPE": "LOCAL",
        "TOPOLOGY": "Point-to-point",
        "PATH_STATUS": "Pending Decommission",
        "CLASS_OF_SERVICE": None,
        "SLM_ELIGIBILITY": None,
        "EVC_ID": None,
        "SERVICE_TYPE": "INT-ACCESS TO PREM TRANSPORT",
        "BANDWIDTH": "1 Gbps",
        "BW_SIZE": "1000000000",
        "CUSTOMER_ID": None,
        "CUSTOMER_NAME": None,
        "IPV4_GLUE_SUBNET": None,
        "IPV4_ASSIGNED_SUBNETS": None,
        "IPV4_ASSIGNED_GATEWAY": None,
        "IPV4_SERVICE_TYPE": None,
        "IPV6_GLUE_SUBNET": None,
        "IPV6_ASSIGNED_SUBNETS": None,
        "IPV6_SERVICE_TYPE": None,
        "CUSTOMER_TYPE": None,
        "ORDER_REFERENCE": "3..1.",
        "PARENT_SEQUENCE": "3",
        "PARENT_MEMBER_NBR": None,
        "SEQUENCE": "1",
        "MEMBER_NBR": None,
        "LEG_NAME": "1",
        "LEG_INST_ID": "1543941",
        "A_SITE_NAME": "WNSLNCPV-TWC/HUB WS-WINSTON",
        "Z_SITE_NAME": None,
        "ELEMENT_TYPE": "PORT",
        "ELEMENT_NAME": "WNSLNCPV0QW/001.0004.010.26/SWT#0",
        "ELEMENT_REFERENCE": "895569",
        "ELEMENT_CATEGORY": "SWITCH",
        "ELEMENT_STATUS": "Live",
        "ELEMENT_BANDWIDTH": "1 Gbps",
        "NEXT_PATH_INST_ID": None,
        "PREV_PATH_INST_ID": None,
        "CHAN_NAME": "VLAN1162",
        "CHAN_INST_ID": "7163952",
        "SLOT": "8",
        "PORT_NAME": "1",
        "PORT_INST_ID": "103833392",
        "PORT_ACCESS_ID": "GE-0/0/8",
        "CONNECTOR_TYPE": "LC",
        "FQDN": "WNSLNCPV0QW.CHTRSE.COM",
        "MODEL": "QFX5100-96S",
        "VENDOR": "JUNIPER",
        "TID": "WNSLNCPV0QW",
        "LEGACY_EQUIP_SOURCE": "L-TWC",
        "PURCHASING_GROUP": "ENTERPRISE",
        "IPV4_ADDRESS": "10.20.102.126/24",
        "IPV6_ADDRESS": None,
        "C_VLAN": None,
        "CUST_S_VLAN": None,
        "S_VLAN": None,
        "VLAN_OPERATION": None,
        "PORT_ROLE": None,
        "INITIAL_PATH_NAME": "33.L1XX.006714..TWCC",
        "INITIAL_CIRCUIT_ID": "1334717",
        "LVL": "2",
    },
    {
        "CIRC_PATH_INST_ID": "1343761",
        "PATH_NAME": "33001.GE1.WNSLNCPV0QW.WNSLNCKX2ZW",
        "PATH_REV": "1",
        "PATH_CATEGORY": "ETHERNET TRANSPORT",
        "PATH_A_SITE": "WNSLNCPV-TWC/HUB WS-WINSTON",
        "PATH_Z_SITE": "WNSLNCKX-KUEHNE NAGEL//3929 WESTPOINT BLVD",
        "A_CLLI": "WNSLNCPV",
        "Z_CLLI": "WNSLNCKX",
        "PATH_A_SITE_TYPE": "HUB",
        "PATH_Z_SITE_TYPE": "LOCAL",
        "TOPOLOGY": "Point-to-point",
        "PATH_STATUS": "Pending Decommission",
        "CLASS_OF_SERVICE": None,
        "SLM_ELIGIBILITY": None,
        "EVC_ID": None,
        "SERVICE_TYPE": "INT-ACCESS TO PREM TRANSPORT",
        "BANDWIDTH": "1 Gbps",
        "BW_SIZE": "1000000000",
        "CUSTOMER_ID": None,
        "CUSTOMER_NAME": None,
        "IPV4_GLUE_SUBNET": None,
        "IPV4_ASSIGNED_SUBNETS": None,
        "IPV4_ASSIGNED_GATEWAY": None,
        "IPV4_SERVICE_TYPE": None,
        "IPV6_GLUE_SUBNET": None,
        "IPV6_ASSIGNED_SUBNETS": None,
        "IPV6_SERVICE_TYPE": None,
        "CUSTOMER_TYPE": None,
        "ORDER_REFERENCE": "3..2.",
        "PARENT_SEQUENCE": "3",
        "PARENT_MEMBER_NBR": None,
        "SEQUENCE": "2",
        "MEMBER_NBR": None,
        "LEG_NAME": "1",
        "LEG_INST_ID": "1543941",
        "A_SITE_NAME": "WNSLNCKX-KUEHNE NAGEL//3929 WESTPOINT BLVD",
        "Z_SITE_NAME": None,
        "ELEMENT_TYPE": "PORT",
        "ELEMENT_NAME": "WNSLNCKX2ZW/999.9999.999.99",
        "ELEMENT_REFERENCE": "1037108",
        "ELEMENT_CATEGORY": "NIU",
        "ELEMENT_STATUS": "Pending Decommission",
        "ELEMENT_BANDWIDTH": "1 Gbps",
        "NEXT_PATH_INST_ID": None,
        "PREV_PATH_INST_ID": None,
        "CHAN_NAME": "VLAN1162",
        "CHAN_INST_ID": "7163952",
        "SLOT": "NET 1",
        "PORT_NAME": "1",
        "PORT_INST_ID": "103833213",
        "PORT_ACCESS_ID": "ETH PORT 1",
        "CONNECTOR_TYPE": "LC",
        "FQDN": "WNSLNCKX2ZW.CML.CHTRSE.COM",
        "MODEL": "ETX203AX/2SFP/2UTP2SFP",
        "VENDOR": "RAD",
        "TID": "WNSLNCKX2ZW",
        "LEGACY_EQUIP_SOURCE": "L-TWC",
        "PURCHASING_GROUP": "ENTERPRISE",
        "IPV4_ADDRESS": "DHCP",
        "IPV6_ADDRESS": None,
        "C_VLAN": None,
        "CUST_S_VLAN": None,
        "S_VLAN": None,
        "VLAN_OPERATION": None,
        "PORT_ROLE": None,
        "INITIAL_PATH_NAME": "33.L1XX.006714..TWCC",
        "INITIAL_CIRCUIT_ID": "1334717",
        "LVL": "2",
    },
]

mock_granite_circuit_devices_bad_service_type = [
    {
        "CIRC_PATH_INST_ID": "1334717",
        "PATH_NAME": "33.L1XX.006714..TWCC",
        "PATH_REV": "1",
        "PATH_CATEGORY": "ETHERNET",
        "PATH_A_SITE": "WNSLNCPV-TWC/HUB WS-WINSTON",
        "PATH_Z_SITE": "WNSLNCKX-KUEHNE NAGEL//3929 WESTPOINT BLVD",
        "A_CLLI": "WNSLNCPV",
        "Z_CLLI": "WNSLNCKX",
        "PATH_A_SITE_TYPE": "HUB",
        "PATH_Z_SITE_TYPE": "LOCAL",
        "TOPOLOGY": "Point-to-point",
        "PATH_STATUS": "Pending Decommission",
        "CLASS_OF_SERVICE": None,
        "SLM_ELIGIBILITY": "ELIGIBLE DESIGN",
        "EVC_ID": None,
        "SERVICE_TYPE": None,
        "BANDWIDTH": "25 Mbps",
        "BW_SIZE": "25000000",
        "CUSTOMER_ID": "ACCT-04400732",
        "CUSTOMER_NAME": "MASSCOMM",
        "IPV4_GLUE_SUBNET": None,
        "IPV4_ASSIGNED_SUBNETS": "173.95.101.40",
        "IPV4_ASSIGNED_GATEWAY": "173.95.101.41",
        "IPV4_SERVICE_TYPE": "LAN",
        "IPV6_GLUE_SUBNET": "2606:A000:0:8::F:3096/127",
        "IPV6_ASSIGNED_SUBNETS": "2600:5800:8C6::/48",
        "IPV6_SERVICE_TYPE": "ROUTED",
        "CUSTOMER_TYPE": "CARRIER ACCESS",
        "ORDER_REFERENCE": "4.",
        "PARENT_SEQUENCE": None,
        "PARENT_MEMBER_NBR": None,
        "SEQUENCE": "4",
        "MEMBER_NBR": None,
        "LEG_NAME": "1",
        "LEG_INST_ID": "1533950",
        "A_SITE_NAME": "WNSLNCKX-KUEHNE NAGEL//3929 WESTPOINT BLVD",
        "Z_SITE_NAME": None,
        "ELEMENT_TYPE": "PORT",
        "ELEMENT_NAME": "WNSLNCKX2ZW/999.9999.999.99",
        "ELEMENT_REFERENCE": "1037108",
        "ELEMENT_CATEGORY": "NIU",
        "ELEMENT_STATUS": "Pending Decommission",
        "ELEMENT_BANDWIDTH": "10/100/1000 BASET",
        "NEXT_PATH_INST_ID": None,
        "PREV_PATH_INST_ID": None,
        "CHAN_NAME": None,
        "CHAN_INST_ID": None,
        "SLOT": "FIXED PORTS",
        "PORT_NAME": "USER 3",
        "PORT_INST_ID": "103833216",
        "PORT_ACCESS_ID": "ETH PORT 3",
        "CONNECTOR_TYPE": "RJ-45",
        "FQDN": "WNSLNCKX2ZW.CML.CHTRSE.COM",
        "MODEL": "ETX203AX/2SFP/2UTP2SFP",
        "VENDOR": "RAD",
        "TID": "WNSLNCKX2ZW",
        "LEGACY_EQUIP_SOURCE": "L-TWC",
        "PURCHASING_GROUP": "ENTERPRISE",
        "IPV4_ADDRESS": "DHCP",
        "IPV6_ADDRESS": None,
        "C_VLAN": None,
        "CUST_S_VLAN": None,
        "S_VLAN": "1162",
        "VLAN_OPERATION": "PUSH",
        "PORT_ROLE": "UNI-EP",
        "INITIAL_PATH_NAME": "33.L1XX.006714..TWCC",
        "INITIAL_CIRCUIT_ID": "1334717",
        "LVL": "1",
    },
    {
        "CIRC_PATH_INST_ID": "1128201",
        "PATH_NAME": "33001.GE40L.WNSLNCPV1CW.WNSLNCPV0QW",
        "PATH_REV": "1",
        "PATH_CATEGORY": "ETHERNET TRANSPORT",
        "PATH_A_SITE": "WNSLNCPV-TWC/HUB WS-WINSTON",
        "PATH_Z_SITE": "WNSLNCPV-TWC/HUB WS-WINSTON",
        "A_CLLI": "WNSLNCPV",
        "Z_CLLI": "WNSLNCPV",
        "PATH_A_SITE_TYPE": "HUB",
        "PATH_Z_SITE_TYPE": "HUB",
        "TOPOLOGY": "Point-to-point",
        "PATH_STATUS": "Live",
        "CLASS_OF_SERVICE": None,
        "SLM_ELIGIBILITY": None,
        "EVC_ID": None,
        "SERVICE_TYPE": "INT-EDGE TRANSPORT",
        "BANDWIDTH": "AGGREGATE",
        "BW_SIZE": "0",
        "CUSTOMER_ID": None,
        "CUSTOMER_NAME": None,
        "IPV4_GLUE_SUBNET": None,
        "IPV4_ASSIGNED_SUBNETS": None,
        "IPV4_ASSIGNED_GATEWAY": None,
        "IPV4_SERVICE_TYPE": None,
        "IPV6_GLUE_SUBNET": None,
        "IPV6_ASSIGNED_SUBNETS": None,
        "IPV6_SERVICE_TYPE": None,
        "CUSTOMER_TYPE": None,
        "ORDER_REFERENCE": "2.1.1.",
        "PARENT_SEQUENCE": "2",
        "PARENT_MEMBER_NBR": "1",
        "SEQUENCE": "1",
        "MEMBER_NBR": None,
        "LEG_NAME": "AE17/AE17 80G",
        "LEG_INST_ID": "1313051",
        "A_SITE_NAME": "WNSLNCPV-TWC/HUB WS-WINSTON",
        "Z_SITE_NAME": None,
        "ELEMENT_TYPE": "PORT",
        "ELEMENT_NAME": "WNSLNCPV1CW/001.0001.102.11/RTR",
        "ELEMENT_REFERENCE": "514200",
        "ELEMENT_CATEGORY": "ROUTER",
        "ELEMENT_STATUS": "Live",
        "ELEMENT_BANDWIDTH": "40 Gbps",
        "NEXT_PATH_INST_ID": None,
        "PREV_PATH_INST_ID": None,
        "CHAN_NAME": "VLAN1162",
        "CHAN_INST_ID": "7163953",
        "SLOT": "3/0",
        "PORT_NAME": "1",
        "PORT_INST_ID": "103005919",
        "PORT_ACCESS_ID": "ET-4/3/0",
        "CONNECTOR_TYPE": "OTHER",
        "FQDN": "WNSLNCPV1CW.CHTRSE.COM",
        "MODEL": "MX960",
        "VENDOR": "JUNIPER",
        "TID": "WNSLNCPV1CW",
        "LEGACY_EQUIP_SOURCE": "L-TWC",
        "PURCHASING_GROUP": "ENTERPRISE",
        "IPV4_ADDRESS": "24.199.192.102/32",
        "IPV6_ADDRESS": "2606:A000::F:66/128",
        "C_VLAN": None,
        "CUST_S_VLAN": None,
        "S_VLAN": None,
        "VLAN_OPERATION": None,
        "PORT_ROLE": None,
        "INITIAL_PATH_NAME": "33.L1XX.006714..TWCC",
        "INITIAL_CIRCUIT_ID": "1334717",
        "LVL": "2",
    },
    {
        "CIRC_PATH_INST_ID": "1128201",
        "PATH_NAME": "33001.GE40L.WNSLNCPV1CW.WNSLNCPV0QW",
        "PATH_REV": "1",
        "PATH_CATEGORY": "ETHERNET TRANSPORT",
        "PATH_A_SITE": "WNSLNCPV-TWC/HUB WS-WINSTON",
        "PATH_Z_SITE": "WNSLNCPV-TWC/HUB WS-WINSTON",
        "A_CLLI": "WNSLNCPV",
        "Z_CLLI": "WNSLNCPV",
        "PATH_A_SITE_TYPE": "HUB",
        "PATH_Z_SITE_TYPE": "HUB",
        "TOPOLOGY": "Point-to-point",
        "PATH_STATUS": "Live",
        "CLASS_OF_SERVICE": None,
        "SLM_ELIGIBILITY": None,
        "EVC_ID": None,
        "SERVICE_TYPE": "INT-EDGE TRANSPORT",
        "BANDWIDTH": "AGGREGATE",
        "BW_SIZE": "0",
        "CUSTOMER_ID": None,
        "CUSTOMER_NAME": None,
        "IPV4_GLUE_SUBNET": None,
        "IPV4_ASSIGNED_SUBNETS": None,
        "IPV4_ASSIGNED_GATEWAY": None,
        "IPV4_SERVICE_TYPE": None,
        "IPV6_GLUE_SUBNET": None,
        "IPV6_ASSIGNED_SUBNETS": None,
        "IPV6_SERVICE_TYPE": None,
        "CUSTOMER_TYPE": None,
        "ORDER_REFERENCE": "2.1.2.",
        "PARENT_SEQUENCE": "2",
        "PARENT_MEMBER_NBR": "1",
        "SEQUENCE": "2",
        "MEMBER_NBR": None,
        "LEG_NAME": "AE17/AE17 80G",
        "LEG_INST_ID": "1313051",
        "A_SITE_NAME": "WNSLNCPV-TWC/HUB WS-WINSTON",
        "Z_SITE_NAME": None,
        "ELEMENT_TYPE": "PORT",
        "ELEMENT_NAME": "WNSLNCPV1CW/001.0001.102.11/RTR",
        "ELEMENT_REFERENCE": "514200",
        "ELEMENT_CATEGORY": "ROUTER",
        "ELEMENT_STATUS": "Live",
        "ELEMENT_BANDWIDTH": "40 Gbps",
        "NEXT_PATH_INST_ID": None,
        "PREV_PATH_INST_ID": None,
        "CHAN_NAME": "VLAN1162",
        "CHAN_INST_ID": "7163953",
        "SLOT": "3/0",
        "PORT_NAME": "1",
        "PORT_INST_ID": "103005944",
        "PORT_ACCESS_ID": "ET-8/3/0",
        "CONNECTOR_TYPE": "OTHER",
        "FQDN": "WNSLNCPV1CW.CHTRSE.COM",
        "MODEL": "MX960",
        "VENDOR": "JUNIPER",
        "TID": "WNSLNCPV1CW",
        "LEGACY_EQUIP_SOURCE": "L-TWC",
        "PURCHASING_GROUP": "ENTERPRISE",
        "IPV4_ADDRESS": "24.199.192.102/32",
        "IPV6_ADDRESS": "2606:A000::F:66/128",
        "C_VLAN": None,
        "CUST_S_VLAN": None,
        "S_VLAN": None,
        "VLAN_OPERATION": None,
        "PORT_ROLE": None,
        "INITIAL_PATH_NAME": "33.L1XX.006714..TWCC",
        "INITIAL_CIRCUIT_ID": "1334717",
        "LVL": "2",
    },
    {
        "CIRC_PATH_INST_ID": "1128201",
        "PATH_NAME": "33001.GE40L.WNSLNCPV1CW.WNSLNCPV0QW",
        "PATH_REV": "1",
        "PATH_CATEGORY": "ETHERNET TRANSPORT",
        "PATH_A_SITE": "WNSLNCPV-TWC/HUB WS-WINSTON",
        "PATH_Z_SITE": "WNSLNCPV-TWC/HUB WS-WINSTON",
        "A_CLLI": "WNSLNCPV",
        "Z_CLLI": "WNSLNCPV",
        "PATH_A_SITE_TYPE": "HUB",
        "PATH_Z_SITE_TYPE": "HUB",
        "TOPOLOGY": "Point-to-point",
        "PATH_STATUS": "Live",
        "CLASS_OF_SERVICE": None,
        "SLM_ELIGIBILITY": None,
        "EVC_ID": None,
        "SERVICE_TYPE": "INT-EDGE TRANSPORT",
        "BANDWIDTH": "AGGREGATE",
        "BW_SIZE": "0",
        "CUSTOMER_ID": None,
        "CUSTOMER_NAME": None,
        "IPV4_GLUE_SUBNET": None,
        "IPV4_ASSIGNED_SUBNETS": None,
        "IPV4_ASSIGNED_GATEWAY": None,
        "IPV4_SERVICE_TYPE": None,
        "IPV6_GLUE_SUBNET": None,
        "IPV6_ASSIGNED_SUBNETS": None,
        "IPV6_SERVICE_TYPE": None,
        "CUSTOMER_TYPE": None,
        "ORDER_REFERENCE": "2.2.1.",
        "PARENT_SEQUENCE": "2",
        "PARENT_MEMBER_NBR": "2",
        "SEQUENCE": "1",
        "MEMBER_NBR": None,
        "LEG_NAME": "AE17/AE17 80G",
        "LEG_INST_ID": "1313051",
        "A_SITE_NAME": "WNSLNCPV-TWC/HUB WS-WINSTON",
        "Z_SITE_NAME": None,
        "ELEMENT_TYPE": "PORT",
        "ELEMENT_NAME": "WNSLNCPV0QW/001.0004.010.26/SWT#0",
        "ELEMENT_REFERENCE": "895569",
        "ELEMENT_CATEGORY": "SWITCH",
        "ELEMENT_STATUS": "Live",
        "ELEMENT_BANDWIDTH": "40 Gbps",
        "NEXT_PATH_INST_ID": None,
        "PREV_PATH_INST_ID": None,
        "CHAN_NAME": "VLAN1162",
        "CHAN_INST_ID": "7163953",
        "SLOT": "96",
        "PORT_NAME": "1",
        "PORT_INST_ID": "101202650",
        "PORT_ACCESS_ID": "ET-0/0/96",
        "CONNECTOR_TYPE": "OTHER",
        "FQDN": "WNSLNCPV0QW.CHTRSE.COM",
        "MODEL": "QFX5100-96S",
        "VENDOR": "JUNIPER",
        "TID": "WNSLNCPV0QW",
        "LEGACY_EQUIP_SOURCE": "L-TWC",
        "PURCHASING_GROUP": "ENTERPRISE",
        "IPV4_ADDRESS": "10.20.102.126/24",
        "IPV6_ADDRESS": None,
        "C_VLAN": None,
        "CUST_S_VLAN": None,
        "S_VLAN": None,
        "VLAN_OPERATION": None,
        "PORT_ROLE": None,
        "INITIAL_PATH_NAME": "33.L1XX.006714..TWCC",
        "INITIAL_CIRCUIT_ID": "1334717",
        "LVL": "2",
    },
    {
        "CIRC_PATH_INST_ID": "1128201",
        "PATH_NAME": "33001.GE40L.WNSLNCPV1CW.WNSLNCPV0QW",
        "PATH_REV": "1",
        "PATH_CATEGORY": "ETHERNET TRANSPORT",
        "PATH_A_SITE": "WNSLNCPV-TWC/HUB WS-WINSTON",
        "PATH_Z_SITE": "WNSLNCPV-TWC/HUB WS-WINSTON",
        "A_CLLI": "WNSLNCPV",
        "Z_CLLI": "WNSLNCPV",
        "PATH_A_SITE_TYPE": "HUB",
        "PATH_Z_SITE_TYPE": "HUB",
        "TOPOLOGY": "Point-to-point",
        "PATH_STATUS": "Live",
        "CLASS_OF_SERVICE": None,
        "SLM_ELIGIBILITY": None,
        "EVC_ID": None,
        "SERVICE_TYPE": "INT-EDGE TRANSPORT",
        "BANDWIDTH": "AGGREGATE",
        "BW_SIZE": "0",
        "CUSTOMER_ID": None,
        "CUSTOMER_NAME": None,
        "IPV4_GLUE_SUBNET": None,
        "IPV4_ASSIGNED_SUBNETS": None,
        "IPV4_ASSIGNED_GATEWAY": None,
        "IPV4_SERVICE_TYPE": None,
        "IPV6_GLUE_SUBNET": None,
        "IPV6_ASSIGNED_SUBNETS": None,
        "IPV6_SERVICE_TYPE": None,
        "CUSTOMER_TYPE": None,
        "ORDER_REFERENCE": "2.2.2.",
        "PARENT_SEQUENCE": "2",
        "PARENT_MEMBER_NBR": "2",
        "SEQUENCE": "2",
        "MEMBER_NBR": None,
        "LEG_NAME": "AE17/AE17 80G",
        "LEG_INST_ID": "1313051",
        "A_SITE_NAME": "WNSLNCPV-TWC/HUB WS-WINSTON",
        "Z_SITE_NAME": None,
        "ELEMENT_TYPE": "PORT",
        "ELEMENT_NAME": "WNSLNCPV0QW/001.0004.010.23/SWT#1",
        "ELEMENT_REFERENCE": "895581",
        "ELEMENT_CATEGORY": "SWITCH",
        "ELEMENT_STATUS": "Live",
        "ELEMENT_BANDWIDTH": "40 Gbps",
        "NEXT_PATH_INST_ID": None,
        "PREV_PATH_INST_ID": None,
        "CHAN_NAME": "VLAN1162",
        "CHAN_INST_ID": "7163953",
        "SLOT": "96",
        "PORT_NAME": "1",
        "PORT_INST_ID": "101202795",
        "PORT_ACCESS_ID": "ET-1/0/96",
        "CONNECTOR_TYPE": "OTHER",
        "FQDN": "WNSLNCPV0QW.CHTRSE.COM",
        "MODEL": "QFX5100-96S",
        "VENDOR": "JUNIPER",
        "TID": "WNSLNCPV0QW",
        "LEGACY_EQUIP_SOURCE": "L-TWC",
        "PURCHASING_GROUP": "ENTERPRISE",
        "IPV4_ADDRESS": "10.20.102.126/24",
        "IPV6_ADDRESS": None,
        "C_VLAN": None,
        "CUST_S_VLAN": None,
        "S_VLAN": None,
        "VLAN_OPERATION": None,
        "PORT_ROLE": None,
        "INITIAL_PATH_NAME": "33.L1XX.006714..TWCC",
        "INITIAL_CIRCUIT_ID": "1334717",
        "LVL": "2",
    },
    {
        "CIRC_PATH_INST_ID": "1343761",
        "PATH_NAME": "33001.GE1.WNSLNCPV0QW.WNSLNCKX2ZW",
        "PATH_REV": "1",
        "PATH_CATEGORY": "ETHERNET TRANSPORT",
        "PATH_A_SITE": "WNSLNCPV-TWC/HUB WS-WINSTON",
        "PATH_Z_SITE": "WNSLNCKX-KUEHNE NAGEL//3929 WESTPOINT BLVD",
        "A_CLLI": "WNSLNCPV",
        "Z_CLLI": "WNSLNCKX",
        "PATH_A_SITE_TYPE": "HUB",
        "PATH_Z_SITE_TYPE": "LOCAL",
        "TOPOLOGY": "Point-to-point",
        "PATH_STATUS": "Pending Decommission",
        "CLASS_OF_SERVICE": None,
        "SLM_ELIGIBILITY": None,
        "EVC_ID": None,
        "SERVICE_TYPE": "INT-ACCESS TO PREM TRANSPORT",
        "BANDWIDTH": "1 Gbps",
        "BW_SIZE": "1000000000",
        "CUSTOMER_ID": None,
        "CUSTOMER_NAME": None,
        "IPV4_GLUE_SUBNET": None,
        "IPV4_ASSIGNED_SUBNETS": None,
        "IPV4_ASSIGNED_GATEWAY": None,
        "IPV4_SERVICE_TYPE": None,
        "IPV6_GLUE_SUBNET": None,
        "IPV6_ASSIGNED_SUBNETS": None,
        "IPV6_SERVICE_TYPE": None,
        "CUSTOMER_TYPE": None,
        "ORDER_REFERENCE": "3..1.",
        "PARENT_SEQUENCE": "3",
        "PARENT_MEMBER_NBR": None,
        "SEQUENCE": "1",
        "MEMBER_NBR": None,
        "LEG_NAME": "1",
        "LEG_INST_ID": "1543941",
        "A_SITE_NAME": "WNSLNCPV-TWC/HUB WS-WINSTON",
        "Z_SITE_NAME": None,
        "ELEMENT_TYPE": "PORT",
        "ELEMENT_NAME": "WNSLNCPV0QW/001.0004.010.26/SWT#0",
        "ELEMENT_REFERENCE": "895569",
        "ELEMENT_CATEGORY": "SWITCH",
        "ELEMENT_STATUS": "Live",
        "ELEMENT_BANDWIDTH": "1 Gbps",
        "NEXT_PATH_INST_ID": None,
        "PREV_PATH_INST_ID": None,
        "CHAN_NAME": "VLAN1162",
        "CHAN_INST_ID": "7163952",
        "SLOT": "8",
        "PORT_NAME": "1",
        "PORT_INST_ID": "103833392",
        "PORT_ACCESS_ID": "GE-0/0/8",
        "CONNECTOR_TYPE": "LC",
        "FQDN": "WNSLNCPV0QW.CHTRSE.COM",
        "MODEL": "QFX5100-96S",
        "VENDOR": "JUNIPER",
        "TID": "WNSLNCPV0QW",
        "LEGACY_EQUIP_SOURCE": "L-TWC",
        "PURCHASING_GROUP": "ENTERPRISE",
        "IPV4_ADDRESS": "10.20.102.126/24",
        "IPV6_ADDRESS": None,
        "C_VLAN": None,
        "CUST_S_VLAN": None,
        "S_VLAN": None,
        "VLAN_OPERATION": None,
        "PORT_ROLE": None,
        "INITIAL_PATH_NAME": "33.L1XX.006714..TWCC",
        "INITIAL_CIRCUIT_ID": "1334717",
        "LVL": "2",
    },
    {
        "CIRC_PATH_INST_ID": "1343761",
        "PATH_NAME": "33001.GE1.WNSLNCPV0QW.WNSLNCKX2ZW",
        "PATH_REV": "1",
        "PATH_CATEGORY": "ETHERNET TRANSPORT",
        "PATH_A_SITE": "WNSLNCPV-TWC/HUB WS-WINSTON",
        "PATH_Z_SITE": "WNSLNCKX-KUEHNE NAGEL//3929 WESTPOINT BLVD",
        "A_CLLI": "WNSLNCPV",
        "Z_CLLI": "WNSLNCKX",
        "PATH_A_SITE_TYPE": "HUB",
        "PATH_Z_SITE_TYPE": "LOCAL",
        "TOPOLOGY": "Point-to-point",
        "PATH_STATUS": "Pending Decommission",
        "CLASS_OF_SERVICE": None,
        "SLM_ELIGIBILITY": None,
        "EVC_ID": None,
        "SERVICE_TYPE": "INT-ACCESS TO PREM TRANSPORT",
        "BANDWIDTH": "1 Gbps",
        "BW_SIZE": "1000000000",
        "CUSTOMER_ID": None,
        "CUSTOMER_NAME": None,
        "IPV4_GLUE_SUBNET": None,
        "IPV4_ASSIGNED_SUBNETS": None,
        "IPV4_ASSIGNED_GATEWAY": None,
        "IPV4_SERVICE_TYPE": None,
        "IPV6_GLUE_SUBNET": None,
        "IPV6_ASSIGNED_SUBNETS": None,
        "IPV6_SERVICE_TYPE": None,
        "CUSTOMER_TYPE": None,
        "ORDER_REFERENCE": "3..2.",
        "PARENT_SEQUENCE": "3",
        "PARENT_MEMBER_NBR": None,
        "SEQUENCE": "2",
        "MEMBER_NBR": None,
        "LEG_NAME": "1",
        "LEG_INST_ID": "1543941",
        "A_SITE_NAME": "WNSLNCKX-KUEHNE NAGEL//3929 WESTPOINT BLVD",
        "Z_SITE_NAME": None,
        "ELEMENT_TYPE": "PORT",
        "ELEMENT_NAME": "WNSLNCKX2ZW/999.9999.999.99",
        "ELEMENT_REFERENCE": "1037108",
        "ELEMENT_CATEGORY": "NIU",
        "ELEMENT_STATUS": "Pending Decommission",
        "ELEMENT_BANDWIDTH": "1 Gbps",
        "NEXT_PATH_INST_ID": None,
        "PREV_PATH_INST_ID": None,
        "CHAN_NAME": "VLAN1162",
        "CHAN_INST_ID": "7163952",
        "SLOT": "NET 1",
        "PORT_NAME": "1",
        "PORT_INST_ID": "103833213",
        "PORT_ACCESS_ID": "ETH PORT 1",
        "CONNECTOR_TYPE": "LC",
        "FQDN": "WNSLNCKX2ZW.CML.CHTRSE.COM",
        "MODEL": "ETX203AX/2SFP/2UTP2SFP",
        "VENDOR": "RAD",
        "TID": "WNSLNCKX2ZW",
        "LEGACY_EQUIP_SOURCE": "L-TWC",
        "PURCHASING_GROUP": "ENTERPRISE",
        "IPV4_ADDRESS": "DHCP",
        "IPV6_ADDRESS": None,
        "C_VLAN": None,
        "CUST_S_VLAN": None,
        "S_VLAN": None,
        "VLAN_OPERATION": None,
        "PORT_ROLE": None,
        "INITIAL_PATH_NAME": "33.L1XX.006714..TWCC",
        "INITIAL_CIRCUIT_ID": "1334717",
        "LVL": "2",
    },
]

mock_granite_circuit_devices_bad_inital_cid = [
    {
        "CIRC_PATH_INST_ID": "1334717",
        "PATH_NAME": "33.L1XX.006714..TWCC",
        "PATH_REV": "1",
        "PATH_CATEGORY": "ETHERNET",
        "PATH_A_SITE": "WNSLNCPV-TWC/HUB WS-WINSTON",
        "PATH_Z_SITE": "WNSLNCKX-KUEHNE NAGEL//3929 WESTPOINT BLVD",
        "A_CLLI": "WNSLNCPV",
        "Z_CLLI": "WNSLNCKX",
        "PATH_A_SITE_TYPE": "HUB",
        "PATH_Z_SITE_TYPE": "LOCAL",
        "TOPOLOGY": "Point-to-point",
        "PATH_STATUS": "Pending Decommission",
        "CLASS_OF_SERVICE": None,
        "SLM_ELIGIBILITY": "ELIGIBLE DESIGN",
        "EVC_ID": None,
        "SERVICE_TYPE": "CAR-DIA",
        "BANDWIDTH": "25 Mbps",
        "BW_SIZE": "25000000",
        "CUSTOMER_ID": "ACCT-04400732",
        "CUSTOMER_NAME": "MASSCOMM",
        "IPV4_GLUE_SUBNET": None,
        "IPV4_ASSIGNED_SUBNETS": "173.95.101.40",
        "IPV4_ASSIGNED_GATEWAY": "173.95.101.41",
        "IPV4_SERVICE_TYPE": "LAN",
        "IPV6_GLUE_SUBNET": "2606:A000:0:8::F:3096/127",
        "IPV6_ASSIGNED_SUBNETS": "2600:5800:8C6::/48",
        "IPV6_SERVICE_TYPE": "ROUTED",
        "CUSTOMER_TYPE": "CARRIER ACCESS",
        "ORDER_REFERENCE": "4.",
        "PARENT_SEQUENCE": None,
        "PARENT_MEMBER_NBR": None,
        "SEQUENCE": "4",
        "MEMBER_NBR": None,
        "LEG_NAME": "1",
        "LEG_INST_ID": "1533950",
        "A_SITE_NAME": "WNSLNCKX-KUEHNE NAGEL//3929 WESTPOINT BLVD",
        "Z_SITE_NAME": None,
        "ELEMENT_TYPE": "PORT",
        "ELEMENT_NAME": "WNSLNCKX2ZW/999.9999.999.99",
        "ELEMENT_REFERENCE": "1037108",
        "ELEMENT_CATEGORY": "NIU",
        "ELEMENT_STATUS": "Pending Decommission",
        "ELEMENT_BANDWIDTH": "10/100/1000 BASET",
        "NEXT_PATH_INST_ID": None,
        "PREV_PATH_INST_ID": None,
        "CHAN_NAME": None,
        "CHAN_INST_ID": None,
        "SLOT": "FIXED PORTS",
        "PORT_NAME": "USER 3",
        "PORT_INST_ID": "103833216",
        "PORT_ACCESS_ID": "ETH PORT 3",
        "CONNECTOR_TYPE": "RJ-45",
        "FQDN": "WNSLNCKX2ZW.CML.CHTRSE.COM",
        "MODEL": "ETX203AX/2SFP/2UTP2SFP",
        "VENDOR": "RAD",
        "TID": "WNSLNCKX2ZW",
        "LEGACY_EQUIP_SOURCE": "L-TWC",
        "PURCHASING_GROUP": "ENTERPRISE",
        "IPV4_ADDRESS": "DHCP",
        "IPV6_ADDRESS": None,
        "C_VLAN": None,
        "CUST_S_VLAN": None,
        "S_VLAN": "1162",
        "VLAN_OPERATION": "PUSH",
        "PORT_ROLE": "UNI-EP",
        "INITIAL_PATH_NAME": "33.L1XX.006714..TWCC",
        "INITIAL_CIRCUIT_ID": None,
        "LVL": "1",
    },
    {
        "CIRC_PATH_INST_ID": "1128201",
        "PATH_NAME": "33001.GE40L.WNSLNCPV1CW.WNSLNCPV0QW",
        "PATH_REV": "1",
        "PATH_CATEGORY": "ETHERNET TRANSPORT",
        "PATH_A_SITE": "WNSLNCPV-TWC/HUB WS-WINSTON",
        "PATH_Z_SITE": "WNSLNCPV-TWC/HUB WS-WINSTON",
        "A_CLLI": "WNSLNCPV",
        "Z_CLLI": "WNSLNCPV",
        "PATH_A_SITE_TYPE": "HUB",
        "PATH_Z_SITE_TYPE": "HUB",
        "TOPOLOGY": "Point-to-point",
        "PATH_STATUS": "Live",
        "CLASS_OF_SERVICE": None,
        "SLM_ELIGIBILITY": None,
        "EVC_ID": None,
        "SERVICE_TYPE": "INT-EDGE TRANSPORT",
        "BANDWIDTH": "AGGREGATE",
        "BW_SIZE": "0",
        "CUSTOMER_ID": None,
        "CUSTOMER_NAME": None,
        "IPV4_GLUE_SUBNET": None,
        "IPV4_ASSIGNED_SUBNETS": None,
        "IPV4_ASSIGNED_GATEWAY": None,
        "IPV4_SERVICE_TYPE": None,
        "IPV6_GLUE_SUBNET": None,
        "IPV6_ASSIGNED_SUBNETS": None,
        "IPV6_SERVICE_TYPE": None,
        "CUSTOMER_TYPE": None,
        "ORDER_REFERENCE": "2.1.1.",
        "PARENT_SEQUENCE": "2",
        "PARENT_MEMBER_NBR": "1",
        "SEQUENCE": "1",
        "MEMBER_NBR": None,
        "LEG_NAME": "AE17/AE17 80G",
        "LEG_INST_ID": "1313051",
        "A_SITE_NAME": "WNSLNCPV-TWC/HUB WS-WINSTON",
        "Z_SITE_NAME": None,
        "ELEMENT_TYPE": "PORT",
        "ELEMENT_NAME": "WNSLNCPV1CW/001.0001.102.11/RTR",
        "ELEMENT_REFERENCE": "514200",
        "ELEMENT_CATEGORY": "ROUTER",
        "ELEMENT_STATUS": "Live",
        "ELEMENT_BANDWIDTH": "40 Gbps",
        "NEXT_PATH_INST_ID": None,
        "PREV_PATH_INST_ID": None,
        "CHAN_NAME": "VLAN1162",
        "CHAN_INST_ID": "7163953",
        "SLOT": "3/0",
        "PORT_NAME": "1",
        "PORT_INST_ID": "103005919",
        "PORT_ACCESS_ID": "ET-4/3/0",
        "CONNECTOR_TYPE": "OTHER",
        "FQDN": "WNSLNCPV1CW.CHTRSE.COM",
        "MODEL": "MX960",
        "VENDOR": "JUNIPER",
        "TID": "WNSLNCPV1CW",
        "LEGACY_EQUIP_SOURCE": "L-TWC",
        "PURCHASING_GROUP": "ENTERPRISE",
        "IPV4_ADDRESS": "24.199.192.102/32",
        "IPV6_ADDRESS": "2606:A000::F:66/128",
        "C_VLAN": None,
        "CUST_S_VLAN": None,
        "S_VLAN": None,
        "VLAN_OPERATION": None,
        "PORT_ROLE": None,
        "INITIAL_PATH_NAME": "33.L1XX.006714..TWCC",
        "INITIAL_CIRCUIT_ID": None,
        "LVL": "2",
    },
    {
        "CIRC_PATH_INST_ID": "1128201",
        "PATH_NAME": "33001.GE40L.WNSLNCPV1CW.WNSLNCPV0QW",
        "PATH_REV": "1",
        "PATH_CATEGORY": "ETHERNET TRANSPORT",
        "PATH_A_SITE": "WNSLNCPV-TWC/HUB WS-WINSTON",
        "PATH_Z_SITE": "WNSLNCPV-TWC/HUB WS-WINSTON",
        "A_CLLI": "WNSLNCPV",
        "Z_CLLI": "WNSLNCPV",
        "PATH_A_SITE_TYPE": "HUB",
        "PATH_Z_SITE_TYPE": "HUB",
        "TOPOLOGY": "Point-to-point",
        "PATH_STATUS": "Live",
        "CLASS_OF_SERVICE": None,
        "SLM_ELIGIBILITY": None,
        "EVC_ID": None,
        "SERVICE_TYPE": "INT-EDGE TRANSPORT",
        "BANDWIDTH": "AGGREGATE",
        "BW_SIZE": "0",
        "CUSTOMER_ID": None,
        "CUSTOMER_NAME": None,
        "IPV4_GLUE_SUBNET": None,
        "IPV4_ASSIGNED_SUBNETS": None,
        "IPV4_ASSIGNED_GATEWAY": None,
        "IPV4_SERVICE_TYPE": None,
        "IPV6_GLUE_SUBNET": None,
        "IPV6_ASSIGNED_SUBNETS": None,
        "IPV6_SERVICE_TYPE": None,
        "CUSTOMER_TYPE": None,
        "ORDER_REFERENCE": "2.1.2.",
        "PARENT_SEQUENCE": "2",
        "PARENT_MEMBER_NBR": "1",
        "SEQUENCE": "2",
        "MEMBER_NBR": None,
        "LEG_NAME": "AE17/AE17 80G",
        "LEG_INST_ID": "1313051",
        "A_SITE_NAME": "WNSLNCPV-TWC/HUB WS-WINSTON",
        "Z_SITE_NAME": None,
        "ELEMENT_TYPE": "PORT",
        "ELEMENT_NAME": "WNSLNCPV1CW/001.0001.102.11/RTR",
        "ELEMENT_REFERENCE": "514200",
        "ELEMENT_CATEGORY": "ROUTER",
        "ELEMENT_STATUS": "Live",
        "ELEMENT_BANDWIDTH": "40 Gbps",
        "NEXT_PATH_INST_ID": None,
        "PREV_PATH_INST_ID": None,
        "CHAN_NAME": "VLAN1162",
        "CHAN_INST_ID": "7163953",
        "SLOT": "3/0",
        "PORT_NAME": "1",
        "PORT_INST_ID": "103005944",
        "PORT_ACCESS_ID": "ET-8/3/0",
        "CONNECTOR_TYPE": "OTHER",
        "FQDN": "WNSLNCPV1CW.CHTRSE.COM",
        "MODEL": "MX960",
        "VENDOR": "JUNIPER",
        "TID": "WNSLNCPV1CW",
        "LEGACY_EQUIP_SOURCE": "L-TWC",
        "PURCHASING_GROUP": "ENTERPRISE",
        "IPV4_ADDRESS": "24.199.192.102/32",
        "IPV6_ADDRESS": "2606:A000::F:66/128",
        "C_VLAN": None,
        "CUST_S_VLAN": None,
        "S_VLAN": None,
        "VLAN_OPERATION": None,
        "PORT_ROLE": None,
        "INITIAL_PATH_NAME": "33.L1XX.006714..TWCC",
        "INITIAL_CIRCUIT_ID": None,
        "LVL": "2",
    },
    {
        "CIRC_PATH_INST_ID": "1128201",
        "PATH_NAME": "33001.GE40L.WNSLNCPV1CW.WNSLNCPV0QW",
        "PATH_REV": "1",
        "PATH_CATEGORY": "ETHERNET TRANSPORT",
        "PATH_A_SITE": "WNSLNCPV-TWC/HUB WS-WINSTON",
        "PATH_Z_SITE": "WNSLNCPV-TWC/HUB WS-WINSTON",
        "A_CLLI": "WNSLNCPV",
        "Z_CLLI": "WNSLNCPV",
        "PATH_A_SITE_TYPE": "HUB",
        "PATH_Z_SITE_TYPE": "HUB",
        "TOPOLOGY": "Point-to-point",
        "PATH_STATUS": "Live",
        "CLASS_OF_SERVICE": None,
        "SLM_ELIGIBILITY": None,
        "EVC_ID": None,
        "SERVICE_TYPE": "INT-EDGE TRANSPORT",
        "BANDWIDTH": "AGGREGATE",
        "BW_SIZE": "0",
        "CUSTOMER_ID": None,
        "CUSTOMER_NAME": None,
        "IPV4_GLUE_SUBNET": None,
        "IPV4_ASSIGNED_SUBNETS": None,
        "IPV4_ASSIGNED_GATEWAY": None,
        "IPV4_SERVICE_TYPE": None,
        "IPV6_GLUE_SUBNET": None,
        "IPV6_ASSIGNED_SUBNETS": None,
        "IPV6_SERVICE_TYPE": None,
        "CUSTOMER_TYPE": None,
        "ORDER_REFERENCE": "2.2.1.",
        "PARENT_SEQUENCE": "2",
        "PARENT_MEMBER_NBR": "2",
        "SEQUENCE": "1",
        "MEMBER_NBR": None,
        "LEG_NAME": "AE17/AE17 80G",
        "LEG_INST_ID": "1313051",
        "A_SITE_NAME": "WNSLNCPV-TWC/HUB WS-WINSTON",
        "Z_SITE_NAME": None,
        "ELEMENT_TYPE": "PORT",
        "ELEMENT_NAME": "WNSLNCPV0QW/001.0004.010.26/SWT#0",
        "ELEMENT_REFERENCE": "895569",
        "ELEMENT_CATEGORY": "SWITCH",
        "ELEMENT_STATUS": "Live",
        "ELEMENT_BANDWIDTH": "40 Gbps",
        "NEXT_PATH_INST_ID": None,
        "PREV_PATH_INST_ID": None,
        "CHAN_NAME": "VLAN1162",
        "CHAN_INST_ID": "7163953",
        "SLOT": "96",
        "PORT_NAME": "1",
        "PORT_INST_ID": "101202650",
        "PORT_ACCESS_ID": "ET-0/0/96",
        "CONNECTOR_TYPE": "OTHER",
        "FQDN": "WNSLNCPV0QW.CHTRSE.COM",
        "MODEL": "QFX5100-96S",
        "VENDOR": "JUNIPER",
        "TID": "WNSLNCPV0QW",
        "LEGACY_EQUIP_SOURCE": "L-TWC",
        "PURCHASING_GROUP": "ENTERPRISE",
        "IPV4_ADDRESS": "10.20.102.126/24",
        "IPV6_ADDRESS": None,
        "C_VLAN": None,
        "CUST_S_VLAN": None,
        "S_VLAN": None,
        "VLAN_OPERATION": None,
        "PORT_ROLE": None,
        "INITIAL_PATH_NAME": "33.L1XX.006714..TWCC",
        "INITIAL_CIRCUIT_ID": None,
        "LVL": "2",
    },
    {
        "CIRC_PATH_INST_ID": "1128201",
        "PATH_NAME": "33001.GE40L.WNSLNCPV1CW.WNSLNCPV0QW",
        "PATH_REV": "1",
        "PATH_CATEGORY": "ETHERNET TRANSPORT",
        "PATH_A_SITE": "WNSLNCPV-TWC/HUB WS-WINSTON",
        "PATH_Z_SITE": "WNSLNCPV-TWC/HUB WS-WINSTON",
        "A_CLLI": "WNSLNCPV",
        "Z_CLLI": "WNSLNCPV",
        "PATH_A_SITE_TYPE": "HUB",
        "PATH_Z_SITE_TYPE": "HUB",
        "TOPOLOGY": "Point-to-point",
        "PATH_STATUS": "Live",
        "CLASS_OF_SERVICE": None,
        "SLM_ELIGIBILITY": None,
        "EVC_ID": None,
        "SERVICE_TYPE": "INT-EDGE TRANSPORT",
        "BANDWIDTH": "AGGREGATE",
        "BW_SIZE": "0",
        "CUSTOMER_ID": None,
        "CUSTOMER_NAME": None,
        "IPV4_GLUE_SUBNET": None,
        "IPV4_ASSIGNED_SUBNETS": None,
        "IPV4_ASSIGNED_GATEWAY": None,
        "IPV4_SERVICE_TYPE": None,
        "IPV6_GLUE_SUBNET": None,
        "IPV6_ASSIGNED_SUBNETS": None,
        "IPV6_SERVICE_TYPE": None,
        "CUSTOMER_TYPE": None,
        "ORDER_REFERENCE": "2.2.2.",
        "PARENT_SEQUENCE": "2",
        "PARENT_MEMBER_NBR": "2",
        "SEQUENCE": "2",
        "MEMBER_NBR": None,
        "LEG_NAME": "AE17/AE17 80G",
        "LEG_INST_ID": "1313051",
        "A_SITE_NAME": "WNSLNCPV-TWC/HUB WS-WINSTON",
        "Z_SITE_NAME": None,
        "ELEMENT_TYPE": "PORT",
        "ELEMENT_NAME": "WNSLNCPV0QW/001.0004.010.23/SWT#1",
        "ELEMENT_REFERENCE": "895581",
        "ELEMENT_CATEGORY": "SWITCH",
        "ELEMENT_STATUS": "Live",
        "ELEMENT_BANDWIDTH": "40 Gbps",
        "NEXT_PATH_INST_ID": None,
        "PREV_PATH_INST_ID": None,
        "CHAN_NAME": "VLAN1162",
        "CHAN_INST_ID": "7163953",
        "SLOT": "96",
        "PORT_NAME": "1",
        "PORT_INST_ID": "101202795",
        "PORT_ACCESS_ID": "ET-1/0/96",
        "CONNECTOR_TYPE": "OTHER",
        "FQDN": "WNSLNCPV0QW.CHTRSE.COM",
        "MODEL": "QFX5100-96S",
        "VENDOR": "JUNIPER",
        "TID": "WNSLNCPV0QW",
        "LEGACY_EQUIP_SOURCE": "L-TWC",
        "PURCHASING_GROUP": "ENTERPRISE",
        "IPV4_ADDRESS": "10.20.102.126/24",
        "IPV6_ADDRESS": None,
        "C_VLAN": None,
        "CUST_S_VLAN": None,
        "S_VLAN": None,
        "VLAN_OPERATION": None,
        "PORT_ROLE": None,
        "INITIAL_PATH_NAME": "33.L1XX.006714..TWCC",
        "INITIAL_CIRCUIT_ID": None,
        "LVL": "2",
    },
    {
        "CIRC_PATH_INST_ID": "1343761",
        "PATH_NAME": "33001.GE1.WNSLNCPV0QW.WNSLNCKX2ZW",
        "PATH_REV": "1",
        "PATH_CATEGORY": "ETHERNET TRANSPORT",
        "PATH_A_SITE": "WNSLNCPV-TWC/HUB WS-WINSTON",
        "PATH_Z_SITE": "WNSLNCKX-KUEHNE NAGEL//3929 WESTPOINT BLVD",
        "A_CLLI": "WNSLNCPV",
        "Z_CLLI": "WNSLNCKX",
        "PATH_A_SITE_TYPE": "HUB",
        "PATH_Z_SITE_TYPE": "LOCAL",
        "TOPOLOGY": "Point-to-point",
        "PATH_STATUS": "Pending Decommission",
        "CLASS_OF_SERVICE": None,
        "SLM_ELIGIBILITY": None,
        "EVC_ID": None,
        "SERVICE_TYPE": "INT-ACCESS TO PREM TRANSPORT",
        "BANDWIDTH": "1 Gbps",
        "BW_SIZE": "1000000000",
        "CUSTOMER_ID": None,
        "CUSTOMER_NAME": None,
        "IPV4_GLUE_SUBNET": None,
        "IPV4_ASSIGNED_SUBNETS": None,
        "IPV4_ASSIGNED_GATEWAY": None,
        "IPV4_SERVICE_TYPE": None,
        "IPV6_GLUE_SUBNET": None,
        "IPV6_ASSIGNED_SUBNETS": None,
        "IPV6_SERVICE_TYPE": None,
        "CUSTOMER_TYPE": None,
        "ORDER_REFERENCE": "3..1.",
        "PARENT_SEQUENCE": "3",
        "PARENT_MEMBER_NBR": None,
        "SEQUENCE": "1",
        "MEMBER_NBR": None,
        "LEG_NAME": "1",
        "LEG_INST_ID": "1543941",
        "A_SITE_NAME": "WNSLNCPV-TWC/HUB WS-WINSTON",
        "Z_SITE_NAME": None,
        "ELEMENT_TYPE": "PORT",
        "ELEMENT_NAME": "WNSLNCPV0QW/001.0004.010.26/SWT#0",
        "ELEMENT_REFERENCE": "895569",
        "ELEMENT_CATEGORY": "SWITCH",
        "ELEMENT_STATUS": "Live",
        "ELEMENT_BANDWIDTH": "1 Gbps",
        "NEXT_PATH_INST_ID": None,
        "PREV_PATH_INST_ID": None,
        "CHAN_NAME": "VLAN1162",
        "CHAN_INST_ID": "7163952",
        "SLOT": "8",
        "PORT_NAME": "1",
        "PORT_INST_ID": "103833392",
        "PORT_ACCESS_ID": "GE-0/0/8",
        "CONNECTOR_TYPE": "LC",
        "FQDN": "WNSLNCPV0QW.CHTRSE.COM",
        "MODEL": "QFX5100-96S",
        "VENDOR": "JUNIPER",
        "TID": "WNSLNCPV0QW",
        "LEGACY_EQUIP_SOURCE": "L-TWC",
        "PURCHASING_GROUP": "ENTERPRISE",
        "IPV4_ADDRESS": "10.20.102.126/24",
        "IPV6_ADDRESS": None,
        "C_VLAN": None,
        "CUST_S_VLAN": None,
        "S_VLAN": None,
        "VLAN_OPERATION": None,
        "PORT_ROLE": None,
        "INITIAL_PATH_NAME": "33.L1XX.006714..TWCC",
        "INITIAL_CIRCUIT_ID": None,
        "LVL": "2",
    },
    {
        "CIRC_PATH_INST_ID": "1343761",
        "PATH_NAME": "33001.GE1.WNSLNCPV0QW.WNSLNCKX2ZW",
        "PATH_REV": "1",
        "PATH_CATEGORY": "ETHERNET TRANSPORT",
        "PATH_A_SITE": "WNSLNCPV-TWC/HUB WS-WINSTON",
        "PATH_Z_SITE": "WNSLNCKX-KUEHNE NAGEL//3929 WESTPOINT BLVD",
        "A_CLLI": "WNSLNCPV",
        "Z_CLLI": "WNSLNCKX",
        "PATH_A_SITE_TYPE": "HUB",
        "PATH_Z_SITE_TYPE": "LOCAL",
        "TOPOLOGY": "Point-to-point",
        "PATH_STATUS": "Pending Decommission",
        "CLASS_OF_SERVICE": None,
        "SLM_ELIGIBILITY": None,
        "EVC_ID": None,
        "SERVICE_TYPE": "INT-ACCESS TO PREM TRANSPORT",
        "BANDWIDTH": "1 Gbps",
        "BW_SIZE": "1000000000",
        "CUSTOMER_ID": None,
        "CUSTOMER_NAME": None,
        "IPV4_GLUE_SUBNET": None,
        "IPV4_ASSIGNED_SUBNETS": None,
        "IPV4_ASSIGNED_GATEWAY": None,
        "IPV4_SERVICE_TYPE": None,
        "IPV6_GLUE_SUBNET": None,
        "IPV6_ASSIGNED_SUBNETS": None,
        "IPV6_SERVICE_TYPE": None,
        "CUSTOMER_TYPE": None,
        "ORDER_REFERENCE": "3..2.",
        "PARENT_SEQUENCE": "3",
        "PARENT_MEMBER_NBR": None,
        "SEQUENCE": "2",
        "MEMBER_NBR": None,
        "LEG_NAME": "1",
        "LEG_INST_ID": "1543941",
        "A_SITE_NAME": "WNSLNCKX-KUEHNE NAGEL//3929 WESTPOINT BLVD",
        "Z_SITE_NAME": None,
        "ELEMENT_TYPE": "PORT",
        "ELEMENT_NAME": "WNSLNCKX2ZW/999.9999.999.99",
        "ELEMENT_REFERENCE": "1037108",
        "ELEMENT_CATEGORY": "NIU",
        "ELEMENT_STATUS": "Pending Decommission",
        "ELEMENT_BANDWIDTH": "1 Gbps",
        "NEXT_PATH_INST_ID": None,
        "PREV_PATH_INST_ID": None,
        "CHAN_NAME": "VLAN1162",
        "CHAN_INST_ID": "7163952",
        "SLOT": "NET 1",
        "PORT_NAME": "1",
        "PORT_INST_ID": "103833213",
        "PORT_ACCESS_ID": "ETH PORT 1",
        "CONNECTOR_TYPE": "LC",
        "FQDN": "WNSLNCKX2ZW.CML.CHTRSE.COM",
        "MODEL": "ETX203AX/2SFP/2UTP2SFP",
        "VENDOR": "RAD",
        "TID": "WNSLNCKX2ZW",
        "LEGACY_EQUIP_SOURCE": "L-TWC",
        "PURCHASING_GROUP": "ENTERPRISE",
        "IPV4_ADDRESS": "DHCP",
        "IPV6_ADDRESS": None,
        "C_VLAN": None,
        "CUST_S_VLAN": None,
        "S_VLAN": None,
        "VLAN_OPERATION": None,
        "PORT_ROLE": None,
        "INITIAL_PATH_NAME": "33.L1XX.006714..TWCC",
        "INITIAL_CIRCUIT_ID": "",
        "LVL": "2",
    },
]

mock_granite_circuit_devices_bad_inital_cid_emptystr = [
    {
        "CIRC_PATH_INST_ID": "1334717",
        "PATH_NAME": "33.L1XX.006714..TWCC",
        "PATH_REV": "1",
        "PATH_CATEGORY": "ETHERNET",
        "PATH_A_SITE": "WNSLNCPV-TWC/HUB WS-WINSTON",
        "PATH_Z_SITE": "WNSLNCKX-KUEHNE NAGEL//3929 WESTPOINT BLVD",
        "A_CLLI": "WNSLNCPV",
        "Z_CLLI": "WNSLNCKX",
        "PATH_A_SITE_TYPE": "HUB",
        "PATH_Z_SITE_TYPE": "LOCAL",
        "TOPOLOGY": "Point-to-point",
        "PATH_STATUS": "Pending Decommission",
        "CLASS_OF_SERVICE": None,
        "SLM_ELIGIBILITY": "ELIGIBLE DESIGN",
        "EVC_ID": None,
        "SERVICE_TYPE": "CAR-DIA",
        "BANDWIDTH": "25 Mbps",
        "BW_SIZE": "25000000",
        "CUSTOMER_ID": "ACCT-04400732",
        "CUSTOMER_NAME": "MASSCOMM",
        "IPV4_GLUE_SUBNET": None,
        "IPV4_ASSIGNED_SUBNETS": "173.95.101.40",
        "IPV4_ASSIGNED_GATEWAY": "173.95.101.41",
        "IPV4_SERVICE_TYPE": "LAN",
        "IPV6_GLUE_SUBNET": "2606:A000:0:8::F:3096/127",
        "IPV6_ASSIGNED_SUBNETS": "2600:5800:8C6::/48",
        "IPV6_SERVICE_TYPE": "ROUTED",
        "CUSTOMER_TYPE": "CARRIER ACCESS",
        "ORDER_REFERENCE": "4.",
        "PARENT_SEQUENCE": None,
        "PARENT_MEMBER_NBR": None,
        "SEQUENCE": "4",
        "MEMBER_NBR": None,
        "LEG_NAME": "1",
        "LEG_INST_ID": "1533950",
        "A_SITE_NAME": "WNSLNCKX-KUEHNE NAGEL//3929 WESTPOINT BLVD",
        "Z_SITE_NAME": None,
        "ELEMENT_TYPE": "PORT",
        "ELEMENT_NAME": "WNSLNCKX2ZW/999.9999.999.99",
        "ELEMENT_REFERENCE": "1037108",
        "ELEMENT_CATEGORY": "NIU",
        "ELEMENT_STATUS": "Pending Decommission",
        "ELEMENT_BANDWIDTH": "10/100/1000 BASET",
        "NEXT_PATH_INST_ID": None,
        "PREV_PATH_INST_ID": None,
        "CHAN_NAME": None,
        "CHAN_INST_ID": None,
        "SLOT": "FIXED PORTS",
        "PORT_NAME": "USER 3",
        "PORT_INST_ID": "103833216",
        "PORT_ACCESS_ID": "ETH PORT 3",
        "CONNECTOR_TYPE": "RJ-45",
        "FQDN": "WNSLNCKX2ZW.CML.CHTRSE.COM",
        "MODEL": "ETX203AX/2SFP/2UTP2SFP",
        "VENDOR": "RAD",
        "TID": "WNSLNCKX2ZW",
        "LEGACY_EQUIP_SOURCE": "L-TWC",
        "PURCHASING_GROUP": "ENTERPRISE",
        "IPV4_ADDRESS": "DHCP",
        "IPV6_ADDRESS": None,
        "C_VLAN": None,
        "CUST_S_VLAN": None,
        "S_VLAN": "1162",
        "VLAN_OPERATION": "PUSH",
        "PORT_ROLE": "UNI-EP",
        "INITIAL_PATH_NAME": "33.L1XX.006714..TWCC",
        "INITIAL_CIRCUIT_ID": "",
        "LVL": "1",
    },
    {
        "CIRC_PATH_INST_ID": "1128201",
        "PATH_NAME": "33001.GE40L.WNSLNCPV1CW.WNSLNCPV0QW",
        "PATH_REV": "1",
        "PATH_CATEGORY": "ETHERNET TRANSPORT",
        "PATH_A_SITE": "WNSLNCPV-TWC/HUB WS-WINSTON",
        "PATH_Z_SITE": "WNSLNCPV-TWC/HUB WS-WINSTON",
        "A_CLLI": "WNSLNCPV",
        "Z_CLLI": "WNSLNCPV",
        "PATH_A_SITE_TYPE": "HUB",
        "PATH_Z_SITE_TYPE": "HUB",
        "TOPOLOGY": "Point-to-point",
        "PATH_STATUS": "Live",
        "CLASS_OF_SERVICE": None,
        "SLM_ELIGIBILITY": None,
        "EVC_ID": None,
        "SERVICE_TYPE": "INT-EDGE TRANSPORT",
        "BANDWIDTH": "AGGREGATE",
        "BW_SIZE": "0",
        "CUSTOMER_ID": None,
        "CUSTOMER_NAME": None,
        "IPV4_GLUE_SUBNET": None,
        "IPV4_ASSIGNED_SUBNETS": None,
        "IPV4_ASSIGNED_GATEWAY": None,
        "IPV4_SERVICE_TYPE": None,
        "IPV6_GLUE_SUBNET": None,
        "IPV6_ASSIGNED_SUBNETS": None,
        "IPV6_SERVICE_TYPE": None,
        "CUSTOMER_TYPE": None,
        "ORDER_REFERENCE": "2.1.1.",
        "PARENT_SEQUENCE": "2",
        "PARENT_MEMBER_NBR": "1",
        "SEQUENCE": "1",
        "MEMBER_NBR": None,
        "LEG_NAME": "AE17/AE17 80G",
        "LEG_INST_ID": "1313051",
        "A_SITE_NAME": "WNSLNCPV-TWC/HUB WS-WINSTON",
        "Z_SITE_NAME": None,
        "ELEMENT_TYPE": "PORT",
        "ELEMENT_NAME": "WNSLNCPV1CW/001.0001.102.11/RTR",
        "ELEMENT_REFERENCE": "514200",
        "ELEMENT_CATEGORY": "ROUTER",
        "ELEMENT_STATUS": "Live",
        "ELEMENT_BANDWIDTH": "40 Gbps",
        "NEXT_PATH_INST_ID": None,
        "PREV_PATH_INST_ID": None,
        "CHAN_NAME": "VLAN1162",
        "CHAN_INST_ID": "7163953",
        "SLOT": "3/0",
        "PORT_NAME": "1",
        "PORT_INST_ID": "103005919",
        "PORT_ACCESS_ID": "ET-4/3/0",
        "CONNECTOR_TYPE": "OTHER",
        "FQDN": "WNSLNCPV1CW.CHTRSE.COM",
        "MODEL": "MX960",
        "VENDOR": "JUNIPER",
        "TID": "WNSLNCPV1CW",
        "LEGACY_EQUIP_SOURCE": "L-TWC",
        "PURCHASING_GROUP": "ENTERPRISE",
        "IPV4_ADDRESS": "24.199.192.102/32",
        "IPV6_ADDRESS": "2606:A000::F:66/128",
        "C_VLAN": None,
        "CUST_S_VLAN": None,
        "S_VLAN": None,
        "VLAN_OPERATION": None,
        "PORT_ROLE": None,
        "INITIAL_PATH_NAME": "33.L1XX.006714..TWCC",
        "INITIAL_CIRCUIT_ID": "",
        "LVL": "2",
    },
    {
        "CIRC_PATH_INST_ID": "1128201",
        "PATH_NAME": "33001.GE40L.WNSLNCPV1CW.WNSLNCPV0QW",
        "PATH_REV": "1",
        "PATH_CATEGORY": "ETHERNET TRANSPORT",
        "PATH_A_SITE": "WNSLNCPV-TWC/HUB WS-WINSTON",
        "PATH_Z_SITE": "WNSLNCPV-TWC/HUB WS-WINSTON",
        "A_CLLI": "WNSLNCPV",
        "Z_CLLI": "WNSLNCPV",
        "PATH_A_SITE_TYPE": "HUB",
        "PATH_Z_SITE_TYPE": "HUB",
        "TOPOLOGY": "Point-to-point",
        "PATH_STATUS": "Live",
        "CLASS_OF_SERVICE": None,
        "SLM_ELIGIBILITY": None,
        "EVC_ID": None,
        "SERVICE_TYPE": "INT-EDGE TRANSPORT",
        "BANDWIDTH": "AGGREGATE",
        "BW_SIZE": "0",
        "CUSTOMER_ID": None,
        "CUSTOMER_NAME": None,
        "IPV4_GLUE_SUBNET": None,
        "IPV4_ASSIGNED_SUBNETS": None,
        "IPV4_ASSIGNED_GATEWAY": None,
        "IPV4_SERVICE_TYPE": None,
        "IPV6_GLUE_SUBNET": None,
        "IPV6_ASSIGNED_SUBNETS": None,
        "IPV6_SERVICE_TYPE": None,
        "CUSTOMER_TYPE": None,
        "ORDER_REFERENCE": "2.1.2.",
        "PARENT_SEQUENCE": "2",
        "PARENT_MEMBER_NBR": "1",
        "SEQUENCE": "2",
        "MEMBER_NBR": None,
        "LEG_NAME": "AE17/AE17 80G",
        "LEG_INST_ID": "1313051",
        "A_SITE_NAME": "WNSLNCPV-TWC/HUB WS-WINSTON",
        "Z_SITE_NAME": None,
        "ELEMENT_TYPE": "PORT",
        "ELEMENT_NAME": "WNSLNCPV1CW/001.0001.102.11/RTR",
        "ELEMENT_REFERENCE": "514200",
        "ELEMENT_CATEGORY": "ROUTER",
        "ELEMENT_STATUS": "Live",
        "ELEMENT_BANDWIDTH": "40 Gbps",
        "NEXT_PATH_INST_ID": None,
        "PREV_PATH_INST_ID": None,
        "CHAN_NAME": "VLAN1162",
        "CHAN_INST_ID": "7163953",
        "SLOT": "3/0",
        "PORT_NAME": "1",
        "PORT_INST_ID": "103005944",
        "PORT_ACCESS_ID": "ET-8/3/0",
        "CONNECTOR_TYPE": "OTHER",
        "FQDN": "WNSLNCPV1CW.CHTRSE.COM",
        "MODEL": "MX960",
        "VENDOR": "JUNIPER",
        "TID": "WNSLNCPV1CW",
        "LEGACY_EQUIP_SOURCE": "L-TWC",
        "PURCHASING_GROUP": "ENTERPRISE",
        "IPV4_ADDRESS": "24.199.192.102/32",
        "IPV6_ADDRESS": "2606:A000::F:66/128",
        "C_VLAN": None,
        "CUST_S_VLAN": None,
        "S_VLAN": None,
        "VLAN_OPERATION": None,
        "PORT_ROLE": None,
        "INITIAL_PATH_NAME": "33.L1XX.006714..TWCC",
        "INITIAL_CIRCUIT_ID": "",
        "LVL": "2",
    },
    {
        "CIRC_PATH_INST_ID": "1128201",
        "PATH_NAME": "33001.GE40L.WNSLNCPV1CW.WNSLNCPV0QW",
        "PATH_REV": "1",
        "PATH_CATEGORY": "ETHERNET TRANSPORT",
        "PATH_A_SITE": "WNSLNCPV-TWC/HUB WS-WINSTON",
        "PATH_Z_SITE": "WNSLNCPV-TWC/HUB WS-WINSTON",
        "A_CLLI": "WNSLNCPV",
        "Z_CLLI": "WNSLNCPV",
        "PATH_A_SITE_TYPE": "HUB",
        "PATH_Z_SITE_TYPE": "HUB",
        "TOPOLOGY": "Point-to-point",
        "PATH_STATUS": "Live",
        "CLASS_OF_SERVICE": None,
        "SLM_ELIGIBILITY": None,
        "EVC_ID": None,
        "SERVICE_TYPE": "INT-EDGE TRANSPORT",
        "BANDWIDTH": "AGGREGATE",
        "BW_SIZE": "0",
        "CUSTOMER_ID": None,
        "CUSTOMER_NAME": None,
        "IPV4_GLUE_SUBNET": None,
        "IPV4_ASSIGNED_SUBNETS": None,
        "IPV4_ASSIGNED_GATEWAY": None,
        "IPV4_SERVICE_TYPE": None,
        "IPV6_GLUE_SUBNET": None,
        "IPV6_ASSIGNED_SUBNETS": None,
        "IPV6_SERVICE_TYPE": None,
        "CUSTOMER_TYPE": None,
        "ORDER_REFERENCE": "2.2.1.",
        "PARENT_SEQUENCE": "2",
        "PARENT_MEMBER_NBR": "2",
        "SEQUENCE": "1",
        "MEMBER_NBR": None,
        "LEG_NAME": "AE17/AE17 80G",
        "LEG_INST_ID": "1313051",
        "A_SITE_NAME": "WNSLNCPV-TWC/HUB WS-WINSTON",
        "Z_SITE_NAME": None,
        "ELEMENT_TYPE": "PORT",
        "ELEMENT_NAME": "WNSLNCPV0QW/001.0004.010.26/SWT#0",
        "ELEMENT_REFERENCE": "895569",
        "ELEMENT_CATEGORY": "SWITCH",
        "ELEMENT_STATUS": "Live",
        "ELEMENT_BANDWIDTH": "40 Gbps",
        "NEXT_PATH_INST_ID": None,
        "PREV_PATH_INST_ID": None,
        "CHAN_NAME": "VLAN1162",
        "CHAN_INST_ID": "7163953",
        "SLOT": "96",
        "PORT_NAME": "1",
        "PORT_INST_ID": "101202650",
        "PORT_ACCESS_ID": "ET-0/0/96",
        "CONNECTOR_TYPE": "OTHER",
        "FQDN": "WNSLNCPV0QW.CHTRSE.COM",
        "MODEL": "QFX5100-96S",
        "VENDOR": "JUNIPER",
        "TID": "WNSLNCPV0QW",
        "LEGACY_EQUIP_SOURCE": "L-TWC",
        "PURCHASING_GROUP": "ENTERPRISE",
        "IPV4_ADDRESS": "10.20.102.126/24",
        "IPV6_ADDRESS": None,
        "C_VLAN": None,
        "CUST_S_VLAN": None,
        "S_VLAN": None,
        "VLAN_OPERATION": None,
        "PORT_ROLE": None,
        "INITIAL_PATH_NAME": "33.L1XX.006714..TWCC",
        "INITIAL_CIRCUIT_ID": "",
        "LVL": "2",
    },
    {
        "CIRC_PATH_INST_ID": "1128201",
        "PATH_NAME": "33001.GE40L.WNSLNCPV1CW.WNSLNCPV0QW",
        "PATH_REV": "1",
        "PATH_CATEGORY": "ETHERNET TRANSPORT",
        "PATH_A_SITE": "WNSLNCPV-TWC/HUB WS-WINSTON",
        "PATH_Z_SITE": "WNSLNCPV-TWC/HUB WS-WINSTON",
        "A_CLLI": "WNSLNCPV",
        "Z_CLLI": "WNSLNCPV",
        "PATH_A_SITE_TYPE": "HUB",
        "PATH_Z_SITE_TYPE": "HUB",
        "TOPOLOGY": "Point-to-point",
        "PATH_STATUS": "Live",
        "CLASS_OF_SERVICE": None,
        "SLM_ELIGIBILITY": None,
        "EVC_ID": None,
        "SERVICE_TYPE": "INT-EDGE TRANSPORT",
        "BANDWIDTH": "AGGREGATE",
        "BW_SIZE": "0",
        "CUSTOMER_ID": None,
        "CUSTOMER_NAME": None,
        "IPV4_GLUE_SUBNET": None,
        "IPV4_ASSIGNED_SUBNETS": None,
        "IPV4_ASSIGNED_GATEWAY": None,
        "IPV4_SERVICE_TYPE": None,
        "IPV6_GLUE_SUBNET": None,
        "IPV6_ASSIGNED_SUBNETS": None,
        "IPV6_SERVICE_TYPE": None,
        "CUSTOMER_TYPE": None,
        "ORDER_REFERENCE": "2.2.2.",
        "PARENT_SEQUENCE": "2",
        "PARENT_MEMBER_NBR": "2",
        "SEQUENCE": "2",
        "MEMBER_NBR": None,
        "LEG_NAME": "AE17/AE17 80G",
        "LEG_INST_ID": "1313051",
        "A_SITE_NAME": "WNSLNCPV-TWC/HUB WS-WINSTON",
        "Z_SITE_NAME": None,
        "ELEMENT_TYPE": "PORT",
        "ELEMENT_NAME": "WNSLNCPV0QW/001.0004.010.23/SWT#1",
        "ELEMENT_REFERENCE": "895581",
        "ELEMENT_CATEGORY": "SWITCH",
        "ELEMENT_STATUS": "Live",
        "ELEMENT_BANDWIDTH": "40 Gbps",
        "NEXT_PATH_INST_ID": None,
        "PREV_PATH_INST_ID": None,
        "CHAN_NAME": "VLAN1162",
        "CHAN_INST_ID": "7163953",
        "SLOT": "96",
        "PORT_NAME": "1",
        "PORT_INST_ID": "101202795",
        "PORT_ACCESS_ID": "ET-1/0/96",
        "CONNECTOR_TYPE": "OTHER",
        "FQDN": "WNSLNCPV0QW.CHTRSE.COM",
        "MODEL": "QFX5100-96S",
        "VENDOR": "JUNIPER",
        "TID": "WNSLNCPV0QW",
        "LEGACY_EQUIP_SOURCE": "L-TWC",
        "PURCHASING_GROUP": "ENTERPRISE",
        "IPV4_ADDRESS": "10.20.102.126/24",
        "IPV6_ADDRESS": None,
        "C_VLAN": None,
        "CUST_S_VLAN": None,
        "S_VLAN": None,
        "VLAN_OPERATION": None,
        "PORT_ROLE": None,
        "INITIAL_PATH_NAME": "33.L1XX.006714..TWCC",
        "INITIAL_CIRCUIT_ID": "",
        "LVL": "2",
    },
    {
        "CIRC_PATH_INST_ID": "1343761",
        "PATH_NAME": "33001.GE1.WNSLNCPV0QW.WNSLNCKX2ZW",
        "PATH_REV": "1",
        "PATH_CATEGORY": "ETHERNET TRANSPORT",
        "PATH_A_SITE": "WNSLNCPV-TWC/HUB WS-WINSTON",
        "PATH_Z_SITE": "WNSLNCKX-KUEHNE NAGEL//3929 WESTPOINT BLVD",
        "A_CLLI": "WNSLNCPV",
        "Z_CLLI": "WNSLNCKX",
        "PATH_A_SITE_TYPE": "HUB",
        "PATH_Z_SITE_TYPE": "LOCAL",
        "TOPOLOGY": "Point-to-point",
        "PATH_STATUS": "Pending Decommission",
        "CLASS_OF_SERVICE": None,
        "SLM_ELIGIBILITY": None,
        "EVC_ID": None,
        "SERVICE_TYPE": "INT-ACCESS TO PREM TRANSPORT",
        "BANDWIDTH": "1 Gbps",
        "BW_SIZE": "1000000000",
        "CUSTOMER_ID": None,
        "CUSTOMER_NAME": None,
        "IPV4_GLUE_SUBNET": None,
        "IPV4_ASSIGNED_SUBNETS": None,
        "IPV4_ASSIGNED_GATEWAY": None,
        "IPV4_SERVICE_TYPE": None,
        "IPV6_GLUE_SUBNET": None,
        "IPV6_ASSIGNED_SUBNETS": None,
        "IPV6_SERVICE_TYPE": None,
        "CUSTOMER_TYPE": None,
        "ORDER_REFERENCE": "3..1.",
        "PARENT_SEQUENCE": "3",
        "PARENT_MEMBER_NBR": None,
        "SEQUENCE": "1",
        "MEMBER_NBR": None,
        "LEG_NAME": "1",
        "LEG_INST_ID": "1543941",
        "A_SITE_NAME": "WNSLNCPV-TWC/HUB WS-WINSTON",
        "Z_SITE_NAME": None,
        "ELEMENT_TYPE": "PORT",
        "ELEMENT_NAME": "WNSLNCPV0QW/001.0004.010.26/SWT#0",
        "ELEMENT_REFERENCE": "895569",
        "ELEMENT_CATEGORY": "SWITCH",
        "ELEMENT_STATUS": "Live",
        "ELEMENT_BANDWIDTH": "1 Gbps",
        "NEXT_PATH_INST_ID": None,
        "PREV_PATH_INST_ID": None,
        "CHAN_NAME": "VLAN1162",
        "CHAN_INST_ID": "7163952",
        "SLOT": "8",
        "PORT_NAME": "1",
        "PORT_INST_ID": "103833392",
        "PORT_ACCESS_ID": "GE-0/0/8",
        "CONNECTOR_TYPE": "LC",
        "FQDN": "WNSLNCPV0QW.CHTRSE.COM",
        "MODEL": "QFX5100-96S",
        "VENDOR": "JUNIPER",
        "TID": "WNSLNCPV0QW",
        "LEGACY_EQUIP_SOURCE": "L-TWC",
        "PURCHASING_GROUP": "ENTERPRISE",
        "IPV4_ADDRESS": "10.20.102.126/24",
        "IPV6_ADDRESS": None,
        "C_VLAN": None,
        "CUST_S_VLAN": None,
        "S_VLAN": None,
        "VLAN_OPERATION": None,
        "PORT_ROLE": None,
        "INITIAL_PATH_NAME": "33.L1XX.006714..TWCC",
        "INITIAL_CIRCUIT_ID": "",
        "LVL": "2",
    },
    {
        "CIRC_PATH_INST_ID": "1343761",
        "PATH_NAME": "33001.GE1.WNSLNCPV0QW.WNSLNCKX2ZW",
        "PATH_REV": "1",
        "PATH_CATEGORY": "ETHERNET TRANSPORT",
        "PATH_A_SITE": "WNSLNCPV-TWC/HUB WS-WINSTON",
        "PATH_Z_SITE": "WNSLNCKX-KUEHNE NAGEL//3929 WESTPOINT BLVD",
        "A_CLLI": "WNSLNCPV",
        "Z_CLLI": "WNSLNCKX",
        "PATH_A_SITE_TYPE": "HUB",
        "PATH_Z_SITE_TYPE": "LOCAL",
        "TOPOLOGY": "Point-to-point",
        "PATH_STATUS": "Pending Decommission",
        "CLASS_OF_SERVICE": None,
        "SLM_ELIGIBILITY": None,
        "EVC_ID": None,
        "SERVICE_TYPE": "INT-ACCESS TO PREM TRANSPORT",
        "BANDWIDTH": "1 Gbps",
        "BW_SIZE": "1000000000",
        "CUSTOMER_ID": None,
        "CUSTOMER_NAME": None,
        "IPV4_GLUE_SUBNET": None,
        "IPV4_ASSIGNED_SUBNETS": None,
        "IPV4_ASSIGNED_GATEWAY": None,
        "IPV4_SERVICE_TYPE": None,
        "IPV6_GLUE_SUBNET": None,
        "IPV6_ASSIGNED_SUBNETS": None,
        "IPV6_SERVICE_TYPE": None,
        "CUSTOMER_TYPE": None,
        "ORDER_REFERENCE": "3..2.",
        "PARENT_SEQUENCE": "3",
        "PARENT_MEMBER_NBR": None,
        "SEQUENCE": "2",
        "MEMBER_NBR": None,
        "LEG_NAME": "1",
        "LEG_INST_ID": "1543941",
        "A_SITE_NAME": "WNSLNCKX-KUEHNE NAGEL//3929 WESTPOINT BLVD",
        "Z_SITE_NAME": None,
        "ELEMENT_TYPE": "PORT",
        "ELEMENT_NAME": "WNSLNCKX2ZW/999.9999.999.99",
        "ELEMENT_REFERENCE": "1037108",
        "ELEMENT_CATEGORY": "NIU",
        "ELEMENT_STATUS": "Pending Decommission",
        "ELEMENT_BANDWIDTH": "1 Gbps",
        "NEXT_PATH_INST_ID": None,
        "PREV_PATH_INST_ID": None,
        "CHAN_NAME": "VLAN1162",
        "CHAN_INST_ID": "7163952",
        "SLOT": "NET 1",
        "PORT_NAME": "1",
        "PORT_INST_ID": "103833213",
        "PORT_ACCESS_ID": "ETH PORT 1",
        "CONNECTOR_TYPE": "LC",
        "FQDN": "WNSLNCKX2ZW.CML.CHTRSE.COM",
        "MODEL": "ETX203AX/2SFP/2UTP2SFP",
        "VENDOR": "RAD",
        "TID": "WNSLNCKX2ZW",
        "LEGACY_EQUIP_SOURCE": "L-TWC",
        "PURCHASING_GROUP": "ENTERPRISE",
        "IPV4_ADDRESS": "DHCP",
        "IPV6_ADDRESS": None,
        "C_VLAN": None,
        "CUST_S_VLAN": None,
        "S_VLAN": None,
        "VLAN_OPERATION": None,
        "PORT_ROLE": None,
        "INITIAL_PATH_NAME": "33.L1XX.006714..TWCC",
        "INITIAL_CIRCUIT_ID": "",
        "LVL": "2",
    },
]

mock_granite_circuit_devices_bad_ip = [
    {
        "CIRC_PATH_INST_ID": "1334717",
        "PATH_NAME": "33.L1XX.006714..TWCC",
        "PATH_REV": "1",
        "PATH_CATEGORY": "ETHERNET",
        "PATH_A_SITE": "WNSLNCPV-TWC/HUB WS-WINSTON",
        "PATH_Z_SITE": "WNSLNCKX-KUEHNE NAGEL//3929 WESTPOINT BLVD",
        "A_CLLI": "WNSLNCPV",
        "Z_CLLI": "WNSLNCKX",
        "PATH_A_SITE_TYPE": "HUB",
        "PATH_Z_SITE_TYPE": "LOCAL",
        "TOPOLOGY": "Point-to-point",
        "PATH_STATUS": "Pending Decommission",
        "CLASS_OF_SERVICE": None,
        "SLM_ELIGIBILITY": "ELIGIBLE DESIGN",
        "EVC_ID": None,
        "SERVICE_TYPE": "CAR-DIA",
        "BANDWIDTH": "25 Mbps",
        "BW_SIZE": "25000000",
        "CUSTOMER_ID": "ACCT-04400732",
        "CUSTOMER_NAME": "MASSCOMM",
        "IPV4_GLUE_SUBNET": None,
        "IPV4_ASSIGNED_SUBNETS": "173.95.101.40",
        "IPV4_ASSIGNED_GATEWAY": "173.95.101.41",
        "IPV4_SERVICE_TYPE": "LAN",
        "IPV6_GLUE_SUBNET": "2606:A000:0:8::F:3096/127",
        "IPV6_ASSIGNED_SUBNETS": "2600:5800:8C6::/48",
        "IPV6_SERVICE_TYPE": "ROUTED",
        "CUSTOMER_TYPE": "CARRIER ACCESS",
        "ORDER_REFERENCE": "4.",
        "PARENT_SEQUENCE": None,
        "PARENT_MEMBER_NBR": None,
        "SEQUENCE": "4",
        "MEMBER_NBR": None,
        "LEG_NAME": "1",
        "LEG_INST_ID": "1533950",
        "A_SITE_NAME": "WNSLNCKX-KUEHNE NAGEL//3929 WESTPOINT BLVD",
        "Z_SITE_NAME": None,
        "ELEMENT_TYPE": "PORT",
        "ELEMENT_NAME": "WNSLNCKX2ZW/999.9999.999.99",
        "ELEMENT_REFERENCE": "1037108",
        "ELEMENT_CATEGORY": "NIU",
        "ELEMENT_STATUS": "Pending Decommission",
        "ELEMENT_BANDWIDTH": "10/100/1000 BASET",
        "NEXT_PATH_INST_ID": None,
        "PREV_PATH_INST_ID": None,
        "CHAN_NAME": None,
        "CHAN_INST_ID": None,
        "SLOT": "FIXED PORTS",
        "PORT_NAME": "USER 3",
        "PORT_INST_ID": "103833216",
        "PORT_ACCESS_ID": "ETH PORT 3",
        "CONNECTOR_TYPE": "RJ-45",
        "FQDN": "WNSLNCKX2ZW.CML.CHTRSE.COM",
        "MODEL": "ETX203AX/2SFP/2UTP2SFP",
        "VENDOR": "RAD",
        "TID": "WNSLNCKX2ZW",
        "LEGACY_EQUIP_SOURCE": "L-TWC",
        "PURCHASING_GROUP": "ENTERPRISE",
        "C_VLAN": None,
        "CUST_S_VLAN": None,
        "S_VLAN": "1162",
        "VLAN_OPERATION": "PUSH",
        "PORT_ROLE": "UNI-EP",
        "INITIAL_PATH_NAME": "33.L1XX.006714..TWCC",
        "INITIAL_CIRCUIT_ID": "1334717",
        "LVL": "1",
    },
    {
        "CIRC_PATH_INST_ID": "1128201",
        "PATH_NAME": "33001.GE40L.WNSLNCPV1CW.WNSLNCPV0QW",
        "PATH_REV": "1",
        "PATH_CATEGORY": "ETHERNET TRANSPORT",
        "PATH_A_SITE": "WNSLNCPV-TWC/HUB WS-WINSTON",
        "PATH_Z_SITE": "WNSLNCPV-TWC/HUB WS-WINSTON",
        "A_CLLI": "WNSLNCPV",
        "Z_CLLI": "WNSLNCPV",
        "PATH_A_SITE_TYPE": "HUB",
        "PATH_Z_SITE_TYPE": "HUB",
        "TOPOLOGY": "Point-to-point",
        "PATH_STATUS": "Live",
        "CLASS_OF_SERVICE": None,
        "SLM_ELIGIBILITY": None,
        "EVC_ID": None,
        "SERVICE_TYPE": "INT-EDGE TRANSPORT",
        "BANDWIDTH": "AGGREGATE",
        "BW_SIZE": "0",
        "CUSTOMER_ID": None,
        "CUSTOMER_NAME": None,
        "IPV4_GLUE_SUBNET": None,
        "IPV4_ASSIGNED_SUBNETS": None,
        "IPV4_ASSIGNED_GATEWAY": None,
        "IPV4_SERVICE_TYPE": None,
        "IPV6_GLUE_SUBNET": None,
        "IPV6_ASSIGNED_SUBNETS": None,
        "IPV6_SERVICE_TYPE": None,
        "CUSTOMER_TYPE": None,
        "ORDER_REFERENCE": "2.1.1.",
        "PARENT_SEQUENCE": "2",
        "PARENT_MEMBER_NBR": "1",
        "SEQUENCE": "1",
        "MEMBER_NBR": None,
        "LEG_NAME": "AE17/AE17 80G",
        "LEG_INST_ID": "1313051",
        "A_SITE_NAME": "WNSLNCPV-TWC/HUB WS-WINSTON",
        "Z_SITE_NAME": None,
        "ELEMENT_TYPE": "PORT",
        "ELEMENT_NAME": "WNSLNCPV1CW/001.0001.102.11/RTR",
        "ELEMENT_REFERENCE": "514200",
        "ELEMENT_CATEGORY": "ROUTER",
        "ELEMENT_STATUS": "Live",
        "ELEMENT_BANDWIDTH": "40 Gbps",
        "NEXT_PATH_INST_ID": None,
        "PREV_PATH_INST_ID": None,
        "CHAN_NAME": "VLAN1162",
        "CHAN_INST_ID": "7163953",
        "SLOT": "3/0",
        "PORT_NAME": "1",
        "PORT_INST_ID": "103005919",
        "PORT_ACCESS_ID": "ET-4/3/0",
        "CONNECTOR_TYPE": "OTHER",
        "FQDN": "WNSLNCPV1CW.CHTRSE.COM",
        "MODEL": "MX960",
        "VENDOR": "JUNIPER",
        "TID": "WNSLNCPV1CW",
        "LEGACY_EQUIP_SOURCE": "L-TWC",
        "PURCHASING_GROUP": "ENTERPRISE",
        "C_VLAN": None,
        "CUST_S_VLAN": None,
        "S_VLAN": None,
        "VLAN_OPERATION": None,
        "PORT_ROLE": None,
        "INITIAL_PATH_NAME": "33.L1XX.006714..TWCC",
        "INITIAL_CIRCUIT_ID": "1334717",
        "LVL": "2",
    },
    {
        "CIRC_PATH_INST_ID": "1128201",
        "PATH_NAME": "33001.GE40L.WNSLNCPV1CW.WNSLNCPV0QW",
        "PATH_REV": "1",
        "PATH_CATEGORY": "ETHERNET TRANSPORT",
        "PATH_A_SITE": "WNSLNCPV-TWC/HUB WS-WINSTON",
        "PATH_Z_SITE": "WNSLNCPV-TWC/HUB WS-WINSTON",
        "A_CLLI": "WNSLNCPV",
        "Z_CLLI": "WNSLNCPV",
        "PATH_A_SITE_TYPE": "HUB",
        "PATH_Z_SITE_TYPE": "HUB",
        "TOPOLOGY": "Point-to-point",
        "PATH_STATUS": "Live",
        "CLASS_OF_SERVICE": None,
        "SLM_ELIGIBILITY": None,
        "EVC_ID": None,
        "SERVICE_TYPE": "INT-EDGE TRANSPORT",
        "BANDWIDTH": "AGGREGATE",
        "BW_SIZE": "0",
        "CUSTOMER_ID": None,
        "CUSTOMER_NAME": None,
        "IPV4_GLUE_SUBNET": None,
        "IPV4_ASSIGNED_SUBNETS": None,
        "IPV4_ASSIGNED_GATEWAY": None,
        "IPV4_SERVICE_TYPE": None,
        "IPV6_GLUE_SUBNET": None,
        "IPV6_ASSIGNED_SUBNETS": None,
        "IPV6_SERVICE_TYPE": None,
        "CUSTOMER_TYPE": None,
        "ORDER_REFERENCE": "2.1.2.",
        "PARENT_SEQUENCE": "2",
        "PARENT_MEMBER_NBR": "1",
        "SEQUENCE": "2",
        "MEMBER_NBR": None,
        "LEG_NAME": "AE17/AE17 80G",
        "LEG_INST_ID": "1313051",
        "A_SITE_NAME": "WNSLNCPV-TWC/HUB WS-WINSTON",
        "Z_SITE_NAME": None,
        "ELEMENT_TYPE": "PORT",
        "ELEMENT_NAME": "WNSLNCPV1CW/001.0001.102.11/RTR",
        "ELEMENT_REFERENCE": "514200",
        "ELEMENT_CATEGORY": "ROUTER",
        "ELEMENT_STATUS": "Live",
        "ELEMENT_BANDWIDTH": "40 Gbps",
        "NEXT_PATH_INST_ID": None,
        "PREV_PATH_INST_ID": None,
        "CHAN_NAME": "VLAN1162",
        "CHAN_INST_ID": "7163953",
        "SLOT": "3/0",
        "PORT_NAME": "1",
        "PORT_INST_ID": "103005944",
        "PORT_ACCESS_ID": "ET-8/3/0",
        "CONNECTOR_TYPE": "OTHER",
        "FQDN": "WNSLNCPV1CW.CHTRSE.COM",
        "MODEL": "MX960",
        "VENDOR": "JUNIPER",
        "TID": "WNSLNCPV1CW",
        "LEGACY_EQUIP_SOURCE": "L-TWC",
        "PURCHASING_GROUP": "ENTERPRISE",
        "C_VLAN": None,
        "CUST_S_VLAN": None,
        "S_VLAN": None,
        "VLAN_OPERATION": None,
        "PORT_ROLE": None,
        "INITIAL_PATH_NAME": "33.L1XX.006714..TWCC",
        "INITIAL_CIRCUIT_ID": "1334717",
        "LVL": "2",
    },
    {
        "CIRC_PATH_INST_ID": "1128201",
        "PATH_NAME": "33001.GE40L.WNSLNCPV1CW.WNSLNCPV0QW",
        "PATH_REV": "1",
        "PATH_CATEGORY": "ETHERNET TRANSPORT",
        "PATH_A_SITE": "WNSLNCPV-TWC/HUB WS-WINSTON",
        "PATH_Z_SITE": "WNSLNCPV-TWC/HUB WS-WINSTON",
        "A_CLLI": "WNSLNCPV",
        "Z_CLLI": "WNSLNCPV",
        "PATH_A_SITE_TYPE": "HUB",
        "PATH_Z_SITE_TYPE": "HUB",
        "TOPOLOGY": "Point-to-point",
        "PATH_STATUS": "Live",
        "CLASS_OF_SERVICE": None,
        "SLM_ELIGIBILITY": None,
        "EVC_ID": None,
        "SERVICE_TYPE": "INT-EDGE TRANSPORT",
        "BANDWIDTH": "AGGREGATE",
        "BW_SIZE": "0",
        "CUSTOMER_ID": None,
        "CUSTOMER_NAME": None,
        "IPV4_GLUE_SUBNET": None,
        "IPV4_ASSIGNED_SUBNETS": None,
        "IPV4_ASSIGNED_GATEWAY": None,
        "IPV4_SERVICE_TYPE": None,
        "IPV6_GLUE_SUBNET": None,
        "IPV6_ASSIGNED_SUBNETS": None,
        "IPV6_SERVICE_TYPE": None,
        "CUSTOMER_TYPE": None,
        "ORDER_REFERENCE": "2.2.1.",
        "PARENT_SEQUENCE": "2",
        "PARENT_MEMBER_NBR": "2",
        "SEQUENCE": "1",
        "MEMBER_NBR": None,
        "LEG_NAME": "AE17/AE17 80G",
        "LEG_INST_ID": "1313051",
        "A_SITE_NAME": "WNSLNCPV-TWC/HUB WS-WINSTON",
        "Z_SITE_NAME": None,
        "ELEMENT_TYPE": "PORT",
        "ELEMENT_NAME": "WNSLNCPV0QW/001.0004.010.26/SWT#0",
        "ELEMENT_REFERENCE": "895569",
        "ELEMENT_CATEGORY": "SWITCH",
        "ELEMENT_STATUS": "Live",
        "ELEMENT_BANDWIDTH": "40 Gbps",
        "NEXT_PATH_INST_ID": None,
        "PREV_PATH_INST_ID": None,
        "CHAN_NAME": "VLAN1162",
        "CHAN_INST_ID": "7163953",
        "SLOT": "96",
        "PORT_NAME": "1",
        "PORT_INST_ID": "101202650",
        "PORT_ACCESS_ID": "ET-0/0/96",
        "CONNECTOR_TYPE": "OTHER",
        "FQDN": "WNSLNCPV0QW.CHTRSE.COM",
        "MODEL": "QFX5100-96S",
        "VENDOR": "JUNIPER",
        "TID": "WNSLNCPV0QW",
        "LEGACY_EQUIP_SOURCE": "L-TWC",
        "PURCHASING_GROUP": "ENTERPRISE",
        "C_VLAN": None,
        "CUST_S_VLAN": None,
        "S_VLAN": None,
        "VLAN_OPERATION": None,
        "PORT_ROLE": None,
        "INITIAL_PATH_NAME": "33.L1XX.006714..TWCC",
        "INITIAL_CIRCUIT_ID": "1334717",
        "LVL": "2",
    },
    {
        "CIRC_PATH_INST_ID": "1128201",
        "PATH_NAME": "33001.GE40L.WNSLNCPV1CW.WNSLNCPV0QW",
        "PATH_REV": "1",
        "PATH_CATEGORY": "ETHERNET TRANSPORT",
        "PATH_A_SITE": "WNSLNCPV-TWC/HUB WS-WINSTON",
        "PATH_Z_SITE": "WNSLNCPV-TWC/HUB WS-WINSTON",
        "A_CLLI": "WNSLNCPV",
        "Z_CLLI": "WNSLNCPV",
        "PATH_A_SITE_TYPE": "HUB",
        "PATH_Z_SITE_TYPE": "HUB",
        "TOPOLOGY": "Point-to-point",
        "PATH_STATUS": "Live",
        "CLASS_OF_SERVICE": None,
        "SLM_ELIGIBILITY": None,
        "EVC_ID": None,
        "SERVICE_TYPE": "INT-EDGE TRANSPORT",
        "BANDWIDTH": "AGGREGATE",
        "BW_SIZE": "0",
        "CUSTOMER_ID": None,
        "CUSTOMER_NAME": None,
        "IPV4_GLUE_SUBNET": None,
        "IPV4_ASSIGNED_SUBNETS": None,
        "IPV4_ASSIGNED_GATEWAY": None,
        "IPV4_SERVICE_TYPE": None,
        "IPV6_GLUE_SUBNET": None,
        "IPV6_ASSIGNED_SUBNETS": None,
        "IPV6_SERVICE_TYPE": None,
        "CUSTOMER_TYPE": None,
        "ORDER_REFERENCE": "2.2.2.",
        "PARENT_SEQUENCE": "2",
        "PARENT_MEMBER_NBR": "2",
        "SEQUENCE": "2",
        "MEMBER_NBR": None,
        "LEG_NAME": "AE17/AE17 80G",
        "LEG_INST_ID": "1313051",
        "A_SITE_NAME": "WNSLNCPV-TWC/HUB WS-WINSTON",
        "Z_SITE_NAME": None,
        "ELEMENT_TYPE": "PORT",
        "ELEMENT_NAME": "WNSLNCPV0QW/001.0004.010.23/SWT#1",
        "ELEMENT_REFERENCE": "895581",
        "ELEMENT_CATEGORY": "SWITCH",
        "ELEMENT_STATUS": "Live",
        "ELEMENT_BANDWIDTH": "40 Gbps",
        "NEXT_PATH_INST_ID": None,
        "PREV_PATH_INST_ID": None,
        "CHAN_NAME": "VLAN1162",
        "CHAN_INST_ID": "7163953",
        "SLOT": "96",
        "PORT_NAME": "1",
        "PORT_INST_ID": "101202795",
        "PORT_ACCESS_ID": "ET-1/0/96",
        "CONNECTOR_TYPE": "OTHER",
        "FQDN": "WNSLNCPV0QW.CHTRSE.COM",
        "MODEL": "QFX5100-96S",
        "VENDOR": "JUNIPER",
        "TID": "WNSLNCPV0QW",
        "LEGACY_EQUIP_SOURCE": "L-TWC",
        "PURCHASING_GROUP": "ENTERPRISE",
        "C_VLAN": None,
        "CUST_S_VLAN": None,
        "S_VLAN": None,
        "VLAN_OPERATION": None,
        "PORT_ROLE": None,
        "INITIAL_PATH_NAME": "33.L1XX.006714..TWCC",
        "INITIAL_CIRCUIT_ID": "1334717",
        "LVL": "2",
    },
    {
        "CIRC_PATH_INST_ID": "1343761",
        "PATH_NAME": "33001.GE1.WNSLNCPV0QW.WNSLNCKX2ZW",
        "PATH_REV": "1",
        "PATH_CATEGORY": "ETHERNET TRANSPORT",
        "PATH_A_SITE": "WNSLNCPV-TWC/HUB WS-WINSTON",
        "PATH_Z_SITE": "WNSLNCKX-KUEHNE NAGEL//3929 WESTPOINT BLVD",
        "A_CLLI": "WNSLNCPV",
        "Z_CLLI": "WNSLNCKX",
        "PATH_A_SITE_TYPE": "HUB",
        "PATH_Z_SITE_TYPE": "LOCAL",
        "TOPOLOGY": "Point-to-point",
        "PATH_STATUS": "Pending Decommission",
        "CLASS_OF_SERVICE": None,
        "SLM_ELIGIBILITY": None,
        "EVC_ID": None,
        "SERVICE_TYPE": "INT-ACCESS TO PREM TRANSPORT",
        "BANDWIDTH": "1 Gbps",
        "BW_SIZE": "1000000000",
        "CUSTOMER_ID": None,
        "CUSTOMER_NAME": None,
        "IPV4_GLUE_SUBNET": None,
        "IPV4_ASSIGNED_SUBNETS": None,
        "IPV4_ASSIGNED_GATEWAY": None,
        "IPV4_SERVICE_TYPE": None,
        "IPV6_GLUE_SUBNET": None,
        "IPV6_ASSIGNED_SUBNETS": None,
        "IPV6_SERVICE_TYPE": None,
        "CUSTOMER_TYPE": None,
        "ORDER_REFERENCE": "3..1.",
        "PARENT_SEQUENCE": "3",
        "PARENT_MEMBER_NBR": None,
        "SEQUENCE": "1",
        "MEMBER_NBR": None,
        "LEG_NAME": "1",
        "LEG_INST_ID": "1543941",
        "A_SITE_NAME": "WNSLNCPV-TWC/HUB WS-WINSTON",
        "Z_SITE_NAME": None,
        "ELEMENT_TYPE": "PORT",
        "ELEMENT_NAME": "WNSLNCPV0QW/001.0004.010.26/SWT#0",
        "ELEMENT_REFERENCE": "895569",
        "ELEMENT_CATEGORY": "SWITCH",
        "ELEMENT_STATUS": "Live",
        "ELEMENT_BANDWIDTH": "1 Gbps",
        "NEXT_PATH_INST_ID": None,
        "PREV_PATH_INST_ID": None,
        "CHAN_NAME": "VLAN1162",
        "CHAN_INST_ID": "7163952",
        "SLOT": "8",
        "PORT_NAME": "1",
        "PORT_INST_ID": "103833392",
        "PORT_ACCESS_ID": "GE-0/0/8",
        "CONNECTOR_TYPE": "LC",
        "FQDN": "WNSLNCPV0QW.CHTRSE.COM",
        "MODEL": "QFX5100-96S",
        "VENDOR": "JUNIPER",
        "TID": "WNSLNCPV0QW",
        "LEGACY_EQUIP_SOURCE": "L-TWC",
        "PURCHASING_GROUP": "ENTERPRISE",
        "C_VLAN": None,
        "CUST_S_VLAN": None,
        "S_VLAN": None,
        "VLAN_OPERATION": None,
        "PORT_ROLE": None,
        "INITIAL_PATH_NAME": "33.L1XX.006714..TWCC",
        "INITIAL_CIRCUIT_ID": "1334717",
        "LVL": "2",
    },
    {
        "CIRC_PATH_INST_ID": "1343761",
        "PATH_NAME": "33001.GE1.WNSLNCPV0QW.WNSLNCKX2ZW",
        "PATH_REV": "1",
        "PATH_CATEGORY": "ETHERNET TRANSPORT",
        "PATH_A_SITE": "WNSLNCPV-TWC/HUB WS-WINSTON",
        "PATH_Z_SITE": "WNSLNCKX-KUEHNE NAGEL//3929 WESTPOINT BLVD",
        "A_CLLI": "WNSLNCPV",
        "Z_CLLI": "WNSLNCKX",
        "PATH_A_SITE_TYPE": "HUB",
        "PATH_Z_SITE_TYPE": "LOCAL",
        "TOPOLOGY": "Point-to-point",
        "PATH_STATUS": "Pending Decommission",
        "CLASS_OF_SERVICE": None,
        "SLM_ELIGIBILITY": None,
        "EVC_ID": None,
        "SERVICE_TYPE": "INT-ACCESS TO PREM TRANSPORT",
        "BANDWIDTH": "1 Gbps",
        "BW_SIZE": "1000000000",
        "CUSTOMER_ID": None,
        "CUSTOMER_NAME": None,
        "IPV4_GLUE_SUBNET": None,
        "IPV4_ASSIGNED_SUBNETS": None,
        "IPV4_ASSIGNED_GATEWAY": None,
        "IPV4_SERVICE_TYPE": None,
        "IPV6_GLUE_SUBNET": None,
        "IPV6_ASSIGNED_SUBNETS": None,
        "IPV6_SERVICE_TYPE": None,
        "CUSTOMER_TYPE": None,
        "ORDER_REFERENCE": "3..2.",
        "PARENT_SEQUENCE": "3",
        "PARENT_MEMBER_NBR": None,
        "SEQUENCE": "2",
        "MEMBER_NBR": None,
        "LEG_NAME": "1",
        "LEG_INST_ID": "1543941",
        "A_SITE_NAME": "WNSLNCKX-KUEHNE NAGEL//3929 WESTPOINT BLVD",
        "Z_SITE_NAME": None,
        "ELEMENT_TYPE": "PORT",
        "ELEMENT_NAME": "WNSLNCKX2ZW/999.9999.999.99",
        "ELEMENT_REFERENCE": "1037108",
        "ELEMENT_CATEGORY": "NIU",
        "ELEMENT_STATUS": "Pending Decommission",
        "ELEMENT_BANDWIDTH": "1 Gbps",
        "NEXT_PATH_INST_ID": None,
        "PREV_PATH_INST_ID": None,
        "CHAN_NAME": "VLAN1162",
        "CHAN_INST_ID": "7163952",
        "SLOT": "NET 1",
        "PORT_NAME": "1",
        "PORT_INST_ID": "103833213",
        "PORT_ACCESS_ID": "ETH PORT 1",
        "CONNECTOR_TYPE": "LC",
        "FQDN": "WNSLNCKX2ZW.CML.CHTRSE.COM",
        "MODEL": "ETX203AX/2SFP/2UTP2SFP",
        "VENDOR": "RAD",
        "TID": "WNSLNCKX2ZW",
        "LEGACY_EQUIP_SOURCE": "L-TWC",
        "PURCHASING_GROUP": "ENTERPRISE",
        "C_VLAN": None,
        "CUST_S_VLAN": None,
        "S_VLAN": None,
        "VLAN_OPERATION": None,
        "PORT_ROLE": None,
        "INITIAL_PATH_NAME": "33.L1XX.006714..TWCC",
        "INITIAL_CIRCUIT_ID": "1334717",
        "LVL": "2",
    },
]


mock_granite_circuit_devices_return = {
    "topology": "CAR-DIA",
    "device_list": [
        {
            "ip": "DHCP",
            "tid": "WNSLNCKX2ZW",
            "fqdn": "WNSLNCKX2ZW.CML.CHTRSE.COM",
            "port": "ETH PORT 3",
            "vlan": "1162",
            "vendor": "RAD",
            "channel": None,
            "category": "NIU",
            "leg": "1",
        },
        {
            "ip": "24.199.192.102/32",
            "tid": "WNSLNCPV1CW",
            "fqdn": "WNSLNCPV1CW.CHTRSE.COM",
            "port": "ET-4/3/0",
            "vlan": None,
            "vendor": "JUNIPER",
            "channel": "VLAN1162",
            "category": "ROUTER",
            "leg": "AE17/AE17 80G",
        },
        {
            "ip": "10.20.102.126/24",
            "tid": "WNSLNCPV0QW",
            "fqdn": "WNSLNCPV0QW.CHTRSE.COM",
            "port": "ET-0/0/96",
            "vlan": None,
            "vendor": "JUNIPER",
            "channel": "VLAN1162",
            "category": "SWITCH",
            "leg": "AE17/AE17 80G",
        },
    ],
}

mock_ca_spectrum_get_models_for_device = {
    "model": {
        "@mh": "0x14394109",
        "attribute": [
            {"@id": "0x129fa", "$": "0x14394109"},  # Model Handle ID
            {"@id": "0x1006e", "$": "HBRNOH181ZW"},  # Model Name ID
            {"@id": "0x12d7f", "$": "10.9.243.200"},  # Network Addess ID
            {"@id": "0x10004", "$": "1"},
            {"@id": "0x129f8", "$": "true"},
        ],
    },
    "link_url": None,
}

mock_ca_spectrum_get_model_response = {
    "model-response-list": {
        "@total-models": 1,
        "@throttle": 1,
        "@error": "EndOfResults",
        "model-responses": {
            "model": {
                "@mh": "0x14394109",
                "attribute": [
                    {"@id": "0x129fa", "$": "0x14394109"},
                    {"@id": "0x1006e", "$": "HBRNOH181ZW"},
                    {"@id": "0x12d7f", "$": "10.9.243.200"},
                    {"@id": "0x10004", "$": "1"},
                    {"@id": "0x129f8", "$": "true"},
                ],
            }
        },
    }
}

mock_ca_spectrum_get_model_response_less_than_one = {
    "model-response-list": {
        "@total-models": 0,
        "@throttle": 1,
        "@error": "EndOfResults",
        "model-responses": {
            "model": {
                "@mh": "0x14394109",
                "attribute": [
                    {"@id": "0x129fa", "$": "0x14394109"},
                    {"@id": "0x1006e", "$": "HBRNOH181ZW"},
                    {"@id": "0x12d7f", "$": "10.9.243.200"},
                    {"@id": "0x10004", "$": "1"},
                    {"@id": "0x129f8", "$": "true"},
                ],
            }
        },
    }
}
mock_ca_spectrum_get_model_response_greater_than_one = {
    "model-response-list": {
        "@total-models": 2,
        "@throttle": 1,
        "@error": "EndOfResults",
        "model-responses": {
            "model": {
                "@mh": "0x14394109",
                "attribute": [
                    {"@id": "0x129fa", "$": "0x14394109"},
                    {"@id": "0x1006e", "$": "HBRNOH181ZW"},
                    {"@id": "0x12d7f", "$": "10.9.243.200"},
                    {"@id": "0x10004", "$": "1"},
                    {"@id": "0x129f8", "$": "true"},
                ],
            }
        },
    }
}

mock_ca_spectrum_get_models_for_device_wrong_tid = {
    "model": {
        "@mh": "0x14394109",
        "attribute": [
            {"@id": "0x129fa", "$": "0x14394109"},  # Model Handle ID
            {"@id": "0x1006e", "$": "hahainserttidhere"},  # Model Name ID
            {"@id": "0x12d7f", "$": "10.9.243.200"},  # Network Addess ID
            {"@id": "0x10004", "$": "1"},
            {"@id": "0x129f8", "$": "true"},
        ],
    },
    "link_url": None,
}

mock_ca_spectrum_get_models_for_device_missing_attribute = {
    "model": {
        "@mh": "0x14394109",
        "attribute": [
            {"@id": "0x129fa", "$": "0x14394109"},  # Model Handle ID
            {"@id": "0x1006e"},  # Model Name ID
            {"@id": "0x12d7f", "$": "10.9.243.200"},  # Network Addess ID
            {"@id": "0x10004", "$": "1"},
            {"@id": "0x129f8", "$": "true"},
        ],
    },
    "link_url": None,
}

mock_ca_spectrum_get_models_for_device_no_attributes = {"model": {"@mh": "0x14394109"}, "link_url": None}

mock_attribute_list = [
    {"@id": "0x129fa", "$": "0x14394109"},
    {"@id": "0x1006e", "$": "HBRNOH181ZW"},
    {"@id": "0x12d7f", "$": "10.9.243.200"},
    {"@id": "0x10004", "$": "1"},
    {"@id": "0x129f8", "$": "true"},
]

mock_shelf_put_ok = {"instId": "0", "httpCode": 200, "retString": "SHELF UPDATED"}

mock_shelf_put_wrong_retString = {"instId": "0", "httpCode": 200, "retString": "EXAMPLE BAD STRING"}
