# Job to build app based on version.json
# image names as follows: $REGISTRY_NAME/$VENDOR_NAME/${PROJECT_NAME/-/_}:$IMAGE_TAG
# where $IMAGE_TAG can look like:  version-tag or branch.version-tag (when not in master/main branch)

# This job will build an image for any app (RA, microservice etc)
# By default, only changes in version.json will trigger this
.build-app:
  variables:
    MAIN_BRANCH: "master"
    DOCKER_CLI_EXPERIMENTAL: "enabled"
    REGISTRY_MIRROR: "false"  # Mirror to current repo's docker registry
    MIRROR_TO_RELEASE_REG: "false" # Mirror to standard product registry: registry.blueplanet.com/release
    DOCKER_RELEASE_REGISTRY: "registry.blueplanet.com/blueplanet/release"
  stage: build
  tags:
    - mdso
  image: $REGISTRY_NAME/docker/blueplanet/devtools/common-ci-cd-automations/build-image:latest
  script:
    - source auto_build_set_env
    - source get_image_tag
    # Required for RAs Dockerfile
    - mkdir -p ./.devops-toolkit
    - docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASSWORD $REGISTRY_NAME
    - IMAGE_NAME=$REGISTRY_NAME/docker/${PROJECT_NAME//-/_}
    - >
      if docker manifest inspect $IMAGE_NAME:$IMAGE_TAG 1>/dev/null ; then
          echo "
          *********************************************
          *
          * ERROR: $IMAGE_NAME:$IMAGE_TAG already exists on registry
          *
          * Troubleshooting:
          * - Was this manually pushed to the docker registry?
          * - Was \`version.json\` file updated but the version/tag values weren't bumped? Any changes in \`version.json\` will not trigger an automatic uprev step
          *
          *********************************************"
          exit 1
      else
          echo Building $IMAGE_NAME:$IMAGE_TAG
      fi
    - docker build --build-arg pypiUser=$pypiUser --build-arg pypiToken=$pypiToken --build-arg blueplanetPypi=$blueplanetPypi -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG
    - echo "Pushed $IMAGE_NAME:$IMAGE_TAG"
    ## If you want to mirror to this repo's docker registry
    - |
      if [ $REGISTRY_MIRROR = true ]; then
        echo This image is going to be mirrored to $CI_REGISTRY_IMAGE
        docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
        docker tag $REGISTRY_IMAGE:$IMAGE_TAG  $CI_REGISTRY_IMAGE:$IMAGE_TAG
        docker push $CI_REGISTRY_IMAGE:$IMAGE_TAG
        echo pushed $CI_REGISTRY_IMAGE:$IMAGE_TAG
      fi
    ## If you want to mirror to the standard registry on gitlab
    - |
      if [ $MIRROR_TO_RELEASE_REG = true ]; then
        echo This image is going to be mirrored to $DOCKER_RELEASE_REGISTRY
        docker login -u gitlab+deploy-token-14 -p $GITLAB_TOKEN registry.blueplanet.com
        docker tag $REGISTRY_IMAGE:$IMAGE_TAG  $DOCKER_RELEASE_REGISTRY/$PROJECT_NAME:$IMAGE_TAG
        docker push $DOCKER_RELEASE_REGISTRY/$PROJECT_NAME:$IMAGE_TAG
        echo pushed $DOCKER_RELEASE_REGISTRY/$PROJECT_NAME:$IMAGE_TAG
      fi
    - docker image rm $IMAGE_NAME:$IMAGE_TAG
