# A job to uprev the tag in version.json

# This job will uprev the tag value in version.json
# By default, any changes on the develop branch will trigger this job.
.uprev:
  stage: uprev
  image: $REGISTRY_NAME/docker/blueplanet/devtools/common-ci-cd-automations/misc-python-image:latest
  tags:
    - mdso
  variables:
    GIT_STRATEGY: clone
    MAIN_BRANCH: 'develop'
  dependencies: []
  script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - ssh-keyscan ${CI_SERVER_HOST} >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - source auto_build_set_env

    - git config --global user.name "$GITLAB_USER_NAME"
    - git config --global user.email "$GITLAB_USER_EMAIL"
    - git reset --hard
    - git checkout $CI_COMMIT_REF_NAME
    - git pull origin $CI_COMMIT_REF_NAME
    - git remote -v
    - cat version.json
    - export PROJECT_TAG=$((10#$PROJECT_TAG))
    - export NEW_TAG=$(($PROJECT_TAG+1))
    - echo $NEW_TAG
    - tmp=$(mktemp)
    - jq '.tag = '\"$NEW_TAG\"'' version.json > "$tmp" && mv "$tmp" version.json
    - cat version.json

    - git add version.json
    - git status
    - git commit -m "uprev to $PROJECT_VERSION-$NEW_TAG for $CI_COMMIT_REF_NAME"
    - git status
    - git push origin $CI_COMMIT_REF_NAME # || true
