# A manual job to release the solution or app.
# clears tag field and increments the version number
# also tags the repo with the version #

.release:
  stage: release
  image: $REGISTRY_NAME/docker/blueplanet/devtools/common-ci-cd-automations/misc-python-image:latest
  tags:
    - mdso
  variables:
    GIT_STRATEGY: clone
    MAIN_BRANCH: "master"
  dependencies: []
  script:
    - "which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )"
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - ssh-keyscan ${CI_SERVER_HOST} >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - source auto_build_set_env

    - git config --global user.name "$GITLAB_USER_NAME"
    - git config --global user.email "$GITLAB_USER_EMAIL"
    - git reset --hard
    - git checkout $CI_COMMIT_REF_NAME
    - git pull origin $CI_COMMIT_REF_NAME
    - git remote set-url --push origin "git@${CI_SERVER_HOST}:${CI_PROJECT_PATH}.git"
    - git remote -v

    - cat version.json
    - export PROJECT_VERSION=${PROJECT_VERSION%.*}.$((10#${PROJECT_VERSION##*.}+1))
    - tmp=$(mktemp)
    - jq '.tag = '\"\"'' version.json > "$tmp" && mv "$tmp" version.json
    - jq '.version = '\"$PROJECT_VERSION\"'' version.json > "$tmp" && mv "$tmp" version.json
    - cat version.json

    - git add version.json
    - git status
    - git commit -m "uprev to $PROJECT_VERSION for $CI_COMMIT_REF_NAME"
    - git tag $PROJECT_VERSION
    - git status
    - git push origin $CI_COMMIT_REF_NAME --tags
