# A job to build an offline tarball of a solution using did.
# tarball names as follows: ${PROJECT_NAME//-/_}-${IMAGE_TAG}-did.tgz ${PROJECT_NAME//-/_}/.tgz

.build-did:
  variables:
    MAIN_BRANCH: "master"
  stage: package
  tags:
    - mdso_docker_machine
  image: $REGISTRY_NAME/docker/blueplanet/devtools/common-ci-cd-automations/build-image:latest
  when: manual
  dependencies: []
  script:
    - source auto_build_set_env
    - docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASSWORD $REGISTRY_NAME
    - source get_image_tag
    - IMAGE_NAME=$REGISTRY_NAME/docker/solution-${PROJECT_NAME//-/_}
    - jinja2 -D IMAGE_TAG=${IMAGE_TAG} /usr/local/bin/images.j2 version.json > images.yml
    - cat images.yml
    - sed -i '/^$/d' images.yml
    - sed -i -e '$a\' images.yml
    - source pull_docker_images "images.yml"
    - docker images
    - docker pull ${IMAGE_NAME}:${IMAGE_TAG}
    - docker images
    - /opt/ciena/bp2hosttools/bin/did-save --did ./${PROJECT_NAME//-/_} -s ${PROJECT_NAME//-/_}:${IMAGE_TAG}
    - tar cvzf ${PROJECT_NAME//-/_}-${IMAGE_TAG}-did.tgz ${PROJECT_NAME//-/_}/
    - ls -al
  artifacts:
    paths:
      - ./*.tgz
    when: on_success
    expire_in: 1 week
