stages:
  - test
  - build
  - release

include:
  - local: '/ra-build/.ra-build-ci-template.yml'
    # https://git.blueplanet.com/BluePlanet/DevTools/common-ci-cd-automations/blob/master/ra-build/.ra-build-ci-template.yml
  - local: '/ra-test/.ra-unittest-ci-template.yml'
    # https://git.blueplanet.com/BluePlanet/DevTools/common-ci-cd-automations/blob/master/ra-test/.ra-unittest-ci-template.yml
  - local: '/solution-build/.solution-build-gitlab-ci-template.yml'
    # https://git.blueplanet.com/BluePlanet/DevTools/common-ci-cd-automations/blob/master/solution-build/.solution-build-gitlab-ci-template.yml
  - local: '/lint/.lint-gitlab-ci-template-master.yml'
    # https://git.blueplanet.com/BluePlanet/DevTools/common-ci-cd-automations/blob/master/lint/.lint-gitlab-ci-template-master.yml
  - local: '/pdf/.pdf-gitlab-ci-template.yml'
    # https://git.blueplanet.com/BluePlanet/DevTools/common-ci-cd-automations/blob/master/pdf/.pdf-gitlab-ci-template.yml

hocon-lint:
  stage: test
  extends: .hocon-lint

json-lint:
  stage: test
  extends: .json-lint

flake8:
  stage: test
  extends: .flake8

ra-unit-test:
  stage: test
  extends: .ra-unit-test

# Override standard version naming and use alternate Dockerfile
ra-build:
  stage: build
  before_script:
    - source commonci_set_env_vars
    - export IMAGE_VERSION=$VERSION.$CI_COMMIT_SHORT_SHA
    - export DOCKERFILE=Dockerfile.gitlab
  extends: .ra-build

# Override standard version naming
solution-build:
  stage: build
  before_script:
    - source commonci_set_env_vars
    - export IMAGE_VERSION=$VERSION.$CI_COMMIT_SHORT_SHA
  extends: .solution-build

pdf:
  stage: release
  extends: .pdf
