# Creates python package

.build-package:
  image: $REGISTRY_NAME/docker/blueplanet/devtools/common-ci-cd-automations/misc-python-image:latest
  tags:
    - mdso
  stage: build-package
  variables:
    PROJECT_ID: 3744
  script:
    - if [[ ! -z "${OVERRIDE_PROJECT_ID}" ]]; then export PROJECT_ID=$OVERRIDE_PROJECT_ID; fi
    - python3 setup.py sdist bdist_wheel
    - TWINE_PASSWORD=$DOCKER_REGISTRY_PASSWORD TWINE_USERNAME=$DOCKER_REGISTRY_USER python -m twine upload --skip-existing --repository-url https://artifactory.ciena.com/api/pypi/blueplanet-pypi dist/* --verbose
    - TWINE_PASSWORD=$GITLAB_TOKEN TWINE_USERNAME=__token__ python -m twine upload --skip-existing --repository-url "https://git.blueplanet.com/api/v4/projects/$PROJECT_ID/packages/pypi" dist/* --verbose

  # rules:
  #   - if: $CI_COMMIT_REF_NAME == "master"
  #     when: on_success
  only:
    refs:
      - master
