# Job to build pypi based on requirements files in model-definitions
# Version.json must be specified for name & version of the pypi image
# Builds standalone solution & app

.pypi-build:
  stage: build
  tags:
    - mdso
  image: $REGISTRY_NAME/docker/blueplanet/devtools/common-ci-cd-automations/build-image:latest
  dependencies: []
  variables:
    DOCKER_CLI_EXPERIMENTAL: "enabled"
    PUSH_PYPI_SOLUTION: "true"
  script:
    - source auto_build_set_env
    - source get_image_tag
    - echo $IMAGE_TAG
    - docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASSWORD $REGISTRY_NAME
    - >
      if docker manifest inspect $REGISTRY_NAME/$VENDOR_NAME/$PROJECT_NAME-pypi:$IMAGE_TAG 1>/dev/null ; then
          echo "
          *********************************************
          *
          * ERROR: $REGISTRY_NAME/$VENDOR_NAME/$PROJECT_NAME-pypi:$IMAGE_TAG already exists on registry
          *
          * Troubleshooting:
          * - Was this manually pushed to the docker registry?
          * - Pypi version does not currently get automatically upreved. Please bump up the version manually in \`version.json\`. (Don't forget to bump up the solution version/tag!)
          *
          *********************************************"
          exit 1
      else
          echo Building $REGISTRY_NAME/$VENDOR_NAME/$PROJECT_NAME-pypi:$IMAGE_TAG
      fi
    - >
      if docker manifest inspect $REGISTRY_NAME/$VENDOR_NAME/solution-"${PROJECT_NAME//-}"pypi:$IMAGE_TAG 1>/dev/null ; then
          echo "
          *********************************************
          *
          * ERROR: $REGISTRY_NAME/$VENDOR_NAME/solution-"${PROJECT_NAME//-}"pypi:$IMAGE_TAG already exists on registry
          *
          * Troubleshooting:
          * - Was this manually pushed to the docker registry?
          * - Pypi version does not currently get automatically upreved. Please bump up the version manually in \`version.json\`. (Don't forget to bump up the solution version/tag!)
          *
          *********************************************"
          exit 1
      else
          echo Building $REGISTRY_NAME/$VENDOR_NAME/solution-"${PROJECT_NAME//-}"pypi:$IMAGE_TAG
      fi
    - mkdir  -p dist
    - reqs3=$(pypi_req_finder -p 3 | tr -d "\'{},")
    - echo $reqs3
    - for package in $reqs3; do pip3 download --dest dist -i https://$pypiUser:$pypiToken@$blueplanetPypi --extra-index-url https://pypi.org/simple $package; done
    - ls ./dist
    - mkpypi -p ./dist -a $REGISTRY_NAME/$VENDOR_NAME/$PROJECT_NAME-pypi:$IMAGE_TAG
      -s $REGISTRY_NAME/$VENDOR_NAME/solution-"${PROJECT_NAME//-}"pypi:$IMAGE_TAG > PYPI.tar
    - docker load < PYPI.tar
    - PYPI_APP=$REGISTRY_NAME/$VENDOR_NAME/$PROJECT_NAME-pypi:$IMAGE_TAG
    - docker push $PYPI_APP
    - docker image rm $PYPI_APP
    - >
      if $PUSH_PYPI_SOLUTION; then
        PYPI_SOL=$REGISTRY_NAME/$VENDOR_NAME/solution-"${PROJECT_NAME//-}"pypi:$IMAGE_TAG
        docker push $PYPI_SOL
        docker image rm $PYPI_SOL
      fi
    - >
      if [ -z ${CI_MERGE_REQUEST_ID+x} ] && [[ ! -z "$CHANNEL_SLACK_WEBHOOK_URL" ]] ; then  curl -X POST --data "{\"text\":\":tada: Pushed $PYPI_APP & $PYPI_SOL \"}" $CHANNEL_SLACK_WEBHOOK_URL; fi
  only:
    refs:
      - master
      - /^release\/\d+\.\d+.*$/
      - develop
      - merge_requests
  #   changes:
  #     - model-definitions/*.txt
  when: manual
