# A job to uprev the tag in version.json of the solution repo


.update-remote-solution:
  variables:
    MAIN_BRANCH: "master"
  stage: update-remote-solution
  image: $REGISTRY_NAME/docker/blueplanet/devtools/common-ci-cd-automations/build-image:latest
  tags:
    - mdso_docker_machine
  dependencies: []
  script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - ssh-keyscan $REGISTRY_NAME >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - source auto_build_set_env
    - source get_image_tag

    - git config --global user.name "$GITLAB_USER_NAME"
    - git config --global user.email "$GITLAB_USER_EMAIL"
    - echo Cloning project from $PROJECT_PATH/$SOLUTION_REPO_NAME
    - git clone git@$REGISTRY_NAME:$PROJECT_PATH/$SOLUTION_REPO_NAME.git /tmp/solution
    - cd /tmp/solution
    - git checkout $CI_COMMIT_REF_NAME
    - git pull
    - cat version.json
    - export SOLUTION_TAG=$((10#$(cat version.json | jq -r .tag)))
    - export NEW_TAG=$(($SOLUTION_TAG+1))
    - echo $NEW_TAG
    - tmp=$(mktemp)
    - jq '.tag = '\"$NEW_TAG\"'' version.json > "$tmp" && mv "$tmp" version.json
    - jq '.apps |= map(if .name=='\"$PROJECT_NAME\"' then .version='\"$IMAGE_TAG\"' else . end)' version.json > "$tmp" && mv "$tmp" version.json
    - cat version.json
    - git add version.json
    - git status
    - git commit -m "uprev $PROJECT_NAME to $PROJECT_VERSION-$NEW_TAG in $CI_COMMIT_REF_NAME branch"
    - git status
    - git push origin $CI_COMMIT_REF_NAME # || true
