.push-to-devOpsExchange:
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  tags:
    - aws
  stage: deploy
  script:
    - >
      if [[ -n "$DOC_NAME" ]]; then
        NAME=$DOC_NAME
      else
        echo "No \$DOC_NAME variable set. Going to use $CI_PROJECT_NAME as name of doc"
        NAME=$CI_PROJECT_NAME
      fi
    - aws s3 sync .$HTML_DOCS_PATH s3://$DOCS_BUCKET_NAME/docs/$NAME
    - aws cloudfront create-invalidation --distribution-id $PROD_DISTRIBUTION_ID --paths /docs/$NAME/*
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      when: manual
    - if: $TRIGGER == "run"