.build:doc:
  image: python:3
  tags:
    - ciena
  stage: build
  # Needs gitlab version 13.10+ https://gitlab.com/gitlab-org/gitlab/-/issues/31264
  # needs: []
  before_script:
    # Install sphinx related requirements
    - >
      if [[ -f "requirements_docs.txt" ]]; then
        python3 -m pip install -r requirements_docs.txt
      else
        echo "requirements_docs.txt doesn't exist. Defaulting to only installing sphinx"
        pip install sphinx
      fi
  script:
    - python3 setup.py build_sphinx
  artifacts:
    expire_in: 30 days
    paths:
      - build/
    when: on_success
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: manual
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      when: on_success


.push-doc:
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  tags:
    - aws
  stage: .post
  needs: [ 'build:doc' ]
  script:
    - >
      if [[ -n "$DOC_NAME" ]]; then
        NAME=$DOC_NAME
      else
        echo "No \$DOC_NAME variable set. Going to use $CI_PROJECT_NAME as name of doc"
        NAME=$CI_PROJECT_NAME
      fi
    - aws s3 sync ./build/html s3://$DOCS_BUCKET_NAME/docs/$NAME
    - aws cloudfront create-invalidation --distribution-id $DOCS_DISTRIBUTION_ID --paths /docs/$NAME/*
  rules:
    # Needs gitlab version 13.10+ https://gitlab.com/gitlab-org/gitlab/-/issues/31264
    # - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    #   when: manual
    #   allow_failure: true
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      when: on_success
