# pathid
DARKFIBER_TYPES = ("CAR-DARKFIBER", "CAR-CTBH DARKFIBER", "COM-DARKFIBER")

ENNI_TYPES = ("CAR-DOCSIS/FIBER EPL", "CAR-E-ACCESS FIBER/FIBER EPL", "CAR-E-ACCESS FIBER/DOCSIS EPL", "CAR-CTBH 4G")

EPL_TYPES = (
    "CAR-DOCSIS ONLY EPL",
    "CAR-DOCSIS/FIBER EPL",
    "CAR-E-ACCESS FIBER/FIBER EPL",
    "CAR-E-TRANSPORT FIBER/FIBER EPL",
    "CAR-EPL",
    "COM-DOCSIS ONLY EPL",
    "COM-DOCSIS/FIBER EPL",
    "COM-EPL",
)

ETHERNET_TYPES = (
    "CAR E-TRANSPORT FIBER/FIBER EPL",
    "CAR-CTBH 4G",
    "CAR-DOCSIS ONLY EPL",
    "CAR-DOCSIS ONLY EVPL",
    "CAR-DOCSIS/FIBER EPL",
    "CAR-DOCSIS/FIBER EPLAN",
    "CAR-DOCSIS/FIBER EVPL",
    "CAR-DOSCIS ONLY EPLAN",
    "CAR-E-ACCESS FIBER/DOCSIS EPL",
    "CAR-E-ACCESS FIBER/FIBER EPL",
    "CAR-E-TRANSPORT FIBER/FIBER EPL",
    "CAR-EOD (ETHERNET OVER DOCSIS)",
    "CAR-EPL",
    "CAR-EPLAN",
    "CAR-ETHERNET OVER FIBER (EOF)",
    "CAR-EVPL",
    "COM-DOCSIS ONLY EPL",
    "COM-DOCSIS ONLY EPLAN",
    "COM-DOCSIS ONLY EVPL",
    "COM-DOCSIS/FIBER EP-LAN",
    "COM-DOCSIS/FIBER EPL",
    "COM-DOCSIS/FIBER EPLAN",
    "COM-DOCSIS/FIBER EVPL",
    "COM-DOCSIS/FIBER EVPL",
    "COM-EOD (ETHERNET OVER DOCSIS)",
    "COM-EPL",
    "COM-EPLAN",
    "COM-EVPL",
)

HOSPITALITY_TYPES = (
    "COM-VIDEO DCI",
    "COM-VIDEO INSERTION",
    "COM-VIDEO OVER IP",
    "COM-VIDEO SBB",
    "CUS-VIDEO-FC PLUS-IP",
    "CUS-VIDEO-FC PLUS-RPHY",
    "CUS-VIDEO-FIBER CONNECT",
    "CUS-VIDEO-FIBER CONNECT PLUS",
    "CUS-VIDEO-IP",
)

MANAGED_TYPES = ("INT-MANAGEMENT",)

OTHER_TYPES = ("CAR-DIA", "COM-DIA", "CUS-VIDEO-PEG", "CUS-SECURE INTERNET ACCESS")

RF_TYPES = (
    "COM-VIDEO DCI",
    "COM-VIDEO INSERTION",
    "COM-VIDEO OVER IP",
    "COM-VIDEO SBB",
    "CUS-VIDEO-FIBER CONNECT",
    "CUS-VIDEO-FIBER CONNECT PLUS",
    "CUS-VIDEO-IP",
)

VOICE_TYPES = ("CUS-VOICE-HOSTED", "CUS-VOICE-PRI", "CUS-VOICE-SIP", "CUS-CLOUD-CALLING")

WAVE_TYPES = ("CAR-WAVELENGTH", "COM-WAVELENGTH")

WIRELESS_TYPES = ("CUS-INTERNET ACCESS",)

# site
ABBREVIATIONS = {
    "AVENUE": "AVE",
    "BOULEVARD": "BLVD",
    "CENTER": "CTR",
    "CIRCLE": "CIR",
    "COURT": "CT",
    "FORT": "FT",
    "FREEWAY": "FWY",
    "HIGHWAY": "HWY",
    "INTERSTATE": "I",
    "LANE": "LN",
    "MOUNT": "MT",
    "MOUNTAIN": "MT",
    "PARKWAY": "PKWY",
    "ROAD": "RD",
    "ROUTE": "RT",
    "SAINT": "ST",
    "STREET": "ST",
    "SQUARE": "SQ",
}

CTBH_ABBREVIATIONS = {
    "AT&T": "ATT",
    "CAROLINA WEST WIRELESS": "CAW",
    "CLEARWIRE": "CLW",
    "DISH WIRELESS": "DISH",
    "FIBERLIGHT": "FBR",
    "PARADIGM": "PAR",
    "SPRINT": "SPR",
    "SUDDENLINK": "SDK",
    "T-MOBILE": "TMO",
    "US CELLULAR": "USC",
    "VERIZON WIRELESS": "VZW",
}

# must stay in this order
BAD_UNITS = (
    "ACCT",
    "ALT",
    "AWS",
    "BASEMENT",
    "CELLAR",
    "CMPTR",
    "COAX",
    "COMM",
    "COM RM",
    "COMRAC",
    "COSTCO",
    "DATACB",
    "DATA",
    "DELIVERY",
    "DIA",
    "DIVERSITY",
    "DONOFC",
    "DTA",
    "ELAN",
    "ELCTIC",
    "ENT",
    "EPLAN",
    "EPL",
    "ERATE",
    "ETHERNET",
    "EVPL",
    "FBRCON",
    "FBR",
    "FCP",
    "FC+",
    "FC",
    "FH",
    "FIA",
    "FIBER CONNECT PLUS",
    "FIBER",
    "FIBMNE",
    "FIB",
    "FIHSD",
    "IFININT",
    "WIFI",
    "FI",
    "FNSH",
    "GEMS",
    "HC",
    "HD",
    "HV",
    "HSD",
    "HUB",
    "TOWER IDF",
    "IDF",
    "INTERNET",
    "INT",
    "SIP",
    "IP",
    "IT RM",
    "LCPMDF",
    "LOCAL",
    "MAIN",
    "MASTER",
    "MCDS",
    "MNE",
    "MN",
    "MPOE",
    "MRS",
    "MSS",
    "NAT",
    "NEW",
    "NETWRK",
    "NTL",
    "NTWRKC",
    "PACIF",
    "PEG",
    "PLUS",
    "PRI",
    "PRO I",
    "REMOTE PHY",
    "RNGCTL",
    "REST",
    "RINGC",
    "RMBACK",
    "RMDATA",
    "RMMDF",
    "RM MDF",
    "MDF",
    "RM OFF",
    "RMMPOE",
    "RMSERV",
    "RMVDC",
    "RRC",
    "RC",
    "RVPARK",
    "SBB119",
    "SBB",
    "SCHOOL",
    "SERVER",
    "VIDEO SERVICE",
    "SERV",
    "SSU",
    "STE",
    "ST",
    "IP",
    "TYPE II",
    "1TELCO",
    "TELCOM",
    "TELCO",
    "TELC",
    "TRLR",
    "TYPE II",
    "UC-OFF",
    "UCRC",
    "UC",
    "USED",
    "VIDEO DIV",
    "WATER RP",
    "WAVE1",
    "WIA",
)

BAD_WORDS = ("FIBER", "HQ", "MASTER", "NATIONAL", "NATL", "NTL", "SUBGROUP")

LOCAL = ("CUST_OFFNET", "CUST_PREM", "LOCAL")

NON_LOCAL = ("COLO", "COLO-NETWORK", "POP", "POP-NETWORK")

MTU = ("ACTIVE MTU", "PASSIVE MTU")

ROOM_TYPES = ("APT", "BLDG", "BLD", "BUILDING", "OFC", "OFFICE", "RM", "ROOM", "STE", "SUITE", "SUIT", "UNIT")
