.flake8-py27:
  image: python:2.7
  stage: lint
  tags:
    - docker
  script:
    - pip install flake8
    - flake8 .
  # rules:
  #   - exists:
  #     - "**.py"
  #     changes:
  #     - "**.py"
  only:
    refs:
      - merge_requests
      - develop
      - master
      - tags
    changes:
      - "**/*.py"

.flake8:
  image: $REGISTRY_NAME/docker/blueplanet/devtools/common-ci-cd-automations/lint-image:latest
  stage: lint
  tags:
    - docker
  script:
    - flake8 .
  # rules:
  #   - exists:
  #     - "**.py"
  #     changes:
  #     - "**.py"
  only:
    refs:
      - merge_requests
      - develop
      - master
      - tags
    changes:
      - "**/*.py"

.hocon-lint:
  image: $REGISTRY_NAME/docker/blueplanet/devtools/common-ci-cd-automations/lint-image:latest
  stage: lint
  tags:
    - docker
  script:
    - >
      if [[ `find . -type f -name "*.tosca"` ]]; then
        find . -type f -name "*.tosca" -print0 | xargs -0 -n1  bash -c 'echo -e "\n========== validating $0 ==========\n" ; hocon-validator "$0" /usr/local/src/jsonschema.yml'
      else
        echo No .tosca files found
      fi
  # rules:
  #   - exists:
  #     - "**.tosca"
  #     changes:
  #     - "**.tosca"
  only:
    refs:
      - merge_requests
      - develop
      - master
      - tags
    changes:
      - "**/*.tosca"

.json-lint:
  image: $REGISTRY_NAME/docker/blueplanet/devtools/common-ci-cd-automations/lint-image:latest
  stage: lint
  tags:
    - docker
  script:
    - jsonlint-tree . 2>&1 | tee output.txt
    - >
      if grep -q Error output.txt ; then
        echo Invalid JSON! See errors above
        exit 1
      fi
  # rules:
  #   - exists:
  #     - "**.json"
  #     changes:
  #     - "**.json"
  only:
    refs:
      - merge_requests
      - develop
      - master
      - tags
    changes:
      - "**/*.json"

# Checks for legacy scripts (aka plan type = script and runs in bpocore). Will not fail pipeline but will raise warning
.legacy-script-check:
  image: $REGISTRY_NAME/docker/blueplanet/devtools/common-ci-cd-automations/lint-image:latest
  stage: lint
  tags:
    - docker
  script:
    # Checks no longer required if/when we can bring rules back again
    - if [[ -d "model-definitions" ]]; then python3 /usr/local/bin/legacy_script_checker.py -m model-definitions; fi
  allow_failure: true
  # rules:
  #   - exists:
  #     - "**.tosca"
  #     changes:
  #     - "**.py"
  only:
    refs:
      - merge_requests
      - master
      - tags
    changes:
      - "**/*.py"

# Checks for use of Python 3.8
.python-version-check:
  image: $REGISTRY_NAME/docker/blueplanet/devtools/common-ci-cd-automations/lint-image:latest
  stage: lint
  tags:
    - docker
  script:
    # Checks no longer required if/when we can bring rules back again
    - if [[ -d "model-definitions" ]]; then python3 /usr/local/bin/python_version_check.py -m model-definitions; fi
  allow_failure: true
  # rules:
  #   - exists:
  #     - "**.tosca"
  #     changes:
  #     - "**.py"
  only:
    refs:
      - merge_requests
      - master
      - tags
    changes:
      - "**/*.py"

# Checks for use of use PlanSDK methods that are deprecated
.plansdk-deprecated-check:
  image: $REGISTRY_NAME/docker/blueplanet/devtools/common-ci-cd-automations/lint-image:latest
  stage: lint
  tags:
    - aws
  script:
    - 'curl -s -L --output plansdk_deprecated_methods.json --header "PRIVATE-TOKEN: ${GITLAB_TOKEN}" "https://git.blueplanet.com/api/v4/projects/1303/jobs/artifacts/master/raw/plansdk_deprecated_methods.json?job=deprecated-methods-list"'
    - python3 /usr/local/bin/deprecated_method_check.py --model-def model-definitions --depr-list plansdk_deprecated_methods.json
  only:
    refs:
      - merge_requests
      - master
      - tags
    changes:
      - "**/*.py"

# Repo must be setup to with `npm run lint`
.eslint:
  stage: lint
  image: docker.io/node:current
  tags:
    - docker
  script:
    - npm i
    - npm set unsafe-perm true
    - npm run lint
  only:
    refs:
      - merge_requests
      - master
      - tags
    changes:
      - "**/*.js"
      - "**/*.jsx"
      - "**/*.ts"
      - "**/*.tsx"
      - "**/*.es6"
      - "**/*.mjs"
