---
commitizen:
  annotated_tag: true
  bump_message: 'bump: release $current_version -> $new_version [skip-ci]'
  changelog_incremental: true
  name: cz_conventional_commits
  tag_format: $version
  update_changelog_on_bump: true
  version: 1.58.43
  version_files:
  - VERSION
