## Set $SLACK_WEBHOOK_URL variable in job
.pipeline-failure-notification:
  image: registry.blueplanet.com/blueplanet/devtools/common-ci-cd-automations/lint-image:latest
  stage: .post
  tags:
    - docker
  script:
    - gitlab -v -o json project-pipeline-job list  --project-id $CI_PROJECT_ID --pipeline-id $CI_PIPELINE_ID > jobs
    - FAILED=$(jq -r '.[] | select(.status=="failed") | .name ' jobs)
    - FAILED="\`${FAILED//+([[:space:]])/\`\n\`}\`"
    - echo Failed jobs = $FAILED
    - >
      if [ $FAILED != "\`\`" ] ; then curl -X POST --data "{\"text\":\":poop:*OH NO!* :poop: The following job(s)-\n $FAILED failed in project $CI_PROJECT_NAME (merge ID- $CI_MERGE_REQUEST_ID).
      \nCheck $CI_PIPELINE_URL for more info\"}" $SLACK_WEBHOOK_URL ; fi
  only:
    refs:
      - master
      - /^release\/\d+\.\d+.*$/
  when: always
