# Job for non-ra onboard type apps
# Includes linting, app build etc

include:
  - local: 'code-quality/.code-climate.yml'
  - local: 'auto-build/.auto-build-maven.yml'

stages:
  - lint
  - test
  - uprev
  - build:mvn
  - build
  - update-remote-solution
  - release


# Lint

.code-quality-post-bump:
  extends: .code-quality
  stage: .post
  only:
    refs:
      - merge_requests
      - master
      - tags
      - /^release\/\d+\.\d+.*$/

