.ra-build:
  image: registry.blueplanet.com/blueplanet/devtools/common-ci-cd-automations/ra-build-image:0.0.3
  stage: build
  tags:
    - docker
  script:
    - if [[ -z "${CI_REGISTRY_IMAGE}" ]]; then echo "FAILURE.  Enable docker registry for the project. https://docs.gitlab.com/ee/user/project/container_registry.html#enable-the-container-registry-for-your-project" && false;fi
    - source commonci_set_env_vars
    - if [[ -z "${DOCKERFILE}" ]]; then echo "FAILURE.  Set the Dockerfile to use. i.e. export DOCKERFILE=Dockerfile" && false;fi
    - if [[ -z "${VENDOR}" ]]; then echo "FAILURE.  Enable the docker registry on the project. https://docs.gitlab.com/ee/user/project/container_registry.html#enable-the-container-registry-for-your-project" && false;fi
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build
      --build-arg PYPI="https://pypi.org/simple --extra-index-url https://gitlab-ci-token:$CI_JOB_TOKEN@pypi.blueplanet.com/simple"
      --build-arg pypi="https://pypi.org/simple --extra-index-url https://gitlab-ci-token:$CI_JOB_TOKEN@pypi.blueplanet.com/simple"
      -f $DOCKERFILE
      -t $REGISTRY/$VENDOR/$NAME:$IMAGE_VERSION .
    - docker push $REGISTRY/$VENDOR/$NAME:$IMAGE_VERSION
    - docker tag $REGISTRY/$VENDOR/$NAME:$IMAGE_VERSION $REGISTRY/$VENDOR/$NAME:$VERSION
    - if [ "$CI_COMMIT_REF_NAME" == "master" ]; then docker push $REGISTRY/$VENDOR/$NAME:$VERSION && echo "SUCCESS. Pushed $REGISTRY/$VENDOR/$NAME:$VERSION"; fi
    - echo "SUCCESS. Pushed $REGISTRY/$VENDOR/$NAME:$IMAGE_VERSION"
  except:
    variables:
    - $CI_COMMIT_MESSAGE =~ /\[skip[ _-]image?\]/i
    - $SCHEDULE_SKIP =~ /\[skip[ _-]image?\]/i
