# A job to use did to push solution to a remote server
# Must be accessible via ciena network


.did-push:
  variables:
    USER: "root"
    MAIN_BRANCH: master
  stage: deploy
  when: manual
  image: registry.blueplanet.com/blueplanet/devtools/common-ci-cd-automations/build-image:latest
  dependencies: []
  script:
    - apt-get update && apt-get install rsync -y
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - echo "$DEST_SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - source auto_build_set_env
    - source get_image_tag
    - >
      if [[ -z "$DEST_BP"  ]]; then
      echo "Please set the DEST_BP variable for this job" &&  false;
      else echo "Copying ${PROJECT_NAME//-/_}:${IMAGE_TAG} to $DEST_BP on $USER account"; fi
    - docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASSWORD $REGISTRY_NAME
    - jinja2 -D IMAGE_TAG=${IMAGE_TAG} /usr/local/bin/images.j2 version.json > images.yml
    - cat images.yml
    - sed -i '/^$/d' images.yml
    - sed -i -e '$a\' images.yml
    - source pull_docker_images "images.yml"
    - docker images
    - docker pull artifactory.ciena.com/blueplanet/solution-${PROJECT_NAME//-/_}:${IMAGE_TAG}
    - docker images
    - /opt/ciena/bp2hosttools/bin/did-save -s ${PROJECT_NAME//-/_}:${IMAGE_TAG}
    - /opt/ciena/bp2hosttools/bin/did-push --dest $USER@$DEST_BP:did -s ${PROJECT_NAME//-/_}:${IMAGE_TAG}
    - ssh $USER@$DEST_BP "did-load -s ${PROJECT_NAME//-/_}:${IMAGE_TAG}"
    - export SOL_NAME=artifactory.ciena.com.blueplanet.${PROJECT_NAME//-/_}
    - SOL_TO_UNDEP=$(ssh $USER@$DEST_BP "solman sps | grep ^$SOL_NAME" 2>&1)
    - echo Undeploying $SOL_TO_UNDEP
    - >
      while read line
        do [ ! -z "$line" ] && ssh $USER@$DEST_BP "solman 'solution_undeploy $line'"
      done <<< "$SOL_TO_UNDEP"
    - ssh $USER@$DEST_BP \
      "sudo solman 'solution_deploy artifactory.ciena.com.blueplanet.${PROJECT_NAME//-/_}:${IMAGE_TAG}'"
