# Supported service types from Granite and Salesforce
FIA_SERVICES = [
    "Fiber Internet Access",
    "Carrier Fiber Internet Access",
    "CAR-DIA",
    "COM-DIA",
    "COM-MSS DIA",
    "COM-MRS_MSS DIA",
    "COM-MRS INTERNET DIA",
    "CUS-SECURE INTERNET ACCESS",
]


ELINE_SERVICES = [
    "EPL (Fiber)",
    "EPL (Type II)",
    "EVPL (Fiber)",
    "EVPL (Type II)",
    "Carrier E-Access (Fiber)",
    "Carrier E-Access (Type II)",
    "COM-EPL",
    "COM-EVPL",
    "CAR-E-ACCESS FIBER/FIBER EPL",
    "CAR-E-ACCESS FIBER/FIBER EVPL",
    "COM-MRS EPL",
    "COM-MRS EVPL",
]


VOICE_SERVICES = [
    "PRI Trunk (Fiber)",
    "PRI Trunk(Fiber) Analog",
    "CUS-VOICE-PRI",
    "SIP - Trunk (Fiber)",
    "SIP Trunk(Fiber) Analog",
    "CUS-VOICE-SIP",
]


HOSTED_VOICE_SERVICES = ["Hosted Voice - (Fiber)", "CUS-VOICE-HOSTED"]


VIDEO_SERVICES = ["FC + Remote PHY", "CUS-VIDEO-FC PLUS-RPHY"]


CTBH_SERVICES = ["CTBH 4G", "Carrier CTBH", "CAR-CTBH 4G"]


NNI_SERVICES = ["NNI", "CAR-NNI"]


ELAN_SERVICES = ["COM-EPLAN", "CAR-EPLAN", "EP-LAN (Fiber)", "EVP-LAN", "COM-MRS EPLAN"]


TRUNKED_SERVICES = [
    "Hosted Voice - (Fiber)",
    "CUS-VOICE-HOSTED",
    "COM-MSS DIA",
    "COM-MRS_MSS DIA",
    "COM-MRS INTERNET DIA",
]

# Supported service types by workstream
DISCONNECT_COMPLIANCE_SERVICES = FIA_SERVICES + ELINE_SERVICES + VOICE_SERVICES + ELAN_SERVICES


NEW_COMPLIANCE_SERVICES = (
    FIA_SERVICES + ELINE_SERVICES + VOICE_SERVICES + HOSTED_VOICE_SERVICES + ELAN_SERVICES + NNI_SERVICES + CTBH_SERVICES
)


MAC_COMPLIANCE_SERVICES = (
    FIA_SERVICES + ELINE_SERVICES + VOICE_SERVICES + HOSTED_VOICE_SERVICES + ELAN_SERVICES + CTBH_SERVICES
)


PROVISIONING_SERVICES = (
    FIA_SERVICES
    + ELINE_SERVICES
    + VOICE_SERVICES
    + HOSTED_VOICE_SERVICES
    + VIDEO_SERVICES
    + CTBH_SERVICES
    + NNI_SERVICES
    + ELAN_SERVICES
)


CEVLAN_SERVICES = tuple(CTBH_SERVICES)


# Supported request order types
UPDATE_TYPES = ["bw"]


NEW_ORDER = "NEW"
CHANGE_ORDER = "CHANGE"
DISCONNECT_ORDER = "DISCONNECT"


NEW_SERVICE_REQUEST_ORDER_TYPE = ["New Install"]


NEW_ENGINEERING_JOB_TYPE = ["New", "Add"]

CHANGE_SERVICE_REQUEST_ORDER_TYPE = ["Change Request"]


CHANGE_ENGINEERING_JOB_TYPE = ["Upgrade", "Express BW Upgrade", "Downgrade"]


GENERAL_ORDER_TYPES = NEW_ORDER + CHANGE_ORDER + DISCONNECT_ORDER


SALESFORCE_ORDER_TYPES = {
    "NEW": ["New Install", "New", "NEW"],
    "CHANGE": ["Add", "Change Request", "Conversion New Install", "Move", "Price Change", "Renewal"],
    "DISCONNECT": ["Disconnect", "Full Disconnect", "Partial Disconnect"],
}


# Equipment types from Granite data required to model topology
EQUIPMENT_TYPES = ("ROUTER", "SWITCH", "NIU", "OPTICAL LINE TERMINAL", "OPTICAL", "NETWORK UNIT")

# Supported device models
JUNIPER_MX_MODELS = ("MX240", "MX480", "MX960", "MX480 ETHERNET ROUTER", "MX960 ETHERNET ROUTER", "MX80 MODULAR")
JUNIPER_QFX_MODELS = ("QFX5100-96S",)
JUNIPER_ACX_MODELS = ("ACX5448",)
JUNIPER_EX_MODELS = ("EX4200-48T", "EX4200-24F", "EX4200-24T")

RAD_220_MODELS = ("ETX-220A",)
RAD_203_MODELS = ("ETX203AX/2SFP/2UTP2SFP", "ETX-203AX/GE30/2SFP/4UTP", "ETX-203AX/N/GE30/2SFP/2UTP")
RAD_2I_MODELS = (
    "RAD ETX-2I-10G/4SFPP/4SFP4UTP",
    "ETX-2I-10G/4SFPP/4SFP4UTP",
    "ETX-2I-10G/4SFPP/24SFP",
    "ETX-2I-10G-B/8.5/8SFPP",
    "ETX-2I-10G-B/19/8SFPP",
    "ETX-2I-10G-B/ODU/8SFPP",
)

ADVA_114_MODELS = ("FSP 150CC-GE114/114S", "FSP 150-GE114PRO-C")
ADVA_120_MODELS = ("FSP 150-XG120PRO",)
ADVA_116_MODELS = ("FSP 150-XG116PRO",)
ADVA_116H_MODELS = ("FSP 150-XG116PROH",)
ADVA_108_MODELS = ("FSP 150-XG108",)
ADVA_118_MODELS = ("FSP 150-XG118PRO (SH)",)

CISCO_9K_MODELS = ("ASR 9006", "ASR 9001", "ASR 9010")
CISCO_920_MODELS = ("ASR-920-12CZ", "ASR-920-24SZ", "ASR-920-4SZ-A")
CISCO_ME3400_MODELS = ("ME-3400E-24TS-M", "ME-3400EG-12CS-M", "ME-3400-EG-12CS-M", "ME-3400EG-2CS-A", "ME-3400-2CS")

CIENA_MODELS = ("CIENA 3931",)

NOKIA_7750_MODELS = ("7750 SR-7", "7750 SR-2S", "7750 SR-12", "7750 SR-1")

NOKIA_7705_MODELS = ("7705 SAR-8", "7705 SAR-18", "7705 SAR-M", "7705 SAR-F")

NOKIA_7210_MODELS = ("7210 SAS-MXP", "7210 SAS-M (10GIGE)", "7210 SAS-M", "7210 SAS-D")


# Devices by vendor and generalized model
DEVICES = {
    "JUNIPER": {"MX": JUNIPER_MX_MODELS, "QFX": JUNIPER_QFX_MODELS, "ACX": JUNIPER_ACX_MODELS, "EX": JUNIPER_EX_MODELS},
    "RAD": {"220": RAD_220_MODELS, "203": RAD_203_MODELS, "2I": RAD_2I_MODELS},
    "ADVA": {
        "114": ADVA_114_MODELS,
        "120": ADVA_120_MODELS,
        "116": ADVA_116_MODELS,
        "116H": ADVA_116H_MODELS,
        "108": ADVA_108_MODELS,
        "118": ADVA_118_MODELS,
    },
    "CISCO": {"9K": CISCO_9K_MODELS, "920": CISCO_920_MODELS, "ME3400": CISCO_ME3400_MODELS},
    "CIENA": {"CIENA": CIENA_MODELS},
    "NOKIA": {"7750": NOKIA_7750_MODELS, "7705": NOKIA_7705_MODELS, "7210": NOKIA_7210_MODELS},
}
